In [2]:
import json
import re
import random
import numpy as np
import pandas as pd
from sklearn.metrics import classification_report, confusion_matrix, f1_score, accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.utils.class_weight import compute_class_weight
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.linear_model import SGDClassifier
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.naive_bayes import ComplementNB

In [3]:
URL_RE     = re.compile(r"(https?://\S+|www\.\S+|\{URL\})", re.IGNORECASE)
MENTION_RE = re.compile(r"@\w+")
HASHTAG_RE = re.compile(r"#(\w+)")

In [5]:
def clean_text(s: str) -> str:
    if not isinstance(s, str):
        return ""
    s = s.strip()
    s = URL_RE.sub(" [URL] ", s)
    s = MENTION_RE.sub(" [MENTION] ", s)
    s = HASHTAG_RE.sub(r" [HASHTAG:\1] ", s)
    s = re.sub(r"\s+", " ", s)
    return s

def eval_split(model, X, y, split_name="VAL"):
    """
    Evalúa el modelo y devuelve un diccionario con métricas clave.
    También imprime el informe detallado.
    """
    preds = model.predict(X)

    f1m = f1_score(y, preds, average="macro")
    acc = accuracy_score(y, preds)

    print(f"\n=== {split_name} ===")
    print(classification_report(y, preds, digits=4))
    print("Confusion matrix:\n", confusion_matrix(y, preds))
    print("F1-macro:", f"{f1m:.4f}")
    print("Accuracy:", f"{acc:.4f}")

    return {
        "f1_macro": f1m,
        "accuracy": acc,
    }

def eval_split(model, X, y, split_name="VAL"):
    """
    Evalúa el modelo y devuelve un diccionario con métricas clave.
    También imprime el informe detallado.
    """
    preds = model.predict(X)

    f1m = f1_score(y, preds, average="macro")
    acc = accuracy_score(y, preds)

    print(f"\n=== {split_name} ===")
    print(classification_report(y, preds, digits=4))
    print("Confusion matrix:\n", confusion_matrix(y, preds))
    print("F1-macro:", f"{f1m:.4f}")
    print("Accuracy:", f"{acc:.4f}")

    return {
        "f1_macro": f1m,
        "accuracy": acc,
    }

In [6]:
def load_jsonl(path):
    rows = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            rows.append(json.loads(line))
    return pd.DataFrame(rows)

def load_ethos(path):
    df = pd.read_csv(path)

    # Drop rows without tweet text
    df = df[df["tweet"].astype(str).str.strip() != ""].copy()

    # Clean text
    df["clean"] = df["tweet"].apply(clean_text)

    # Binary hate label (adapt if your coding is different)
    df["label"] = (df["sentiment"].astype(str).str.lower() == "hate").astype(int)

    # Version with only tweet and target
    df_min = df[["tweet", "target"]].copy()

    return df, df_min

In [7]:
def load_and_clean_tweethate(path, text_field="text"):
    """
    Carga un JSONL tipo supertweeteval, filtra texto vacío,
    elimina NaN reales y NaN en string en predicted_hate_category,
    genera label binaria y limpia el texto.

    Devuelve:
        df : DataFrame limpio y con columnas:
             - text_field
             - predicted_hate_category
             - label (0/1)
             - clean (texto limpio)
    """
    # ====== Carga ======
    rows = load_jsonl(path)
    df = pd.DataFrame(rows)

    # ====== 1. Filtrar texto no vacío ======
    df = df[df[text_field].apply(lambda x: isinstance(x, str) and x.strip() != "")].copy()

    # ====== 2. Eliminar NaN reales ======
    df = df.dropna(subset=["predicted_hate_category"]).copy()

    # ====== 3. Eliminar "nan" como texto ======
    df = df[df["predicted_hate_category"].astype(str).str.lower() != "nan"].copy()

    # ====== 4. Etiqueta binaria ======
    df["label"] = (
        df["predicted_hate_category"]
        .astype(str)
        .str.lower()
        != "nan"
    ).astype(int)

    # ====== 5. Texto limpio ======
    df["clean"] = df[text_field].apply(clean_text)

    return df

# --------------------
# 2) Load NEW CSV dataset
# --------------------
INPUT_CSV = "ethos/en_dataset_with_stop_words.csv"
df_new_full, df_new_min = load_ethos(INPUT_CSV)

In [8]:
INPUT_JSONL = "supertweeteval/merged_masked_unionv2.jsonl"

df_tweethate = load_and_clean_tweethate(INPUT_JSONL, text_field="text")
df_tweethate.head()

,id,text,text_masked,predicted_hate_category,groups_from_mask,taxonomy_version,masking_model,lang,lexicon,label,clean
2,10,If yall faggots waste votes on this clownery i...,If yall [SLUR:SEXUAL_ORIENTATION_OTHER] waste ...,hate_sexuality,[SEXUAL_ORIENTATION_OTHER],v1.1-closed,gpt-4o-mini,en,1,1,If yall faggots waste votes on this clownery i...
4,1000,These niggas are goofy ass scary hoes foreal lol,These [SLUR:RACE_BLACK] are goofy ass scary [S...,hate_race,"[GENDER_WOMEN, RACE_BLACK]",v1.1-closed,gpt-4o-mini,en,1,1,These niggas are goofy ass scary hoes foreal lol
8,1004,: females are literal reptiles : like born sna...,: [SLUR:GENDER_WOMEN] are literal reptiles : l...,hate_gender,[GENDER_WOMEN],v1.1-closed,gpt-4o-mini,en,1,1,: females are literal reptiles : like born sna...
14,101,@user worst thing about conservative women: wi...,[MENTION] worst thing about conservative [TARG...,hate_gender,[GENDER_WOMEN],v1.1-closed,gpt-4o-mini,en,1,1,[MENTION] worst thing about conservative wome...
15,1010,Women really be minding their business and tra...,[GENDER_WOMEN] really be minding their busines...,hate_gender,[GENDER_MEN],v1.1-closed,gpt-4o-mini,en,1,1,Women really be minding their business and tra...

In [9]:
def show_hate_and_target_distribution(df, name, label_col="label"):
    print(f"\n===== {name} – target distribution =====")
    print(df[label_col].value_counts().rename("count"))
    print("\nProportions:")
    print(df[label_col].value_counts(normalize=True).round(3).rename("prop"))

# Compare distributions
show_hate_and_target_distribution(df_new_full, "new CSV dataset", label_col="target")
show_hate_and_target_distribution(df_tweethate, "new CSV dataset", label_col="predicted_hate_category")

===== new CSV dataset – target distribution =====
target
origin                2448
disability            1089
other                  890
gender                 638
sexual_orientation     514
religion                68
Name: count, dtype: int64

Proportions:
target
origin                0.434
disability            0.193
other                 0.158
gender                0.113
sexual_orientation    0.091
religion              0.012
Name: prop, dtype: float64

===== new CSV dataset – target distribution =====
predicted_hate_category
hate_gender        771
hate_race          542
hate_sexuality     246
hate_religion      234
hate_origin        162
hate_disability     20
hate_age             9
Name: count, dtype: int64

Proportions:
predicted_hate_category
hate_gender        0.389
hate_race          0.273
hate_sexuality     0.124
hate_religion      0.118
hate_origin        0.082
hate_disability    0.010
hate_age           0.005
Name: prop, dtype: float64

In [ ]:
# Experiment function

In [10]:
# =========================================
# Helper: intervalo de confianza 95%
# =========================================
def ci95(series):
    arr = np.array(series)
    mean = arr.mean()
    std  = arr.std(ddof=1)
    ci_low  = mean - 1.96 * std / np.sqrt(len(arr))
    ci_high = mean + 1.96 * std / np.sqrt(len(arr))
    return mean, std, ci_low, ci_high


# =========================================
# Experimento por seed (tu versión limpia)
# =========================================
def _single_seed_experiment(df_trainval, df_test, X_field, seed,
                            val_size, ngram_range, min_df, max_df, max_features):

    random.seed(seed)
    np.random.seed(seed)

    df_trainval = df_trainval[df_trainval[X_field].apply(lambda x: isinstance(x, str) and x.strip() != "")]
    df_test     = df_test[df_test[X_field].apply(lambda x: isinstance(x, str) and x.strip() != "")]

    for df in (df_trainval, df_test):
        df["phc"] = df["predicted_hate_category"].astype(str).str.strip()

    df_trainval = df_trainval[df_trainval["phc"].str.lower() != "nan"].copy()
    df_test     = df_test[df_test["phc"].str.lower() != "nan"].copy()

    if len(df_trainval) == 0 or len(df_test) == 0:
        raise RuntimeError("Train/Val o Test vacío tras filtrar 'nan'.")

    # Etiquetado
    all_labels = sorted(set(df_trainval["phc"].str.lower()) | set(df_test["phc"].str.lower()))
    label2id = {c:i for i,c in enumerate(all_labels)}
    id2label = {i:c for c,i in label2id.items()}

    for df in (df_trainval, df_test):
        df["label"] = df["phc"].str.lower().map(label2id).astype(int)
        df["clean"] = df[X_field].apply(clean_text)

    # Split
    X_train, X_val, y_train, y_val = train_test_split(
        df_trainval["clean"].values,
        df_trainval["label"].values,
        test_size=val_size,
        random_state=seed,
        stratify=df_trainval["label"].values
    )
    X_test = df_test["clean"].values
    y_test = df_test["label"].values

    # Vectorizer
    vectorizer = TfidfVectorizer(
        lowercase=True,
        ngram_range=ngram_range,
        min_df=min_df,
        max_df=max_df,
        strip_accents="unicode",
        sublinear_tf=True,
        stop_words="english",
        max_features=max_features,
    )
    Xtr = vectorizer.fit_transform(X_train)
    Xva = vectorizer.transform(X_val)
    Xte = vectorizer.transform(X_test)

    # Pesos de clase
    uniq = np.unique(y_train)
    class_weights = compute_class_weight(class_weight="balanced", classes=uniq, y=y_train)
    cw_map = {int(c): float(w) for c,w in zip(uniq, class_weights)}
    sw_train = np.vectorize(cw_map.get)(y_train)

    # Modelos
    models = {
        "logreg_ovr": LogisticRegression(
            max_iter=8000, n_jobs=-1, class_weight=cw_map, C=2.0,
            solver="liblinear", multi_class="ovr", random_state=seed),
        "linear_svm": LinearSVC(class_weight=cw_map, random_state=seed),
        "sgd_log": SGDClassifier(loss="log_loss", alpha=1e-4, max_iter=2000,
                                 tol=1e-3, random_state=seed),
        "passive_aggressive": PassiveAggressiveClassifier(C=0.5, max_iter=2000,
                                                          random_state=seed),
        "complement_nb": ComplementNB(alpha=0.5),
    }

    seed_results = []

    for name, clf in models.items():
        # Entrenamiento
        try:
            clf.fit(Xtr, y_train, sample_weight=sw_train)
        except TypeError:
            clf.fit(Xtr, y_train)

        # Evaluación
        val_metrics  = eval_split(clf, Xva, y_val, "VAL")
        test_metrics = eval_split(clf, Xte, y_test, "TEST (fijo)")

        seed_results.append({
            "model": name,
            "seed": seed,
            "val_f1_macro":  val_metrics["f1_macro"],
            "val_accuracy":  val_metrics["accuracy"],
            "test_f1_macro": test_metrics["f1_macro"],
            "test_accuracy": test_metrics["accuracy"],
        })

    return pd.DataFrame(seed_results)



# =========================================
# Experimento sobre múltiples seeds (main)
# =========================================
def experiment_from_df_multi_seed(
        df_trainval, df_test, X_field,
        seeds=[1,2,3,4,5],
        val_size=0.10, ngram_range=(1,2), 
        min_df=3, max_df=0.90, max_features=None):

    all_runs = []

    print("=====================================")
    print(" Ejecutando Seeds:", seeds)
    print("=====================================")

    for sd in seeds:
        print(f"\n##### SEED = {sd} #####\n")
        df_seed = _single_seed_experiment(
            df_trainval.copy(),
            df_test.copy(),
            X_field,
            seed=sd,
            val_size=val_size,
            ngram_range=ngram_range,
            min_df=min_df,
            max_df=max_df,
            max_features=max_features
        )
        all_runs.append(df_seed)

    df_all = pd.concat(all_runs, ignore_index=True)

    # ============================
    #  Agregado por modelo
    # ============================
    rows = []
    for model, sub in df_all.groupby("model"):
        mean_val, std_val, lo_val, hi_val = ci95(sub["val_f1_macro"])
        mean_te, std_te, lo_te, hi_te = ci95(sub["test_f1_macro"])

        rows.append({
            "model": model,
            "val_f1_macro_mean": mean_val,
            "val_f1_macro_std": std_val,
            "val_f1_macro_CI_low": lo_val,
            "val_f1_macro_CI_high": hi_val,

            "test_f1_macro_mean": mean_te,
            "test_f1_macro_std": std_te,
            "test_f1_macro_CI_low": lo_te,
            "test_f1_macro_CI_high": hi_te,
        })

    df_summary = pd.DataFrame(rows).sort_values(by="val_f1_macro_mean", ascending=False)

    print("\n=====================================")
    print("Resumen Multi-Seed (95% CI)")
    print("=====================================")
    print(df_summary.to_string(index=False))

    return df_all, df_summary

In [11]:
def remove_values_from_column(df, column, values_to_remove):
    """
    Devuelve un nuevo DataFrame donde se eliminan todas las filas
    cuya columna `column` contiene uno de los valores en `values_to_remove`.

    Parámetros:
        df : DataFrame de entrada
        column : str, nombre de la columna a filtrar
        values_to_remove : lista, set o array con valores a eliminar

    Retorna:
        df_filtrado : DataFrame sin las filas indeseadas
    """
    # Convertimos a set para eficiencia
    remove_set = set(values_to_remove)

    # Filtrado
    df_filtered = df[~df[column].isin(remove_set)].copy()

    return df_filtered

In [12]:
def collapse_race_into_origin(df, col="predicted_hate_category"):
    """
    Reemplaza hate_race -> hate_origin en la columna dada.
    Devuelve un nuevo DataFrame (no in-place).
    """
    df = df.copy()
    df[col] = df[col].replace({"hate_race": "hate_origin"})
    return df

## Create Test set

## Initial test

In [12]:
#INPUT_JSONL = "supertweeteval/merged_masked_unionv2.jsonl"
TEST_JSONL = "supertweeteval/test_split_only_originals.jsonl"

INPUT_JSONL = "supertweeteval/broken_phone/balanced_with_broken_phone_supertweetevalv3.jsonl"
TEST_JSONL = "supertweeteval/test_split_only_originals.jsonl"

my_train_df = load_and_clean_tweethate(INPUT_JSONL, text_field="text")
my_test_df = load_and_clean_tweethate(TEST_JSONL, text_field="text")

my_train_df = remove_values_from_column(my_train_df, "predicted_hate_category", ["hate_age"])
my_test_df = remove_values_from_column(my_test_df, "predicted_hate_category", ["hate_age"])

my_train_df = collapse_race_into_origin(my_train_df, col="predicted_hate_category")
my_test_df      = collapse_race_into_origin(my_test_df,      col="predicted_hate_category")

In [ ]:
df_all_runs, df_summary = experiment_from_df_multi_seed(
    df_trainval=my_train_df,
    df_test=my_test_df,
    X_field="text",
    seeds=[7,11,13,17,19]
)

=====================================
 Ejecutando Seeds: [7, 11, 13, 17, 19]
=====================================

##### SEED = 7 #####


=== VAL ===
              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000        71
           1     0.8987    0.9467    0.9221        75
           2     0.9929    0.9459    0.9689       148
           3     0.9737    1.0000    0.9867        74
           4     0.9737    0.9867    0.9801        75

    accuracy                         0.9707       443
   macro avg     0.9678    0.9759    0.9715       443
weighted avg     0.9716    0.9707    0.9708       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  0  71   1   1   2]
 [  0   7 140   1   0]
 [  0   0   0  74   0]
 [  0   1   0   0  74]]
F1-macro: 0.9715
Accuracy: 0.9707

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000         1
           1     0.8750    0.8537    0.8642        41
           2     0.8529    0.7838    0.8169        37
           3     0.5882    0.8333    0.6897        12
           4     0.9167    0.8462    0.8800        13

    accuracy                         0.8269       104
   macro avg     0.8466    0.8634    0.8502       104
weighted avg     0.8405    0.8269    0.8305       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 35  3  2  1]
 [ 0  3 29  5  0]
 [ 0  0  2 10  0]
 [ 0  2  0  0 11]]
F1-macro: 0.8502
Accuracy: 0.8269

=== VAL ===
              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000        71
           1     0.9600    0.9600    0.9600        75
           2     0.9864    0.9797    0.9831       148
           3     0.9867    1.0000    0.9933        74
           4     1.0000    1.0000    1.0000        75

    accuracy                         0.9865       443
   macro avg     0.9866    0.9879    0.9873       443
weighted avg     0.9865    0.9865    0.9864       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  0  72   2   1   0]
 [  0   3 145   0   0]
 [  0   0   0  74   0]
 [  0   0   0   0  75]]
F1-macro: 0.9873
Accuracy: 0.9865

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000         1
           1     0.8718    0.8293    0.8500        41
           2     0.8108    0.8108    0.8108        37
           3     0.5625    0.7500    0.6429        12
           4     0.9091    0.7692    0.8333        13

    accuracy                         0.8077       104
   macro avg     0.8308    0.8319    0.8274       104
weighted avg     0.8203    0.8077    0.8115       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 34  4  2  1]
 [ 0  2 30  5  0]
 [ 0  1  2  9  0]
 [ 0  2  1  0 10]]
F1-macro: 0.8274
Accuracy: 0.8077

=== VAL ===
              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000        71
           1     0.9467    0.9467    0.9467        75
           2     0.9864    0.9797    0.9831       148
           3     0.9867    1.0000    0.9933        74
           4     0.9867    0.9867    0.9867        75

    accuracy                         0.9819       443
   macro avg     0.9813    0.9826    0.9819       443
weighted avg     0.9819    0.9819    0.9819       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  0  71   2   1   1]
 [  0   3 145   0   0]
 [  0   0   0  74   0]
 [  0   1   0   0  74]]
F1-macro: 0.9819
Accuracy: 0.9819

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000         1
           1     0.9189    0.8293    0.8718        41
           2     0.8250    0.8919    0.8571        37
           3     0.6667    0.8333    0.7407        12
           4     0.9091    0.7692    0.8333        13

    accuracy                         0.8462       104
   macro avg     0.8639    0.8647    0.8606       104
weighted avg     0.8560    0.8462    0.8479       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 34  4  2  1]
 [ 0  1 33  3  0]
 [ 0  0  2 10  0]
 [ 0  2  1  0 10]]
F1-macro: 0.8606
Accuracy: 0.8462

=== VAL ===
              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000        71
           1     0.9730    0.9600    0.9664        75
           2     0.9865    0.9865    0.9865       148
           3     0.9867    1.0000    0.9933        74
           4     1.0000    1.0000    1.0000        75

    accuracy                         0.9887       443
   macro avg     0.9892    0.9893    0.9892       443
weighted avg     0.9887    0.9887    0.9887       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  0  72   2   1   0]
 [  0   2 146   0   0]
 [  0   0   0  74   0]
 [  0   0   0   0  75]]
F1-macro: 0.9892
Accuracy: 0.9887

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.0000    0.0000    0.0000         1
           1     0.8333    0.8537    0.8434        41
           2     0.8205    0.8649    0.8421        37
           3     0.5833    0.5833    0.5833        12
           4     0.9091    0.7692    0.8333        13

    accuracy                         0.8077       104
   macro avg     0.6293    0.6142    0.6204       104
weighted avg     0.8014    0.8077    0.8036       104

Confusion matrix:
 [[ 0  0  0  1  0]
 [ 0 35  4  1  1]
 [ 0  2 32  3  0]
 [ 0  3  2  7  0]
 [ 0  2  1  0 10]]
F1-macro: 0.6204
Accuracy: 0.8077

=== VAL ===
              precision    recall  f1-score   support

           0     0.9467    1.0000    0.9726        71
           1     0.8049    0.8800    0.8408        75
           2     0.9774    0.8784    0.9253       148
           3     0.9487    1.0000    0.9737        74
           4     0.9467    0.9467    0.9467        75

    accuracy                         0.9300       443
   macro avg     0.9249    0.9410    0.9318       443
weighted avg     0.9333    0.9300    0.9303       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  0  66   3   3   3]
 [  1  15 130   1   1]
 [  0   0   0  74   0]
 [  3   1   0   0  71]]
F1-macro: 0.9318
Accuracy: 0.9300

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.1667    1.0000    0.2857         1
           1     0.8049    0.8049    0.8049        41
           2     0.8276    0.6486    0.7273        37
           3     0.6667    0.6667    0.6667        12
           4     0.6875    0.8462    0.7586        13

    accuracy                         0.7404       104
   macro avg     0.6307    0.7933    0.6486       104
weighted avg     0.7762    0.7404    0.7505       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 33  5  1  2]
 [ 3  4 24  3  3]
 [ 2  2  0  8  0]
 [ 0  2  0  0 11]]
F1-macro: 0.6486
Accuracy: 0.7404

##### SEED = 11 #####

/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1281: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1296: FutureWarning: Using the 'liblinear' solver for multiclass classification is deprecated. An error will be raised in 1.8. Either use another solver which supports the multinomial loss or wrap the estimator in a OneVsRestClassifier to keep applying a one-versus-rest scheme.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1305: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 32.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1281: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1296: FutureWarning: Using the 'liblinear' solver for multiclass classification is deprecated. An error will be raised in 1.8. Either use another solver which supports the multinomial loss or wrap the estimator in a OneVsRestClassifier to keep applying a one-versus-rest scheme.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1305: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 32.
  warnings.warn(

=== VAL ===
              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000        71
           1     0.8256    0.9467    0.8820        75
           2     0.9776    0.8851    0.9291       148
           3     0.9487    1.0000    0.9737        74
           4     1.0000    0.9867    0.9933        75

    accuracy                         0.9503       443
   macro avg     0.9504    0.9637    0.9556       443
weighted avg     0.9544    0.9503    0.9508       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  0  71   3   1   0]
 [  0  14 131   3   0]
 [  0   0   0  74   0]
 [  0   1   0   0  74]]
F1-macro: 0.9556
Accuracy: 0.9503

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000         1
           1     0.8537    0.8537    0.8537        41
           2     0.8529    0.7838    0.8169        37
           3     0.5882    0.8333    0.6897        12
           4     1.0000    0.8462    0.9167        13

    accuracy                         0.8269       104
   macro avg     0.8590    0.8634    0.8554       104
weighted avg     0.8425    0.8269    0.8309       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 35  4  2  0]
 [ 0  3 29  5  0]
 [ 0  1  1 10  0]
 [ 0  2  0  0 11]]
F1-macro: 0.8554
Accuracy: 0.8269

=== VAL ===
              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000        71
           1     0.9589    0.9333    0.9459        75
           2     0.9796    0.9730    0.9763       148
           3     0.9737    1.0000    0.9867        74
           4     0.9868    1.0000    0.9934        75

    accuracy                         0.9797       443
   macro avg     0.9798    0.9813    0.9805       443
weighted avg     0.9796    0.9797    0.9796       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  0  70   3   1   1]
 [  0   3 144   1   0]
 [  0   0   0  74   0]
 [  0   0   0   0  75]]
F1-macro: 0.9805
Accuracy: 0.9797

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000         1
           1     0.8571    0.8780    0.8675        41
           2     0.8824    0.8108    0.8451        37
           3     0.5625    0.7500    0.6429        12
           4     1.0000    0.8462    0.9167        13

    accuracy                         0.8365       104
   macro avg     0.8604    0.8570    0.8544       104
weighted avg     0.8513    0.8365    0.8410       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 36  3  2  0]
 [ 0  2 30  5  0]
 [ 0  2  1  9  0]
 [ 0  2  0  0 11]]
F1-macro: 0.8544
Accuracy: 0.8365

=== VAL ===
              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000        71
           1     0.8974    0.9333    0.9150        75
           2     0.9720    0.9392    0.9553       148
           3     0.9610    1.0000    0.9801        74
           4     1.0000    0.9867    0.9933        75

    accuracy                         0.9661       443
   macro avg     0.9661    0.9718    0.9688       443
weighted avg     0.9668    0.9661    0.9662       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  0  70   4   1   0]
 [  0   7 139   2   0]
 [  0   0   0  74   0]
 [  0   1   0   0  74]]
F1-macro: 0.9688
Accuracy: 0.9661

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000         1
           1     0.8974    0.8537    0.8750        41
           2     0.8158    0.8378    0.8267        37
           3     0.6250    0.8333    0.7143        12
           4     1.0000    0.7692    0.8696        13

    accuracy                         0.8365       104
   macro avg     0.8676    0.8588    0.8571       104
weighted avg     0.8508    0.8365    0.8398       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 35  4  2  0]
 [ 0  2 31  4  0]
 [ 0  0  2 10  0]
 [ 0  2  1  0 10]]
F1-macro: 0.8571
Accuracy: 0.8365

=== VAL ===
              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000        71
           1     0.9861    0.9467    0.9660        75
           2     0.9866    0.9932    0.9899       148
           3     0.9867    1.0000    0.9933        74
           4     0.9868    1.0000    0.9934        75

    accuracy                         0.9887       443
   macro avg     0.9892    0.9880    0.9885       443
weighted avg     0.9887    0.9887    0.9886       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  0  71   2   1   1]
 [  0   1 147   0   0]
 [  0   0   0  74   0]
 [  0   0   0   0  75]]
F1-macro: 0.9885
Accuracy: 0.9887

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000         1
           1     0.8372    0.8780    0.8571        41
           2     0.7949    0.8378    0.8158        37
           3     0.5455    0.5000    0.5217        12
           4     1.0000    0.7692    0.8696        13

    accuracy                         0.8077       104
   macro avg     0.8355    0.7970    0.8128       104
weighted avg     0.8104    0.8077    0.8067       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 36  4  1  0]
 [ 0  2 31  4  0]
 [ 0  3  3  6  0]
 [ 0  2  1  0 10]]
F1-macro: 0.8128
Accuracy: 0.8077

=== VAL ===
              precision    recall  f1-score   support

           0     0.9467    1.0000    0.9726        71
           1     0.7229    0.8000    0.7595        75
           2     0.9606    0.8243    0.8873       148
           3     0.9024    1.0000    0.9487        74
           4     0.9605    0.9733    0.9669        75

    accuracy                         0.9029       443
   macro avg     0.8986    0.9195    0.9070       443
weighted avg     0.9084    0.9029    0.9031       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  4  60   5   3   3]
 [  0  21 122   5   0]
 [  0   0   0  74   0]
 [  0   2   0   0  73]]
F1-macro: 0.9070
Accuracy: 0.9029

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.1429    1.0000    0.2500         1
           1     0.7955    0.8537    0.8235        41
           2     0.8889    0.6486    0.7500        37
           3     0.6667    0.6667    0.6667        12
           4     0.7143    0.7692    0.7407        13

    accuracy                         0.7500       104
   macro avg     0.6416    0.7876    0.6462       104
weighted avg     0.7974    0.7500    0.7634       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 1 35  3  1  1]
 [ 3  5 24  3  2]
 [ 2  1  0  8  1]
 [ 0  3  0  0 10]]
F1-macro: 0.6462
Accuracy: 0.7500

##### SEED = 13 #####


=== VAL ===
              precision    recall  f1-score   support

           0     0.9861    1.0000    0.9930        71
           1     0.9091    0.9333    0.9211        75
           2     0.9859    0.9459    0.9655       148
           3     0.9367    1.0000    0.9673        74
           4     1.0000    0.9733    0.9865        75

    accuracy                         0.9661       443
   macro avg     0.9636    0.9705    0.9667       443
weighted avg     0.9671    0.9661    0.9662       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  1  70   2   2   0]
 [  0   5 140   3   0]
 [  0   0   0  74   0]
 [  0   2   0   0  73]]
F1-macro: 0.9667
Accuracy: 0.9661

=== TEST (fijo) ===

/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1281: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1296: FutureWarning: Using the 'liblinear' solver for multiclass classification is deprecated. An error will be raised in 1.8. Either use another solver which supports the multinomial loss or wrap the estimator in a OneVsRestClassifier to keep applying a one-versus-rest scheme.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1305: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 32.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1281: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1296: FutureWarning: Using the 'liblinear' solver for multiclass classification is deprecated. An error will be raised in 1.8. Either use another solver which supports the multinomial loss or wrap the estimator in a OneVsRestClassifier to keep applying a one-versus-rest scheme.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1305: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 32.
  warnings.warn(

              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000         1
           1     0.8333    0.8537    0.8434        41
           2     0.8235    0.7568    0.7887        37
           3     0.5625    0.7500    0.6429        12
           4     1.0000    0.8462    0.9167        13

    accuracy                         0.8077       104
   macro avg     0.8439    0.8413    0.8383       104
weighted avg     0.8210    0.8077    0.8115       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 35  4  2  0]
 [ 0  4 28  5  0]
 [ 0  1  2  9  0]
 [ 0  2  0  0 11]]
F1-macro: 0.8383
Accuracy: 0.8077

=== VAL ===
              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000        71
           1     0.9600    0.9600    0.9600        75
           2     0.9863    0.9730    0.9796       148
           3     0.9737    1.0000    0.9867        74
           4     1.0000    1.0000    1.0000        75

    accuracy                         0.9842       443
   macro avg     0.9840    0.9866    0.9853       443
weighted avg     0.9843    0.9842    0.9842       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  0  72   2   1   0]
 [  0   3 144   1   0]
 [  0   0   0  74   0]
 [  0   0   0   0  75]]
F1-macro: 0.9853
Accuracy: 0.9842

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000         1
           1     0.8750    0.8537    0.8642        41
           2     0.8333    0.8108    0.8219        37
           3     0.5625    0.7500    0.6429        12
           4     1.0000    0.8462    0.9167        13

    accuracy                         0.8269       104
   macro avg     0.8542    0.8521    0.8491       104
weighted avg     0.8409    0.8269    0.8315       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 35  4  2  0]
 [ 0  2 30  5  0]
 [ 0  1  2  9  0]
 [ 0  2  0  0 11]]
F1-macro: 0.8491
Accuracy: 0.8269

=== VAL ===
              precision    recall  f1-score   support

           0     0.9861    1.0000    0.9930        71
           1     0.9342    0.9467    0.9404        75
           2     0.9863    0.9730    0.9796       148
           3     0.9737    1.0000    0.9867        74
           4     1.0000    0.9733    0.9865        75

    accuracy                         0.9774       443
   macro avg     0.9761    0.9786    0.9772       443
weighted avg     0.9777    0.9774    0.9775       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  1  71   2   1   0]
 [  0   3 144   1   0]
 [  0   0   0  74   0]
 [  0   2   0   0  73]]
F1-macro: 0.9772
Accuracy: 0.9774

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000         1
           1     0.8750    0.8537    0.8642        41
           2     0.8158    0.8378    0.8267        37
           3     0.6000    0.7500    0.6667        12
           4     1.0000    0.7692    0.8696        13

    accuracy                         0.8269       104
   macro avg     0.8582    0.8421    0.8454       104
weighted avg     0.8390    0.8269    0.8300       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 35  4  2  0]
 [ 0  2 31  4  0]
 [ 0  1  2  9  0]
 [ 0  2  1  0 10]]
F1-macro: 0.8454
Accuracy: 0.8269

=== VAL ===
              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000        71
           1     0.9863    0.9600    0.9730        75
           2     0.9799    0.9865    0.9832       148
           3     0.9867    1.0000    0.9933        74
           4     1.0000    1.0000    1.0000        75

    accuracy                         0.9887       443
   macro avg     0.9906    0.9893    0.9899       443
weighted avg     0.9887    0.9887    0.9887       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  0  72   3   0   0]
 [  0   1 146   1   0]
 [  0   0   0  74   0]
 [  0   0   0   0  75]]
F1-macro: 0.9899
Accuracy: 0.9887

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000         1
           1     0.8810    0.9024    0.8916        41
           2     0.8250    0.8919    0.8571        37
           3     0.7273    0.6667    0.6957        12
           4     1.0000    0.7692    0.8696        13

    accuracy                         0.8558       104
   macro avg     0.8866    0.8460    0.8628       104
weighted avg     0.8593    0.8558    0.8550       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 37  3  1  0]
 [ 0  2 33  2  0]
 [ 0  1  3  8  0]
 [ 0  2  1  0 10]]
F1-macro: 0.8628
Accuracy: 0.8558

=== VAL ===
              precision    recall  f1-score   support

           0     0.9595    1.0000    0.9793        71
           1     0.7791    0.8933    0.8323        75
           2     0.9699    0.8716    0.9181       148
           3     0.9737    1.0000    0.9867        74
           4     0.9730    0.9600    0.9664        75

    accuracy                         0.9323       443
   macro avg     0.9310    0.9450    0.9366       443
weighted avg     0.9371    0.9323    0.9330       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  2  67   4   1   1]
 [  1  16 129   1   1]
 [  0   0   0  74   0]
 [  0   3   0   0  72]]
F1-macro: 0.9366
Accuracy: 0.9323

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.1667    1.0000    0.2857         1
           1     0.8043    0.9024    0.8506        41
           2     0.8846    0.6216    0.7302        37
           3     0.6154    0.6667    0.6400        12
           4     0.7692    0.7692    0.7692        13

    accuracy                         0.7596       104
   macro avg     0.6480    0.7920    0.6551       104
weighted avg     0.8006    0.7596    0.7678       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 37  3  1  0]
 [ 3  4 23  4  3]
 [ 2  2  0  8  0]
 [ 0  3  0  0 10]]
F1-macro: 0.6551
Accuracy: 0.7596

##### SEED = 17 #####


=== VAL ===
              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000        71
           1     0.9189    0.9067    0.9128        75
           2     0.9790    0.9459    0.9622       148
           3     0.9487    1.0000    0.9737        74
           4     0.9740    1.0000    0.9868        75

    accuracy                         0.9661       443
   macro avg     0.9641    0.9705    0.9671       443
weighted avg     0.9663    0.9661    0.9660       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  0  68   3   2   2]
 [  0   6 140   2   0]
 [  0   0   0  74   0]
 [  0   0   0   0  75]]
F1-macro: 0.9671
Accuracy: 0.9661

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000         1
           1     0.8333    0.8537    0.8434        41
           2     0.8438    0.7297    0.7826        37
           3     0.5294    0.7500    0.6207        12
           4     0.9167    0.8462    0.8800        13

    accuracy                         0.7981       104
   macro avg     0.8246    0.8359    0.8253       104
weighted avg     0.8140    0.7981    0.8021       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 35  3  2  1]
 [ 0  4 27  6  0]
 [ 0  1  2  9  0]
 [ 0  2  0  0 11]]
F1-macro: 0.8253
Accuracy: 0.7981

=== VAL ===
              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000        71
           1     0.9583    0.9200    0.9388        75
           2     0.9797    0.9797    0.9797       148
           3     0.9737    1.0000    0.9867        74
           4     0.9868    1.0000    0.9934        75

    accuracy                         0.9797       443
   macro avg     0.9797    0.9799    0.9797       443
weighted avg     0.9796    0.9797    0.9795       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  0  69   3   2   1]
 [  0   3 145   0   0]
 [  0   0   0  74   0]
 [  0   0   0   0  75]]
F1-macro: 0.9797
Accuracy: 0.9797

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000         1
           1     0.8293    0.8293    0.8293        41
           2     0.8611    0.8378    0.8493        37
           3     0.6000    0.7500    0.6667        12
           4     0.9091    0.7692    0.8333        13

    accuracy                         0.8173       104
   macro avg     0.8399    0.8373    0.8357       104
weighted avg     0.8258    0.8173    0.8198       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 34  4  2  1]
 [ 0  2 31  4  0]
 [ 0  2  1  9  0]
 [ 0  3  0  0 10]]
F1-macro: 0.8357
Accuracy: 0.8173

=== VAL ===
              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000        71
           1     0.9571    0.8933    0.9241        75
           2     0.9732    0.9797    0.9764       148
           3     0.9737    1.0000    0.9867        74
           4     0.9740    1.0000    0.9868        75

    accuracy                         0.9752       443
   macro avg     0.9756    0.9746    0.9748       443
weighted avg     0.9750    0.9752    0.9748       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  0  67   4   2   2]
 [  0   3 145   0   0]
 [  0   0   0  74   0]
 [  0   0   0   0  75]]
F1-macro: 0.9748
Accuracy: 0.9752

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000         1
           1     0.8718    0.8293    0.8500        41
           2     0.8108    0.8108    0.8108        37
           3     0.5625    0.7500    0.6429        12
           4     0.9091    0.7692    0.8333        13

    accuracy                         0.8077       104
   macro avg     0.8308    0.8319    0.8274       104
weighted avg     0.8203    0.8077    0.8115       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 34  4  2  1]
 [ 0  2 30  5  0]
 [ 0  1  2  9  0]
 [ 0  2  1  0 10]]
F1-macro: 0.8274
Accuracy: 0.8077

=== VAL ===
              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000        71
           1     0.9722    0.9333    0.9524        75
           2     0.9733    0.9865    0.9799       148
           3     0.9867    1.0000    0.9933        74
           4     1.0000    1.0000    1.0000        75

    accuracy                         0.9842       443
   macro avg     0.9864    0.9840    0.9851       443
weighted avg     0.9842    0.9842    0.9841       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  0  70   4   1   0]
 [  0   2 146   0   0]
 [  0   0   0  74   0]
 [  0   0   0   0  75]]
F1-macro: 0.9851
Accuracy: 0.9842

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.0000    0.0000    0.0000         1
           1     0.8409    0.9024    0.8706        41
           2     0.8378    0.8378    0.8378        37
           3     0.5385    0.5833    0.5600        12
           4     1.0000    0.7692    0.8696        13

    accuracy                         0.8173       104
   macro avg     0.6434    0.6186    0.6276       104
weighted avg     0.8167    0.8173    0.8146       104

Confusion matrix:
 [[ 0  0  0  1  0]
 [ 0 37  3  1  0]
 [ 0  2 31  4  0]
 [ 0  3  2  7  0]
 [ 0  2  1  0 10]]
F1-macro: 0.6276
Accuracy: 0.8173

=== VAL ===
              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000        71
           1     0.8000    0.8533    0.8258        75
           2     0.9706    0.8919    0.9296       148
           3     0.9487    1.0000    0.9737        74
           4     0.9359    0.9733    0.9542        75

    accuracy                         0.9345       443
   macro avg     0.9310    0.9437    0.9367       443
weighted avg     0.9369    0.9345    0.9348       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  0  64   4   3   4]
 [  0  14 132   1   1]
 [  0   0   0  74   0]
 [  0   2   0   0  73]]
F1-macro: 0.9367
Accuracy: 0.9345

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.1429    1.0000    0.2500         1
           1     0.7778    0.8537    0.8140        41
           2     0.8800    0.5946    0.7097        37
           3     0.5714    0.6667    0.6154        12
           4     0.7692    0.7692    0.7692        13

    accuracy                         0.7308       104
   macro avg     0.6283    0.7768    0.6316       104
weighted avg     0.7832    0.7308    0.7429       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 1 35  3  1  1]
 [ 3  5 22  5  2]
 [ 2  2  0  8  0]
 [ 0  3  0  0 10]]
F1-macro: 0.6316
Accuracy: 0.7308

##### SEED = 19 #####


=== VAL ===
              precision    recall  f1-score   support

           0     0.9861    1.0000    0.9930        71
           1     0.9571    0.8933    0.9241        75
           2     0.9650    0.9324    0.9485       148
           3     0.9250    1.0000    0.9610        74
           4     0.9615    1.0000    0.9804        75

    accuracy                         0.9594       443
   macro avg     0.9590    0.9652    0.9614       443
weighted avg     0.9598    0.9594    0.9590       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  1  67   5   0   2]
 [  0   3 138   6   1]
 [  0   0   0  74   0]
 [  0   0   0   0  75]]
F1-macro: 0.9614
Accuracy: 0.9594

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000         1
           1     0.8500    0.8293    0.8395        41
           2     0.8286    0.7838    0.8056        37
           3     0.5625    0.7500    0.6429        12
           4     0.9167    0.8462    0.8800        13

    accuracy                         0.8077       104
   macro avg     0.8315    0.8418    0.8336       104
weighted avg     0.8190    0.8077    0.8113       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 34  4  2  1]
 [ 0  3 29  5  0]
 [ 0  1  2  9  0]
 [ 0  2  0  0 11]]
F1-macro: 0.8336
Accuracy: 0.8077

=== VAL ===
              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000        71
           1     0.9710    0.8933    0.9306        75
           2     0.9605    0.9865    0.9733       148
           3     1.0000    1.0000    1.0000        74
           4     0.9740    1.0000    0.9868        75

    accuracy                         0.9774       443
   macro avg     0.9811    0.9760    0.9781       443
weighted avg     0.9775    0.9774    0.9771       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  0  67   6   0   2]
 [  0   2 146   0   0]
 [  0   0   0  74   0]
 [  0   0   0   0  75]]
F1-macro: 0.9781
Accuracy: 0.9774

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000         1
           1     0.8500    0.8293    0.8395        41
           2     0.8333    0.8108    0.8219        37
           3     0.5625    0.7500    0.6429        12
           4     0.9091    0.7692    0.8333        13

    accuracy                         0.8077       104
   macro avg     0.8310    0.8319    0.8275       104
weighted avg     0.8197    0.8077    0.8113       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 34  4  2  1]
 [ 0  2 30  5  0]
 [ 0  1  2  9  0]
 [ 0  3  0  0 10]]
F1-macro: 0.8275
Accuracy: 0.8077

/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1281: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1296: FutureWarning: Using the 'liblinear' solver for multiclass classification is deprecated. An error will be raised in 1.8. Either use another solver which supports the multinomial loss or wrap the estimator in a OneVsRestClassifier to keep applying a one-versus-rest scheme.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1305: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 32.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

=== VAL ===
              precision    recall  f1-score   support

           0     0.9861    1.0000    0.9930        71
           1     0.9706    0.8800    0.9231        75
           2     0.9603    0.9797    0.9699       148
           3     1.0000    1.0000    1.0000        74
           4     0.9615    1.0000    0.9804        75

    accuracy                         0.9729       443
   macro avg     0.9757    0.9719    0.9733       443
weighted avg     0.9730    0.9729    0.9725       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  1  66   6   0   2]
 [  0   2 145   0   1]
 [  0   0   0  74   0]
 [  0   0   0   0  75]]
F1-macro: 0.9733
Accuracy: 0.9729

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000         1
           1     0.8500    0.8293    0.8395        41
           2     0.8108    0.8108    0.8108        37
           3     0.6000    0.7500    0.6667        12
           4     0.9091    0.7692    0.8333        13

    accuracy                         0.8077       104
   macro avg     0.8340    0.8319    0.8301       104
weighted avg     0.8160    0.8077    0.8101       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 34  4  2  1]
 [ 0  3 30  4  0]
 [ 0  1  2  9  0]
 [ 0  2  1  0 10]]
F1-macro: 0.8301
Accuracy: 0.8077

=== VAL ===
              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000        71
           1     0.9851    0.8800    0.9296        75
           2     0.9545    0.9932    0.9735       148
           3     1.0000    1.0000    1.0000        74
           4     0.9740    1.0000    0.9868        75

    accuracy                         0.9774       443
   macro avg     0.9827    0.9746    0.9780       443
weighted avg     0.9779    0.9774    0.9770       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  0  66   7   0   2]
 [  0   1 147   0   0]
 [  0   0   0  74   0]
 [  0   0   0   0  75]]
F1-macro: 0.9780
Accuracy: 0.9774

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.0000    0.0000    0.0000         1
           1     0.8571    0.8780    0.8675        41
           2     0.8250    0.8919    0.8571        37
           3     0.6364    0.5833    0.6087        12
           4     0.9091    0.7692    0.8333        13

    accuracy                         0.8269       104
   macro avg     0.6455    0.6245    0.6333       104
weighted avg     0.8185    0.8269    0.8213       104

Confusion matrix:
 [[ 0  0  0  1  0]
 [ 0 36  3  1  1]
 [ 0  2 33  2  0]
 [ 0  1  4  7  0]
 [ 0  3  0  0 10]]
F1-macro: 0.6333
Accuracy: 0.8269

=== VAL ===
              precision    recall  f1-score   support

           0     0.9726    1.0000    0.9861        71
           1     0.8767    0.8533    0.8649        75
           2     0.9784    0.9189    0.9477       148
           3     0.9487    1.0000    0.9737        74
           4     0.9250    0.9867    0.9548        75

    accuracy                         0.9458       443
   macro avg     0.9403    0.9518    0.9454       443
weighted avg     0.9463    0.9458    0.9454       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  2  64   3   0   6]
 [  0   8 136   4   0]
 [  0   0   0  74   0]
 [  0   1   0   0  74]]
F1-macro: 0.9454
Accuracy: 0.9458

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.1667    1.0000    0.2857         1
           1     0.8095    0.8293    0.8193        41
           2     0.8571    0.6486    0.7385        37
           3     0.6154    0.6667    0.6400        12
           4     0.7333    0.8462    0.7857        13

    accuracy                         0.7500       104
   macro avg     0.6364    0.7981    0.6538       104
weighted avg     0.7884    0.7500    0.7605       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 34  4  1  2]
 [ 3  4 24  4  2]
 [ 2  2  0  8  0]
 [ 0  2  0  0 11]]
F1-macro: 0.6538
Accuracy: 0.7500

=====================================
Resumen Multi-Seed (95% CI)
=====================================
             model  val_f1_macro_mean  val_f1_macro_std  val_f1_macro_CI_low  val_f1_macro_CI_high  test_f1_macro_mean  test_f1_macro_std  test_f1_macro_CI_low  test_f1_macro_CI_high
passive_aggressive           0.986146          0.004920             0.981834              0.990459            0.711398           0.116836              0.608986               0.813809
        linear_svm           0.982166          0.003895             0.978752              0.985580            0.838836           0.012420              0.827949               0.849723
           sgd_log           0.975202          0.004870             0.970934              0.979471            0.844118           0.015158              0.830831               0.857404
        logreg_ovr           0.964467          0.006119             0.959103              0.969830            0.840554           0.012217              0.829846               0.851263
     complement_nb           0.931495          0.014556             0.918736              0.944254            0.647087           0.009378              0.638867               0.655308

In [72]:
df_summary

,model,val_f1_macro_mean,val_f1_macro_std,val_f1_macro_CI_low,val_f1_macro_CI_high,test_f1_macro_mean,test_f1_macro_std,test_f1_macro_CI_low,test_f1_macro_CI_high
4,sgd_log,0.704571,0.045734,0.664483,0.744658,0.757229,0.013061,0.745780,0.768677
1,linear_svm,0.691243,0.049450,0.647898,0.734588,0.747702,0.012699,0.736571,0.758834
3,passive_aggressive,0.689503,0.058110,0.638567,0.740439,0.788131,0.031646,0.760392,0.815870
2,logreg_ovr,0.621616,0.023852,0.600708,0.642524,0.676250,0.021434,0.657463,0.695038
0,complement_nb,0.584789,0.029115,0.559268,0.610309,0.637153,0.009632,0.628710,0.645596

In [116]:
df_summary

,model,val_f1_macro_mean,val_f1_macro_std,val_f1_macro_CI_low,val_f1_macro_CI_high,test_f1_macro_mean,test_f1_macro_std,test_f1_macro_CI_low,test_f1_macro_CI_high
3,passive_aggressive,0.986146,0.004920,0.981834,0.990459,0.711398,0.116836,0.608986,0.813809
1,linear_svm,0.982166,0.003895,0.978752,0.985580,0.838836,0.012420,0.827949,0.849723
4,sgd_log,0.975202,0.004870,0.970934,0.979471,0.844118,0.015158,0.830831,0.857404
2,logreg_ovr,0.964467,0.006119,0.959103,0.969830,0.840554,0.012217,0.829846,0.851263
0,complement_nb,0.931495,0.014556,0.918736,0.944254,0.647087,0.009378,0.638867,0.655308

In [13]:
#INPUT_JSONL = "supertweeteval/merged_masked_unionv2.jsonl"
TEST_JSONL = "supertweeteval/test_split_only_originals.jsonl"
INPUT_JSONL = "supertweeteval/broken_phone/balanced_with_broken_phone_supertweetevalv3.jsonl"


my_train_df = load_and_clean_tweethate(INPUT_JSONL, text_field="text_masked")
my_test_df = load_and_clean_tweethate(TEST_JSONL, text_field="text_masked")

my_train_df = remove_values_from_column(my_train_df, "predicted_hate_category", ["hate_age"])
my_test_df = remove_values_from_column(my_test_df, "predicted_hate_category", ["hate_age"])

my_train_df = collapse_race_into_origin(my_train_df, col="predicted_hate_category")
my_test_df      = collapse_race_into_origin(my_test_df,      col="predicted_hate_category")

In [121]:
df_all_runs, df_summary = experiment_from_df_multi_seed(
    df_trainval=my_train_df,
    df_test=my_test_df,
    X_field="text_masked",
    seeds=[7,11,13,17,19]
)

=====================================
 Ejecutando Seeds: [7, 11, 13, 17, 19]
=====================================

##### SEED = 7 #####


=== VAL ===
              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000        71
           1     0.8588    0.9733    0.9125        75
           2     0.9854    0.9122    0.9474       148
           3     0.9324    0.9324    0.9324        74
           4     0.9605    0.9733    0.9669        75

    accuracy                         0.9503       443
   macro avg     0.9474    0.9583    0.9518       443
weighted avg     0.9533    0.9503    0.9507       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  0  73   0   0   2]
 [  0   8 135   5   0]
 [  0   2   2  69   1]
 [  0   2   0   0  73]]
F1-macro: 0.9518
Accuracy: 0.9503

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.5000    1.0000    0.6667         1
           1     0.8444    0.9268    0.8837        41
           2     0.8889    0.8649    0.8767        37
           3     1.0000    0.5833    0.7368        12
           4     0.8571    0.9231    0.8889        13

    accuracy                         0.8654       104
   macro avg     0.8181    0.8596    0.8106       104
weighted avg     0.8765    0.8654    0.8628       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 38  2  0  1]
 [ 0  5 32  0  0]
 [ 1  1  2  7  1]
 [ 0  1  0  0 12]]
F1-macro: 0.8106
Accuracy: 0.8654

=== VAL ===
              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000        71
           1     0.9024    0.9867    0.9427        75
           2     0.9862    0.9662    0.9761       148
           3     0.9859    0.9459    0.9655        74
           4     0.9865    0.9733    0.9799        75

    accuracy                         0.9729       443
   macro avg     0.9722    0.9744    0.9728       443
weighted avg     0.9742    0.9729    0.9731       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  0  74   0   0   1]
 [  0   4 143   1   0]
 [  0   2   2  70   0]
 [  0   2   0   0  73]]
F1-macro: 0.9728
Accuracy: 0.9729

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.5000    1.0000    0.6667         1
           1     0.8444    0.9268    0.8837        41
           2     0.8889    0.8649    0.8767        37
           3     1.0000    0.5833    0.7368        12
           4     0.8571    0.9231    0.8889        13

    accuracy                         0.8654       104
   macro avg     0.8181    0.8596    0.8106       104
weighted avg     0.8765    0.8654    0.8628       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 38  2  0  1]
 [ 0  5 32  0  0]
 [ 1  1  2  7  1]
 [ 0  1  0  0 12]]
F1-macro: 0.8106
Accuracy: 0.8654

=== VAL ===
              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000        71
           1     0.8690    0.9733    0.9182        75
           2     0.9786    0.9257    0.9514       148
           3     0.9452    0.9324    0.9388        74
           4     0.9733    0.9733    0.9733        75

    accuracy                         0.9549       443
   macro avg     0.9532    0.9610    0.9563       443
weighted avg     0.9570    0.9549    0.9552       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  0  73   0   0   2]
 [  0   7 137   4   0]
 [  0   2   3  69   0]
 [  0   2   0   0  73]]
F1-macro: 0.9563
Accuracy: 0.9549

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.5000    1.0000    0.6667         1
           1     0.8636    0.9268    0.8941        41
           2     0.8919    0.8919    0.8919        37
           3     1.0000    0.5833    0.7368        12
           4     0.8571    0.9231    0.8889        13

    accuracy                         0.8750       104
   macro avg     0.8225    0.8650    0.8157       104
weighted avg     0.8851    0.8750    0.8723       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 38  2  0  1]
 [ 0  4 33  0  0]
 [ 1  1  2  7  1]
 [ 0  1  0  0 12]]
F1-macro: 0.8157
Accuracy: 0.8750

=== VAL ===
              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000        71
           1     0.9241    0.9733    0.9481        75
           2     0.9732    0.9797    0.9764       148
           3     0.9855    0.9189    0.9510        74
           4     0.9867    0.9867    0.9867        75

    accuracy                         0.9729       443
   macro avg     0.9739    0.9717    0.9724       443
weighted avg     0.9735    0.9729    0.9729       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  0  73   1   0   1]
 [  0   2 145   1   0]
 [  0   3   3  68   0]
 [  0   1   0   0  74]]
F1-macro: 0.9724
Accuracy: 0.9729

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.5000    1.0000    0.6667         1
           1     0.8837    0.9268    0.9048        41
           2     0.8947    0.9189    0.9067        37
           3     1.0000    0.5833    0.7368        12
           4     0.8571    0.9231    0.8889        13

    accuracy                         0.8846       104
   macro avg     0.8271    0.8704    0.8208       104
weighted avg     0.8940    0.8846    0.8818       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 38  2  0  1]
 [ 0  3 34  0  0]
 [ 1  1  2  7  1]
 [ 0  1  0  0 12]]
F1-macro: 0.8208
Accuracy: 0.8846

=== VAL ===
              precision    recall  f1-score   support

           0     0.9861    1.0000    0.9930        71
           1     0.7717    0.9467    0.8503        75
           2     0.9764    0.8378    0.9018       148
           3     0.9079    0.9324    0.9200        74
           4     0.9474    0.9600    0.9536        75

    accuracy                         0.9187       443
   macro avg     0.9179    0.9354    0.9238       443
weighted avg     0.9269    0.9187    0.9195       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  0  71   0   0   4]
 [  0  17 124   7   0]
 [  0   2   3  69   0]
 [  1   2   0   0  72]]
F1-macro: 0.9238
Accuracy: 0.9187

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.5000    1.0000    0.6667         1
           1     0.8261    0.9268    0.8736        41
           2     0.9310    0.7297    0.8182        37
           3     0.8333    0.8333    0.8333        12
           4     0.8667    1.0000    0.9286        13

    accuracy                         0.8558       104
   macro avg     0.7914    0.8980    0.8241       104
weighted avg     0.8662    0.8558    0.8541       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 38  2  0  1]
 [ 1  7 27  2  0]
 [ 0  1  0 10  1]
 [ 0  0  0  0 13]]
F1-macro: 0.8241
Accuracy: 0.8558

##### SEED = 11 #####

/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1281: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1296: FutureWarning: Using the 'liblinear' solver for multiclass classification is deprecated. An error will be raised in 1.8. Either use another solver which supports the multinomial loss or wrap the estimator in a OneVsRestClassifier to keep applying a one-versus-rest scheme.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1305: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 32.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1281: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1296: FutureWarning: Using the 'liblinear' solver for multiclass classification is deprecated. An error will be raised in 1.8. Either use another solver which supports the multinomial loss or wrap the estimator in a OneVsRestClassifier to keep applying a one-versus-rest scheme.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1305: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 32.
  warnings.warn(

=== VAL ===
              precision    recall  f1-score   support

           0     0.9726    1.0000    0.9861        71
           1     0.7753    0.9200    0.8415        75
           2     0.9843    0.8446    0.9091       148
           3     0.8987    0.9595    0.9281        74
           4     0.9467    0.9467    0.9467        75

    accuracy                         0.9187       443
   macro avg     0.9155    0.9341    0.9223       443
weighted avg     0.9264    0.9187    0.9195       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  0  69   2   0   4]
 [  2  13 125   8   0]
 [  0   3   0  71   0]
 [  0   4   0   0  71]]
F1-macro: 0.9223
Accuracy: 0.9187

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.5000    1.0000    0.6667         1
           1     0.8444    0.9268    0.8837        41
           2     0.9167    0.8919    0.9041        37
           3     1.0000    0.5833    0.7368        12
           4     0.8571    0.9231    0.8889        13

    accuracy                         0.8750       104
   macro avg     0.8237    0.8650    0.8160       104
weighted avg     0.8864    0.8750    0.8726       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 38  2  0  1]
 [ 0  4 33  0  0]
 [ 1  2  1  7  1]
 [ 0  1  0  0 12]]
F1-macro: 0.8160
Accuracy: 0.8750

=== VAL ===
              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000        71
           1     0.8095    0.9067    0.8553        75
           2     0.9783    0.9122    0.9441       148
           3     0.9595    0.9595    0.9595        74
           4     0.9474    0.9600    0.9536        75

    accuracy                         0.9413       443
   macro avg     0.9389    0.9477    0.9425       443
weighted avg     0.9448    0.9413    0.9422       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  0  68   3   0   4]
 [  0  10 135   3   0]
 [  0   3   0  71   0]
 [  0   3   0   0  72]]
F1-macro: 0.9425
Accuracy: 0.9413

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.5000    1.0000    0.6667         1
           1     0.8478    0.9512    0.8966        41
           2     0.9167    0.8919    0.9041        37
           3     1.0000    0.5833    0.7368        12
           4     0.9231    0.9231    0.9231        13

    accuracy                         0.8846       104
   macro avg     0.8375    0.8699    0.8254       104
weighted avg     0.8959    0.8846    0.8819       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 39  2  0  0]
 [ 0  4 33  0  0]
 [ 1  2  1  7  1]
 [ 0  1  0  0 12]]
F1-macro: 0.8254
Accuracy: 0.8846

=== VAL ===
              precision    recall  f1-score   support

           0     0.9726    1.0000    0.9861        71
           1     0.8313    0.9200    0.8734        75
           2     0.9710    0.9054    0.9371       148
           3     0.9333    0.9459    0.9396        74
           4     0.9595    0.9467    0.9530        75

    accuracy                         0.9368       443
   macro avg     0.9335    0.9436    0.9378       443
weighted avg     0.9394    0.9368    0.9373       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  0  69   3   0   3]
 [  2   7 134   5   0]
 [  0   3   1  70   0]
 [  0   4   0   0  71]]
F1-macro: 0.9378
Accuracy: 0.9368

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.5000    1.0000    0.6667         1
           1     0.8636    0.9268    0.8941        41
           2     0.8919    0.8919    0.8919        37
           3     1.0000    0.5833    0.7368        12
           4     0.8571    0.9231    0.8889        13

    accuracy                         0.8750       104
   macro avg     0.8225    0.8650    0.8157       104
weighted avg     0.8851    0.8750    0.8723       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 38  2  0  1]
 [ 0  4 33  0  0]
 [ 1  1  2  7  1]
 [ 0  1  0  0 12]]
F1-macro: 0.8157
Accuracy: 0.8750

=== VAL ===
              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000        71
           1     0.8701    0.8933    0.8816        75
           2     0.9524    0.9459    0.9492       148
           3     0.9861    0.9595    0.9726        74
           4     0.9605    0.9733    0.9669        75

    accuracy                         0.9526       443
   macro avg     0.9538    0.9544    0.9540       443
weighted avg     0.9531    0.9526    0.9528       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  0  67   5   0   3]
 [  0   7 140   1   0]
 [  0   1   2  71   0]
 [  0   2   0   0  73]]
F1-macro: 0.9540
Accuracy: 0.9526

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.5000    1.0000    0.6667         1
           1     0.8444    0.9268    0.8837        41
           2     0.9167    0.8919    0.9041        37
           3     1.0000    0.5833    0.7368        12
           4     0.8571    0.9231    0.8889        13

    accuracy                         0.8750       104
   macro avg     0.8237    0.8650    0.8160       104
weighted avg     0.8864    0.8750    0.8726       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 38  2  0  1]
 [ 0  4 33  0  0]
 [ 1  2  1  7  1]
 [ 0  1  0  0 12]]
F1-macro: 0.8160
Accuracy: 0.8750

=== VAL ===
              precision    recall  f1-score   support

           0     0.9103    1.0000    0.9530        71
           1     0.7586    0.8800    0.8148        75
           2     0.9435    0.7905    0.8603       148
           3     0.8765    0.9595    0.9161        74
           4     0.9315    0.9067    0.9189        75

    accuracy                         0.8871       443
   macro avg     0.8841    0.9073    0.8926       443
weighted avg     0.8937    0.8871    0.8867       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  1  66   3   1   4]
 [  5  16 117   9   1]
 [  0   0   3  71   0]
 [  1   5   1   0  68]]
F1-macro: 0.8926
Accuracy: 0.8871

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.3333    1.0000    0.5000         1
           1     0.8043    0.9024    0.8506        41
           2     0.9231    0.6486    0.7619        37
           3     0.7143    0.8333    0.7692        12
           4     0.8667    1.0000    0.9286        13

    accuracy                         0.8173       104
   macro avg     0.7283    0.8769    0.7621       104
weighted avg     0.8395    0.8173    0.8160       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 1 37  2  0  1]
 [ 1  8 24  4  0]
 [ 0  1  0 10  1]
 [ 0  0  0  0 13]]
F1-macro: 0.7621
Accuracy: 0.8173

##### SEED = 13 #####


=== VAL ===
              precision    recall  f1-score   support

           0     0.9718    0.9718    0.9718        71
           1     0.7849    0.9733    0.8690        75
           2     0.9690    0.8446    0.9025       148
           3     0.8861    0.9459    0.9150        74
           4     1.0000    0.9467    0.9726        75

    accuracy                         0.9210       443
   macro avg     0.9224    0.9365    0.9262       443
weighted avg     0.9297    0.9210    0.9219       443

Confusion matrix:
 [[ 69   2   0   0   0]
 [  1  73   1   0   0]
 [  1  13 125   9   0]
 [  0   2   2  70   0]
 [  0   3   1   0  71]]
F1-macro: 0.9262
Accuracy: 0.9210

=== TEST (fijo) ===

/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1281: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1296: FutureWarning: Using the 'liblinear' solver for multiclass classification is deprecated. An error will be raised in 1.8. Either use another solver which supports the multinomial loss or wrap the estimator in a OneVsRestClassifier to keep applying a one-versus-rest scheme.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1305: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 32.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1281: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1296: FutureWarning: Using the 'liblinear' solver for multiclass classification is deprecated. An error will be raised in 1.8. Either use another solver which supports the multinomial loss or wrap the estimator in a OneVsRestClassifier to keep applying a one-versus-rest scheme.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1305: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 32.
  warnings.warn(

              precision    recall  f1-score   support

           0     0.5000    1.0000    0.6667         1
           1     0.8478    0.9512    0.8966        41
           2     0.8889    0.8649    0.8767        37
           3     1.0000    0.5833    0.7368        12
           4     0.9231    0.9231    0.9231        13

    accuracy                         0.8750       104
   macro avg     0.8320    0.8645    0.8200       104
weighted avg     0.8861    0.8750    0.8722       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 39  2  0  0]
 [ 0  5 32  0  0]
 [ 1  1  2  7  1]
 [ 0  1  0  0 12]]
F1-macro: 0.8200
Accuracy: 0.8750

=== VAL ===
              precision    recall  f1-score   support

           0     0.9859    0.9859    0.9859        71
           1     0.8690    0.9733    0.9182        75
           2     0.9718    0.9324    0.9517       148
           3     0.9863    0.9730    0.9796        74
           4     0.9863    0.9600    0.9730        75

    accuracy                         0.9594       443
   macro avg     0.9599    0.9649    0.9617       443
weighted avg     0.9616    0.9594    0.9598       443

Confusion matrix:
 [[ 70   1   0   0   0]
 [  1  73   1   0   0]
 [  0   8 138   1   1]
 [  0   0   2  72   0]
 [  0   2   1   0  72]]
F1-macro: 0.9617
Accuracy: 0.9594

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.5000    1.0000    0.6667         1
           1     0.8636    0.9268    0.8941        41
           2     0.8919    0.8919    0.8919        37
           3     1.0000    0.5833    0.7368        12
           4     0.8571    0.9231    0.8889        13

    accuracy                         0.8750       104
   macro avg     0.8225    0.8650    0.8157       104
weighted avg     0.8851    0.8750    0.8723       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 38  2  0  1]
 [ 0  4 33  0  0]
 [ 1  1  2  7  1]
 [ 0  1  0  0 12]]
F1-macro: 0.8157
Accuracy: 0.8750

=== VAL ===
              precision    recall  f1-score   support

           0     0.9710    0.9437    0.9571        71
           1     0.7912    0.9600    0.8675        75
           2     0.9420    0.8784    0.9091       148
           3     0.9324    0.9324    0.9324        74
           4     1.0000    0.9467    0.9726        75

    accuracy                         0.9233       443
   macro avg     0.9273    0.9322    0.9277       443
weighted avg     0.9294    0.9233    0.9244       443

Confusion matrix:
 [[ 67   2   2   0   0]
 [  1  72   2   0   0]
 [  1  12 130   5   0]
 [  0   2   3  69   0]
 [  0   3   1   0  71]]
F1-macro: 0.9277
Accuracy: 0.9233

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.5000    1.0000    0.6667         1
           1     0.8667    0.9512    0.9070        41
           2     0.8919    0.8919    0.8919        37
           3     1.0000    0.5833    0.7368        12
           4     0.9231    0.9231    0.9231        13

    accuracy                         0.8846       104
   macro avg     0.8363    0.8699    0.8251       104
weighted avg     0.8946    0.8846    0.8817       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 39  2  0  0]
 [ 0  4 33  0  0]
 [ 1  1  2  7  1]
 [ 0  1  0  0 12]]
F1-macro: 0.8251
Accuracy: 0.8846

=== VAL ===
              precision    recall  f1-score   support

           0     0.9857    0.9718    0.9787        71
           1     0.8642    0.9333    0.8974        75
           2     0.9452    0.9324    0.9388       148
           3     0.9861    0.9595    0.9726        74
           4     0.9730    0.9600    0.9664        75

    accuracy                         0.9481       443
   macro avg     0.9508    0.9514    0.9508       443
weighted avg     0.9495    0.9481    0.9485       443

Confusion matrix:
 [[ 69   1   1   0   0]
 [  1  70   3   1   0]
 [  0   8 138   0   2]
 [  0   0   3  71   0]
 [  0   2   1   0  72]]
F1-macro: 0.9508
Accuracy: 0.9481

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.5000    1.0000    0.6667         1
           1     0.8837    0.9268    0.9048        41
           2     0.8684    0.8919    0.8800        37
           3     1.0000    0.5833    0.7368        12
           4     0.8571    0.9231    0.8889        13

    accuracy                         0.8750       104
   macro avg     0.8219    0.8650    0.8154       104
weighted avg     0.8847    0.8750    0.8723       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 38  2  0  1]
 [ 0  4 33  0  0]
 [ 1  0  3  7  1]
 [ 0  1  0  0 12]]
F1-macro: 0.8154
Accuracy: 0.8750

=== VAL ===
              precision    recall  f1-score   support

           0     0.9459    0.9859    0.9655        71
           1     0.7692    0.9333    0.8434        75
           2     0.9600    0.8108    0.8791       148
           3     0.8987    0.9595    0.9281        74
           4     0.9865    0.9733    0.9799        75

    accuracy                         0.9120       443
   macro avg     0.9121    0.9326    0.9192       443
weighted avg     0.9197    0.9120    0.9122       443

Confusion matrix:
 [[ 70   1   0   0   0]
 [  1  70   3   0   1]
 [  2  18 120   8   0]
 [  1   0   2  71   0]
 [  0   2   0   0  73]]
F1-macro: 0.9192
Accuracy: 0.9120

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.3333    1.0000    0.5000         1
           1     0.8000    0.8780    0.8372        41
           2     0.8966    0.7027    0.7879        37
           3     0.8333    0.8333    0.8333        12
           4     0.8667    1.0000    0.9286        13

    accuracy                         0.8269       104
   macro avg     0.7460    0.8828    0.7774       104
weighted avg     0.8420    0.8269    0.8274       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 1 36  3  0  1]
 [ 1  8 26  2  0]
 [ 0  1  0 10  1]
 [ 0  0  0  0 13]]
F1-macro: 0.7774
Accuracy: 0.8269

##### SEED = 17 #####


=== VAL ===
              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000        71
           1     0.8333    0.9333    0.8805        75
           2     0.9517    0.9324    0.9420       148
           3     0.9857    0.9324    0.9583        74
           4     0.9452    0.9200    0.9324        75

    accuracy                         0.9413       443
   macro avg     0.9432    0.9436    0.9426       443
weighted avg     0.9440    0.9413    0.9420       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  0  70   3   1   1]
 [  0   8 138   0   2]
 [  0   0   4  69   1]
 [  0   6   0   0  69]]
F1-macro: 0.9426
Accuracy: 0.9413

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.5000    1.0000    0.6667         1
           1     0.8636    0.9268    0.8941        41
           2     0.8889    0.8649    0.8767        37
           3     0.8750    0.5833    0.7000        12
           4     0.8571    0.9231    0.8889        13

    accuracy                         0.8654       104
   macro avg     0.7969    0.8596    0.8053       104
weighted avg     0.8696    0.8654    0.8627       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 38  2  0  1]
 [ 0  4 32  1  0]
 [ 1  1  2  7  1]
 [ 0  1  0  0 12]]
F1-macro: 0.8053
Accuracy: 0.8654

=== VAL ===
              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000        71
           1     0.8333    0.9333    0.8805        75
           2     0.9583    0.9324    0.9452       148
           3     0.9859    0.9459    0.9655        74
           4     0.9589    0.9333    0.9459        75

    accuracy                         0.9458       443
   macro avg     0.9473    0.9490    0.9474       443
weighted avg     0.9486    0.9458    0.9466       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  0  70   3   1   1]
 [  0   8 138   0   2]
 [  0   1   3  70   0]
 [  0   5   0   0  70]]
F1-macro: 0.9474
Accuracy: 0.9458

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.5000    1.0000    0.6667         1
           1     0.8837    0.9268    0.9048        41
           2     0.8919    0.8919    0.8919        37
           3     0.8750    0.5833    0.7000        12
           4     0.8571    0.9231    0.8889        13

    accuracy                         0.8750       104
   macro avg     0.8016    0.8650    0.8104       104
weighted avg     0.8786    0.8750    0.8723       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 38  2  0  1]
 [ 0  3 33  1  0]
 [ 1  1  2  7  1]
 [ 0  1  0  0 12]]
F1-macro: 0.8104
Accuracy: 0.8750

=== VAL ===
              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000        71
           1     0.8313    0.9200    0.8734        75
           2     0.9517    0.9324    0.9420       148
           3     0.9722    0.9459    0.9589        74
           4     0.9583    0.9200    0.9388        75

    accuracy                         0.9413       443
   macro avg     0.9427    0.9437    0.9426       443
weighted avg     0.9436    0.9413    0.9420       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  0  69   3   2   1]
 [  0   8 138   0   2]
 [  0   0   4  70   0]
 [  0   6   0   0  69]]
F1-macro: 0.9426
Accuracy: 0.9413

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.5000    1.0000    0.6667         1
           1     0.8837    0.9268    0.9048        41
           2     0.8919    0.8919    0.8919        37
           3     0.8750    0.5833    0.7000        12
           4     0.8571    0.9231    0.8889        13

    accuracy                         0.8750       104
   macro avg     0.8016    0.8650    0.8104       104
weighted avg     0.8786    0.8750    0.8723       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 38  2  0  1]
 [ 0  3 33  1  0]
 [ 1  1  2  7  1]
 [ 0  1  0  0 12]]
F1-macro: 0.8104
Accuracy: 0.8750

=== VAL ===
              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000        71
           1     0.8395    0.9067    0.8718        75
           2     0.9459    0.9459    0.9459       148
           3     0.9859    0.9459    0.9655        74
           4     0.9722    0.9333    0.9524        75

    accuracy                         0.9458       443
   macro avg     0.9487    0.9464    0.9471       443
weighted avg     0.9477    0.9458    0.9464       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  0  68   5   1   1]
 [  0   7 140   0   1]
 [  0   1   3  70   0]
 [  0   5   0   0  70]]
F1-macro: 0.9471
Accuracy: 0.9458

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.5000    1.0000    0.6667         1
           1     0.9268    0.9268    0.9268        41
           2     0.8718    0.9189    0.8947        37
           3     0.8750    0.5833    0.7000        12
           4     0.8571    0.9231    0.8889        13

    accuracy                         0.8846       104
   macro avg     0.8062    0.8704    0.8154       104
weighted avg     0.8885    0.8846    0.8820       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 38  2  0  1]
 [ 0  2 34  1  0]
 [ 1  0  3  7  1]
 [ 0  1  0  0 12]]
F1-macro: 0.8154
Accuracy: 0.8846

=== VAL ===
              precision    recall  f1-score   support

           0     0.9726    1.0000    0.9861        71
           1     0.7701    0.8933    0.8272        75
           2     0.9612    0.8378    0.8953       148
           3     0.9125    0.9865    0.9481        74
           4     0.9459    0.9333    0.9396        75

    accuracy                         0.9142       443
   macro avg     0.9125    0.9302    0.9192       443
weighted avg     0.9200    0.9142    0.9146       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  0  67   3   3   2]
 [  2  18 124   2   2]
 [  0   0   1  73   0]
 [  0   2   1   2  70]]
F1-macro: 0.9192
Accuracy: 0.9142

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.3333    1.0000    0.5000         1
           1     0.8182    0.8780    0.8471        41
           2     0.8966    0.7027    0.7879        37
           3     0.7692    0.8333    0.8000        12
           4     0.8667    1.0000    0.9286        13

    accuracy                         0.8269       104
   macro avg     0.7368    0.8828    0.7727       104
weighted avg     0.8418    0.8269    0.8274       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 1 36  3  0  1]
 [ 1  7 26  3  0]
 [ 0  1  0 10  1]
 [ 0  0  0  0 13]]
F1-macro: 0.7727
Accuracy: 0.8269

##### SEED = 19 #####


=== VAL ===
              precision    recall  f1-score   support

           0     0.9726    1.0000    0.9861        71
           1     0.8072    0.8933    0.8481        75
           2     0.9291    0.8851    0.9066       148
           3     0.8904    0.8784    0.8844        74
           4     0.9452    0.9200    0.9324        75

    accuracy                         0.9097       443
   macro avg     0.9089    0.9154    0.9115       443
weighted avg     0.9117    0.9097    0.9101       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  1  67   5   0   2]
 [  1   8 131   7   1]
 [  0   4   4  65   1]
 [  0   4   1   1  69]]
F1-macro: 0.9115
Accuracy: 0.9097

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.5000    1.0000    0.6667         1
           1     0.8444    0.9268    0.8837        41
           2     0.8889    0.8649    0.8767        37
           3     1.0000    0.5833    0.7368        12
           4     0.8571    0.9231    0.8889        13

    accuracy                         0.8654       104
   macro avg     0.8181    0.8596    0.8106       104
weighted avg     0.8765    0.8654    0.8628       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 38  2  0  1]
 [ 0  5 32  0  0]
 [ 1  1  2  7  1]
 [ 0  1  0  0 12]]
F1-macro: 0.8106
Accuracy: 0.8654

=== VAL ===
              precision    recall  f1-score   support

           0     0.9861    1.0000    0.9930        71
           1     0.8933    0.8933    0.8933        75
           2     0.9392    0.9392    0.9392       148
           3     0.9315    0.9189    0.9252        74
           4     0.9467    0.9467    0.9467        75

    accuracy                         0.9391       443
   macro avg     0.9394    0.9396    0.9395       443
weighted avg     0.9389    0.9391    0.9390       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  1  67   6   0   1]
 [  0   2 139   5   2]
 [  0   2   3  68   1]
 [  0   4   0   0  71]]
F1-macro: 0.9395
Accuracy: 0.9391

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.5000    1.0000    0.6667         1
           1     0.8478    0.9512    0.8966        41
           2     0.8889    0.8649    0.8767        37
           3     1.0000    0.5833    0.7368        12
           4     0.9231    0.9231    0.9231        13

    accuracy                         0.8750       104
   macro avg     0.8320    0.8645    0.8200       104
weighted avg     0.8861    0.8750    0.8722       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 39  2  0  0]
 [ 0  5 32  0  0]
 [ 1  1  2  7  1]
 [ 0  1  0  0 12]]
F1-macro: 0.8200
Accuracy: 0.8750

=== VAL ===
              precision    recall  f1-score   support

           0     0.9726    1.0000    0.9861        71
           1     0.8701    0.8933    0.8816        75
           2     0.9320    0.9257    0.9288       148
           3     0.9041    0.8919    0.8980        74
           4     0.9452    0.9200    0.9324        75

    accuracy                         0.9255       443
   macro avg     0.9248    0.9262    0.9254       443
weighted avg     0.9256    0.9255    0.9255       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  1  67   5   0   2]
 [  1   3 137   6   1]
 [  0   3   4  66   1]
 [  0   4   1   1  69]]
F1-macro: 0.9254
Accuracy: 0.9255

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.5000    1.0000    0.6667         1
           1     0.8667    0.9512    0.9070        41
           2     0.8919    0.8919    0.8919        37
           3     1.0000    0.5833    0.7368        12
           4     0.9231    0.9231    0.9231        13

    accuracy                         0.8846       104
   macro avg     0.8363    0.8699    0.8251       104
weighted avg     0.8946    0.8846    0.8817       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 39  2  0  0]
 [ 0  4 33  0  0]
 [ 1  1  2  7  1]
 [ 0  1  0  0 12]]
F1-macro: 0.8251
Accuracy: 0.8846

=== VAL ===
              precision    recall  f1-score   support

           0     0.9861    1.0000    0.9930        71
           1     0.8904    0.8667    0.8784        75
           2     0.9216    0.9527    0.9369       148
           3     0.9710    0.9054    0.9371        74
           4     0.9474    0.9600    0.9536        75

    accuracy                         0.9391       443
   macro avg     0.9433    0.9370    0.9398       443
weighted avg     0.9393    0.9391    0.9388       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  1  65   8   0   1]
 [  0   3 141   2   2]
 [  0   2   4  67   1]
 [  0   3   0   0  72]]
F1-macro: 0.9398
Accuracy: 0.9391

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.5000    1.0000    0.6667         1
           1     0.8636    0.9268    0.8941        41
           2     0.8919    0.8919    0.8919        37
           3     1.0000    0.5833    0.7368        12
           4     0.8571    0.9231    0.8889        13

    accuracy                         0.8750       104
   macro avg     0.8225    0.8650    0.8157       104
weighted avg     0.8851    0.8750    0.8723       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 38  2  0  1]
 [ 0  4 33  0  0]
 [ 1  1  2  7  1]
 [ 0  1  0  0 12]]
F1-macro: 0.8157
Accuracy: 0.8750

=== VAL ===
              precision    recall  f1-score   support

           0     0.9595    1.0000    0.9793        71
           1     0.8533    0.8533    0.8533        75
           2     0.9220    0.8784    0.8997       148
           3     0.8800    0.8919    0.8859        74
           4     0.8974    0.9333    0.9150        75

    accuracy                         0.9052       443
   macro avg     0.9024    0.9114    0.9066       443
weighted avg     0.9052    0.9052    0.9049       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  1  64   6   0   4]
 [  1   7 130   8   2]
 [  0   2   4  66   2]
 [  1   2   1   1  70]]
F1-macro: 0.9066
Accuracy: 0.9052

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.3333    1.0000    0.5000         1
           1     0.8409    0.9024    0.8706        41
           2     0.9032    0.7568    0.8235        37
           3     0.8182    0.7500    0.7826        12
           4     0.8667    1.0000    0.9286        13

    accuracy                         0.8462       104
   macro avg     0.7525    0.8818    0.7811       104
weighted avg     0.8588    0.8462    0.8474       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 1 37  2  0  1]
 [ 1  6 28  2  0]
 [ 0  1  1  9  1]
 [ 0  0  0  0 13]]
F1-macro: 0.7811
Accuracy: 0.8462

=====================================
Resumen Multi-Seed (95% CI)
=====================================
             model  val_f1_macro_mean  val_f1_macro_std  val_f1_macro_CI_low  val_f1_macro_CI_high  test_f1_macro_mean  test_f1_macro_std  test_f1_macro_CI_low  test_f1_macro_CI_high
passive_aggressive           0.952840          0.012172             0.942171              0.963509            0.816670           0.002303              0.814651               0.818689
        linear_svm           0.952786          0.014078             0.940446              0.965126            0.816422           0.006416              0.810798               0.822046

/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1281: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1296: FutureWarning: Using the 'liblinear' solver for multiclass classification is deprecated. An error will be raised in 1.8. Either use another solver which supports the multinomial loss or wrap the estimator in a OneVsRestClassifier to keep applying a one-versus-rest scheme.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1305: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 32.
  warnings.warn(

In [119]:
df_summary

,model,val_f1_macro_mean,val_f1_macro_std,val_f1_macro_CI_low,val_f1_macro_CI_high,test_f1_macro_mean,test_f1_macro_std,test_f1_macro_CI_low,test_f1_macro_CI_high
4,sgd_log,0.812323,0.037968,0.779043,0.845604,0.777282,0.013976,0.765032,0.789532
3,passive_aggressive,0.807570,0.040248,0.772291,0.842848,0.766606,0.034440,0.736418,0.796793
1,linear_svm,0.792903,0.050220,0.748883,0.836923,0.760166,0.010335,0.751107,0.769225
2,logreg_ovr,0.760215,0.017529,0.744850,0.775580,0.737553,0.008155,0.730404,0.744701
0,complement_nb,0.703088,0.014002,0.690815,0.715362,0.698448,0.023736,0.677643,0.719254

In [122]:
df_summary

,model,val_f1_macro_mean,val_f1_macro_std,val_f1_macro_CI_low,val_f1_macro_CI_high,test_f1_macro_mean,test_f1_macro_std,test_f1_macro_CI_low,test_f1_macro_CI_high
3,passive_aggressive,0.952840,0.012172,0.942171,0.963509,0.816670,0.002303,0.814651,0.818689
1,linear_svm,0.952786,0.014078,0.940446,0.965126,0.816422,0.006416,0.810798,0.822046
4,sgd_log,0.937986,0.012473,0.927053,0.948920,0.818397,0.006474,0.812723,0.824072
2,logreg_ovr,0.930899,0.016190,0.916709,0.945090,0.812485,0.005657,0.807526,0.817444
0,complement_nb,0.912296,0.012705,0.901160,0.923432,0.783456,0.023796,0.762598,0.804314

## Create new test

In [13]:
def map_new_csv_to_hate_categories(df_new_full, text_col="tweet"):
    """
    A partir de df_new_full con columnas [text_col, target],
    crea una columna predicted_hate_category compatible con df_tweethate.

    target:
        origin              -> hate_origin
        disability          -> hate_disability
        gender              -> hate_gender
        sexual_orientation  -> hate_sexuality
        religion            -> hate_religion
        other               -> se descarta (no mapeamos)

    Devuelve:
        df_mapped con columnas:
            - text
            - target
            - predicted_hate_category
            - clean
    """
    df = df_new_full.copy()

    # Mapeo target -> categoría hate_*
    target2hate = {
        "origin":             "hate_origin",
        "disability":         "hate_disability",
        "gender":             "hate_gender",
        "sexual_orientation": "hate_sexuality",
        "religion":           "hate_religion",
        # "other": None  # lo descartamos
    }

    df["predicted_hate_category"] = df["target"].map(target2hate)

    # Nos quedamos solo con targets que mapean a una categoría conocida
    df = df[~df["predicted_hate_category"].isna()].copy()

    # Normalizamos nombre de columna de texto para que coincida con df_tweethate (text)
    df["text"] = df[text_col]

    # Limpiamos texto igual que en el resto del pipeline
    df["clean"] = df["text"].apply(clean_text)

    return df

In [14]:
df_new_mapped = map_new_csv_to_hate_categories(df_new_full, text_col="tweet")

In [19]:
import numpy as np
import pandas as pd

def augment_test_with_new_data(
    df_test,
    df_new_mapped,
    label_col="predicted_hate_category",
    total_new=500,
    random_state=42,
    mode="proportional",
):
    """
    Añade ejemplos de df_new_mapped al df_test.

    Parámetros:
        df_test       : DataFrame de test original
        df_new_mapped : DataFrame con columnas [text, clean, label_col]
        label_col     : nombre de columna de clase (por defecto 'predicted_hate_category')
        total_new     : nº total de ejemplos nuevos a intentar añadir
        random_state  : semilla para reproducibilidad
        mode          : 
            - "proportional": mantiene aprox. la distribución de clases de df_test (modo original).
            - "balanced": reparte los nuevos ejemplos de forma aproximadamente uniforme
                          entre las clases presentes en df_test y df_new_mapped.

    Devuelve:
        df_test_aug   : test original + nuevos ejemplos
        df_added      : solo los ejemplos añadidos

    Nota:
        En modo "balanced" el nº real de ejemplos añadidos puede ser < total_new
        si alguna clase no tiene suficientes ejemplos en df_new_mapped.
    """
    df_test = df_test.copy()
    df_new  = df_new_mapped.copy()

    # Clases presentes en test (en orden de frecuencia)
    test_counts = df_test[label_col].value_counts()
    labels_in_test = list(test_counts.index)

    # Filtrar a clases que también existen en df_new
    labels_new = set(df_new[label_col].unique())
    labels = [lab for lab in labels_in_test if lab in labels_new]

    if not labels:
        raise RuntimeError("No hay solapamiento de clases entre df_test y df_new_mapped.")

    samples = []

    if mode == "proportional":
        # Distribución actual en test (normalizada)
        dist = (test_counts / test_counts.sum()).loc[labels]

        for label, p in dist.items():
            n_label = int(round(total_new * p))
            pool = df_new[df_new[label_col] == label]

            if len(pool) == 0:
                print(f"[WARN] No hay ejemplos en df_new_mapped para la clase {label}, se salta.")
                continue

            n_label = min(n_label, len(pool))
            if n_label <= 0:
                continue

            samples.append(pool.sample(n=n_label, random_state=random_state))

    elif mode == "balanced":
        # Reparto aproximadamente uniforme entre las clases posibles
        n_classes = len(labels)
        if n_classes == 0:
            raise RuntimeError("No hay clases válidas para modo 'balanced'.")

        base = total_new // n_classes
        remainder = total_new % n_classes

        for idx, label in enumerate(labels):
            pool = df_new[df_new[label_col] == label]

            if len(pool) == 0:
                print(f"[WARN] No hay ejemplos en df_new_mapped para la clase {label}, se salta.")
                continue

            # reparto uniforme base + 1 para las primeras 'remainder' clases
            n_label = base + (1 if idx < remainder else 0)
            n_label = min(n_label, len(pool))

            if n_label <= 0:
                continue

            samples.append(pool.sample(n=n_label, random_state=random_state))

    else:
        raise ValueError("mode debe ser 'proportional' o 'balanced'.")

    if not samples:
        raise RuntimeError("No se han podido muestrear ejemplos nuevos; revisa el solapamiento de clases.")

    df_added = pd.concat(samples, ignore_index=True)

    # Concatenamos al test
    df_test_aug = pd.concat([df_test, df_added], ignore_index=True)

    return df_test_aug, df_added

In [21]:
my_train_df = load_and_clean_tweethate(INPUT_JSONL, text_field="text_masked")
my_test_df = load_and_clean_tweethate("supertweeteval/test_split_only_originals.jsonl", text_field="text_masked")

my_train_df = remove_values_from_column(my_train_df, "predicted_hate_category", ["hate_age"])
my_test_df = remove_values_from_column(my_test_df, "predicted_hate_category", ["hate_age"])

my_train_df = collapse_race_into_origin(my_train_df, col="predicted_hate_category")
my_test_df      = collapse_race_into_origin(my_test_df,      col="predicted_hate_category")

df_tweethate = collapse_race_into_origin(my_train_df, "predicted_hate_category")
df_test      = collapse_race_into_origin(my_test_df,      "predicted_hate_category")

# 2) Mapear dataset nuevo a categorías hate_*
df_new_mapped = map_new_csv_to_hate_categories(df_new_full, text_col="tweet")

# 3) Aumentar el test con, por ejemplo, 300 nuevos ejemplos
df_test_aug, df_added = augment_test_with_new_data(
    df_test, df_new_mapped, total_new=500, mode="balanced"
)

print("Tamaño original test:", len(df_test))
print("Nuevos ejemplos añadidos:", len(df_added))
print("Nuevo tamaño test:", len(df_test_aug))

print("\nDistribución original test:")
print(df_test["predicted_hate_category"].value_counts(normalize=True))

print("\nDistribución test aumentada:")
print(df_test_aug["predicted_hate_category"].value_counts(normalize=True))

Tamaño original test: 104
Nuevos ejemplos añadidos: 468
Nuevo tamaño test: 572

Distribución original test:
predicted_hate_category
hate_gender        0.394231
hate_origin        0.355769
hate_sexuality     0.125000
hate_religion      0.115385
hate_disability    0.009615
Name: proportion, dtype: float64

Distribución test aumentada:
predicted_hate_category
hate_gender        0.246503
hate_origin        0.239510
hate_sexuality     0.197552
hate_disability    0.176573
hate_religion      0.139860
Name: proportion, dtype: float64

In [26]:
INPUT_JSONL = "supertweeteval/merged_masked_unionv2.jsonl"

#INPUT_JSONL = "supertweeteval/broken_phone/balanced_with_broken_phone_supertweetevalv3.jsonl"

my_train_df = load_and_clean_tweethate(INPUT_JSONL, text_field="text_masked")

my_train_df = remove_values_from_column(my_train_df, "predicted_hate_category", ["hate_age"])

my_train_df = collapse_race_into_origin(my_train_df, col="predicted_hate_category")

In [27]:
df_all_runs, df_summary = experiment_from_df_multi_seed(
    df_trainval=my_train_df,
    df_test=df_test_aug,
    X_field="text",
    seeds=[7,11,13,17,19]
)

=====================================
 Ejecutando Seeds: [7, 11, 13, 17, 19]
=====================================

##### SEED = 7 #####


=== VAL ===
              precision    recall  f1-score   support

           0     0.1000    0.5000    0.1667         2
           1     0.8966    0.6753    0.7704        77
           2     0.8750    0.6901    0.7717        71
           3     0.5238    0.9565    0.6769        23
           4     0.5938    0.7600    0.6667        25

    accuracy                         0.7222       198
   macro avg     0.5978    0.7164    0.6105       198
weighted avg     0.7992    0.7222    0.7408       198

Confusion matrix:
 [[ 1  0  0  1  0]
 [ 3 52  7  5 10]
 [ 4  4 49 11  3]
 [ 0  1  0 22  0]
 [ 2  1  0  3 19]]
F1-macro: 0.6105
Accuracy: 0.7222

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.6081    0.4455    0.5143       101
           1     0.7471    0.4610    0.5702       141
           2     0.6907    0.4891    0.5726       137
           3     0.3067    0.5750    0.4000        80
           4     0.6220    0.9027    0.7365       113

    accuracy                         0.5682       572
   macro avg     0.5949    0.5746    0.5587       572
weighted avg     0.6227    0.5682    0.5699       572

Confusion matrix:
 [[ 45   5   7  28  16]
 [ 11  65  11  36  18]
 [  8   7  67  36  19]
 [  7   7  11  46   9]
 [  3   3   1   4 102]]
F1-macro: 0.5587
Accuracy: 0.5682

=== VAL ===
              precision    recall  f1-score   support

           0     0.3333    0.5000    0.4000         2
           1     0.8788    0.7532    0.8112        77
           2     0.8472    0.8592    0.8531        71
           3     0.7037    0.8261    0.7600        23
           4     0.6667    0.8000    0.7273        25

    accuracy                         0.8030       198
   macro avg     0.6859    0.7477    0.7103       198
weighted avg     0.8148    0.8030    0.8055       198

Confusion matrix:
 [[ 1  0  1  0  0]
 [ 2 58  7  3  7]
 [ 0  3 61  5  2]
 [ 0  1  2 19  1]
 [ 0  4  1  0 20]]
F1-macro: 0.7103
Accuracy: 0.8030

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.7119    0.4158    0.5250       101
           1     0.6508    0.5816    0.6142       141
           2     0.5759    0.6642    0.6169       137
           3     0.5395    0.5125    0.5256        80
           4     0.6667    0.9027    0.7669       113

    accuracy                         0.6259       572
   macro avg     0.6289    0.6154    0.6097       572
weighted avg     0.6312    0.6259    0.6169       572

Confusion matrix:
 [[ 42  14  22  13  10]
 [  5  82  27   9  18]
 [  7  12  91  11  16]
 [  3  14  15  41   7]
 [  2   4   3   2 102]]
F1-macro: 0.6097
Accuracy: 0.6259

=== VAL ===
              precision    recall  f1-score   support

           0     0.5000    0.5000    0.5000         2
           1     0.8592    0.7922    0.8243        77
           2     0.8451    0.8451    0.8451        71
           3     0.7143    0.8696    0.7843        23
           4     0.7308    0.7600    0.7451        25

    accuracy                         0.8131       198
   macro avg     0.7299    0.7534    0.7398       198
weighted avg     0.8174    0.8131    0.8138       198

Confusion matrix:
 [[ 1  0  1  0  0]
 [ 1 61  8  2  5]
 [ 0  4 60  5  2]
 [ 0  2  1 20  0]
 [ 0  4  1  1 19]]
F1-macro: 0.7398
Accuracy: 0.8131

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.7119    0.4158    0.5250       101
           1     0.6560    0.5816    0.6165       141
           2     0.5363    0.7007    0.6076       137
           3     0.5672    0.4750    0.5170        80
           4     0.7254    0.9115    0.8078       113

    accuracy                         0.6311       572
   macro avg     0.6393    0.6169    0.6148       572
weighted avg     0.6385    0.6311    0.6221       572

Confusion matrix:
 [[ 42  13  28  11   7]
 [  4  82  33   9  13]
 [  7  12  96   9  13]
 [  4  14  18  38   6]
 [  2   4   4   0 103]]
F1-macro: 0.6148
Accuracy: 0.6311

=== VAL ===
              precision    recall  f1-score   support

           0     0.0000    0.0000    0.0000         2
           1     0.8750    0.8182    0.8456        77
           2     0.7927    0.9155    0.8497        71
           3     0.8095    0.7391    0.7727        23
           4     0.8261    0.7600    0.7917        25

    accuracy                         0.8283       198
   macro avg     0.6607    0.6466    0.6519       198
weighted avg     0.8229    0.8283    0.8233       198

Confusion matrix:
 [[ 0  1  1  0  0]
 [ 0 63 10  2  2]
 [ 0  3 65  2  1]
 [ 0  1  4 17  1]
 [ 0  4  2  0 19]]
F1-macro: 0.6519
Accuracy: 0.8283

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.7692    0.2970    0.4286       101
           1     0.5705    0.6312    0.5993       141
           2     0.5181    0.7299    0.6061       137
           3     0.6458    0.3875    0.4844        80
           4     0.7426    0.8938    0.8112       113

    accuracy                         0.6136       572
   macro avg     0.6493    0.5879    0.5859       572
weighted avg     0.6376    0.6136    0.5966       572

Confusion matrix:
 [[ 30  23  34   8   6]
 [  3  89  35   3  11]
 [  2  17 100   6  12]
 [  2  21  20  31   6]
 [  2   6   4   0 101]]
F1-macro: 0.5859
Accuracy: 0.6136

=== VAL ===
              precision    recall  f1-score   support

           0     0.0769    0.5000    0.1333         2
           1     0.8421    0.6234    0.7164        77
           2     0.8269    0.6056    0.6992        71
           3     0.5238    0.9565    0.6769        23
           4     0.5588    0.7600    0.6441        25

    accuracy                         0.6717       198
   macro avg     0.5657    0.6891    0.5740       198
weighted avg     0.7562    0.6717    0.6906       198

Confusion matrix:
 [[ 1  0  0  1  0]
 [ 5 48  7  6 11]
 [ 5  8 43 11  4]
 [ 0  0  1 22  0]
 [ 2  1  1  2 19]]
F1-macro: 0.5740
Accuracy: 0.6717

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.5361    0.5149    0.5253       101
           1     0.6593    0.4255    0.5172       141
           2     0.6346    0.4818    0.5477       137
           3     0.3621    0.5250    0.4286        80
           4     0.6280    0.9115    0.7437       113

    accuracy                         0.5647       572
   macro avg     0.5640    0.5717    0.5525       572
weighted avg     0.5839    0.5647    0.5583       572

Confusion matrix:
 [[ 52  11   8  18  12]
 [ 16  60  17  29  19]
 [ 17   7  66  26  21]
 [  7  11  11  42   9]
 [  5   2   2   1 103]]
F1-macro: 0.5525
Accuracy: 0.5647

##### SEED = 11 #####


=== VAL ===
              precision    recall  f1-score   support

           0     0.0000    0.0000    0.0000         2
           1     0.9464    0.6883    0.7970        77
           2     0.9153    0.7606    0.8308        71
           3     0.5500    0.9565    0.6984        23
           4     0.5676    0.8400    0.6774        25

    accuracy                         0.7576       198
   macro avg     0.5959    0.6491    0.6007       198
weighted avg     0.8318    0.7576    0.7745       198

Confusion matrix:
 [[ 0  1  1  0  0]
 [ 4 53  2  4 14]
 [ 1  2 54 12  2]
 [ 0  0  1 22  0]
 [ 1  0  1  2 21]]
F1-macro: 0.6007
Accuracy: 0.7576

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.4956    0.5545    0.5234       101
           1     0.7470    0.4397    0.5536       141
           2     0.7590    0.4599    0.5727       137
           3     0.3481    0.5875    0.4372        80
           4     0.6456    0.9027    0.7528       113

    accuracy                         0.5769       572
   macro avg     0.5991    0.5888    0.5679       572
weighted avg     0.6297    0.5769    0.5759       572

Confusion matrix:
 [[ 56   5   5  24  11]
 [ 20  62  10  28  21]
 [ 22   6  63  32  14]
 [ 11   7   5  47  10]
 [  4   3   0   4 102]]
F1-macro: 0.5679
Accuracy: 0.5769

=== VAL ===
              precision    recall  f1-score   support

           0     0.0000    0.0000    0.0000         2
           1     0.8889    0.8312    0.8591        77
           2     0.8788    0.8169    0.8467        71
           3     0.6667    0.8696    0.7547        23
           4     0.6667    0.7200    0.6923        25

    accuracy                         0.8081       198
   macro avg     0.6202    0.6475    0.6306       198
weighted avg     0.8224    0.8081    0.8128       198

Confusion matrix:
 [[ 0  1  1  0  0]
 [ 2 64  2  2  7]
 [ 0  4 58  7  2]
 [ 0  1  2 20  0]
 [ 1  2  3  1 18]]
F1-macro: 0.6306
Accuracy: 0.8081

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.5375    0.4257    0.4751       101
           1     0.5938    0.5390    0.5651       141
           2     0.5809    0.5766    0.5788       137
           3     0.5405    0.5000    0.5195        80
           4     0.6688    0.9115    0.7715       113

    accuracy                         0.5962       572
   macro avg     0.5843    0.5906    0.5820       572
weighted avg     0.5881    0.5962    0.5869       572

Confusion matrix:
 [[ 43  17  23   8  10]
 [ 15  76  22  11  17]
 [ 14  12  79  14  18]
 [  6  17  11  40   6]
 [  2   6   1   1 103]]
F1-macro: 0.5820
Accuracy: 0.5962

=== VAL ===
              precision    recall  f1-score   support

           0     0.0000    0.0000    0.0000         2
           1     0.9054    0.8701    0.8874        77
           2     0.8955    0.8451    0.8696        71
           3     0.7333    0.9565    0.8302        23
           4     0.7200    0.7200    0.7200        25

    accuracy                         0.8434       198
   macro avg     0.6509    0.6783    0.6614       198
weighted avg     0.8493    0.8434    0.8443       198

Confusion matrix:
 [[ 0  1  1  0  0]
 [ 1 67  2  1  6]
 [ 0  4 60  6  1]
 [ 0  0  1 22  0]
 [ 1  2  3  1 18]]
F1-macro: 0.6614
Accuracy: 0.8434

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.6000    0.4455    0.5114       101
           1     0.6429    0.5745    0.6067       141
           2     0.5556    0.6569    0.6020       137
           3     0.5821    0.4875    0.5306        80
           4     0.7183    0.9027    0.8000       113

    accuracy                         0.6241       572
   macro avg     0.6198    0.6134    0.6101       572
weighted avg     0.6208    0.6241    0.6163       572

Confusion matrix:
 [[ 45  12  27   9   8]
 [ 12  81  25   9  14]
 [ 12  12  90  10  13]
 [  4  16  16  39   5]
 [  2   5   4   0 102]]
F1-macro: 0.6101
Accuracy: 0.6241

/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1281: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1296: FutureWarning: Using the 'liblinear' solver for multiclass classification is deprecated. An error will be raised in 1.8. Either use another solver which supports the multinomial loss or wrap the estimator in a OneVsRestClassifier to keep applying a one-versus-rest scheme.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1305: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 32.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1281: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1296: FutureWarning: Using the 'liblinear' solver for multiclass classification is deprecated. An error will be raised in 1.8. Either use another solver which supports the multinomial loss or wrap the estimator in a OneVsRestClassifier to keep applying a one-versus-rest scheme.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1305: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 32.
  warnings.warn(

=== VAL ===
              precision    recall  f1-score   support

           0     0.0000    0.0000    0.0000         2
           1     0.8415    0.8961    0.8679        77
           2     0.8429    0.8310    0.8369        71
           3     0.7500    0.7826    0.7660        23
           4     0.9048    0.7600    0.8261        25

    accuracy                         0.8333       198
   macro avg     0.6678    0.6539    0.6594       198
weighted avg     0.8308    0.8333    0.8309       198

Confusion matrix:
 [[ 0  1  1  0  0]
 [ 1 69  4  1  2]
 [ 0  8 59  4  0]
 [ 0  2  3 18  0]
 [ 0  2  3  1 19]]
F1-macro: 0.6594
Accuracy: 0.8333

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.7857    0.3267    0.4615       101
           1     0.5667    0.6028    0.5842       141
           2     0.5185    0.7153    0.6012       137
           3     0.6122    0.3750    0.4651        80
           4     0.7042    0.8850    0.7843       113

    accuracy                         0.6049       572
   macro avg     0.6375    0.5810    0.5793       572
weighted avg     0.6274    0.6049    0.5895       572

Confusion matrix:
 [[ 33  21  33   6   8]
 [  3  85  35   7  11]
 [  3  14  98   6  16]
 [  1  22  20  30   7]
 [  2   8   3   0 100]]
F1-macro: 0.5793
Accuracy: 0.6049

=== VAL ===
              precision    recall  f1-score   support

           0     0.0000    0.0000    0.0000         2
           1     0.8491    0.5844    0.6923        77
           2     0.9038    0.6620    0.7642        71
           3     0.5000    0.9565    0.6567        23
           4     0.4878    0.8000    0.6061        25

    accuracy                         0.6768       198
   macro avg     0.5481    0.6006    0.5439       198
weighted avg     0.7740    0.6768    0.6961       198

Confusion matrix:
 [[ 0  1  1  0  0]
 [ 6 45  3  5 18]
 [ 1  6 47 14  3]
 [ 0  0  1 22  0]
 [ 1  1  0  3 20]]
F1-macro: 0.5439
Accuracy: 0.6768

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.4914    0.5644    0.5253       101
           1     0.6300    0.4468    0.5228       141
           2     0.6900    0.5036    0.5823       137
           3     0.4111    0.4625    0.4353        80
           4     0.6145    0.9027    0.7312       113

    accuracy                         0.5734       572
   macro avg     0.5674    0.5760    0.5594       572
weighted avg     0.5862    0.5734    0.5664       572

Confusion matrix:
 [[ 57  10   5  15  14]
 [ 28  63  16  13  21]
 [ 18   7  69  23  20]
 [  8  17   9  37   9]
 [  5   3   1   2 102]]
F1-macro: 0.5594
Accuracy: 0.5734

##### SEED = 13 #####


=== VAL ===
              precision    recall  f1-score   support

           0     0.1429    0.5000    0.2222         2
           1     0.9231    0.7792    0.8451        77
           2     0.9623    0.7183    0.8226        71
           3     0.5500    0.9565    0.6984        23
           4     0.6364    0.8400    0.7241        25

    accuracy                         0.7828       198
   macro avg     0.6429    0.7588    0.6625       198
weighted avg     0.8497    0.7828    0.7984       198

Confusion matrix:
 [[ 1  0  1  0  0]
 [ 2 60  0  3 12]
 [ 3  4 51 13  0]
 [ 0  0  1 22  0]
 [ 1  1  0  2 21]]
F1-macro: 0.6625
Accuracy: 0.7828

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.6992    0.8515    0.7679       101
           1     0.7975    0.4468    0.5727       141
           2     0.7033    0.4672    0.5614       137
           3     0.3721    0.6000    0.4593        80
           4     0.6867    0.9115    0.7833       113

    accuracy                         0.6364       572
   macro avg     0.6517    0.6554    0.6289       572
weighted avg     0.6762    0.6364    0.6302       572

Confusion matrix:
 [[ 86   0   2   8   5]
 [ 17  63  12  31  18]
 [ 10   6  64  41  16]
 [  8   7   9  48   8]
 [  2   3   4   1 103]]
F1-macro: 0.6289
Accuracy: 0.6364

=== VAL ===
              precision    recall  f1-score   support

           0     0.5000    0.5000    0.5000         2
           1     0.8800    0.8571    0.8684        77
           2     0.9077    0.8310    0.8676        71
           3     0.6923    0.7826    0.7347        23
           4     0.7333    0.8800    0.8000        25

    accuracy                         0.8384       198
   macro avg     0.7427    0.7701    0.7542       198
weighted avg     0.8458    0.8384    0.8402       198

Confusion matrix:
 [[ 1  0  1  0  0]
 [ 0 66  2  1  8]
 [ 1  4 59  7  0]
 [ 0  4  1 18  0]
 [ 0  1  2  0 22]]
F1-macro: 0.7542
Accuracy: 0.8384

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.7822    0.7822    0.7822       101
           1     0.6957    0.5674    0.6250       141
           2     0.6207    0.6569    0.6383       137
           3     0.5588    0.4750    0.5135        80
           4     0.7133    0.9027    0.7969       113

    accuracy                         0.6801       572
   macro avg     0.6741    0.6768    0.6712       572
weighted avg     0.6773    0.6801    0.6743       572

Confusion matrix:
 [[ 79   5   8   5   4]
 [  7  80  27  13  14]
 [  6  11  90  12  18]
 [  7  13  17  38   5]
 [  2   6   3   0 102]]
F1-macro: 0.6712
Accuracy: 0.6801

=== VAL ===
              precision    recall  f1-score   support

           0     0.5000    0.5000    0.5000         2
           1     0.8625    0.8961    0.8790        77
           2     0.9091    0.8451    0.8759        71
           3     0.7391    0.7391    0.7391        23
           4     0.7407    0.8000    0.7692        25

    accuracy                         0.8434       198
   macro avg     0.7503    0.7561    0.7527       198
weighted avg     0.8458    0.8434    0.8439       198

Confusion matrix:
 [[ 1  0  1  0  0]
 [ 0 69  1  0  7]
 [ 1  4 60  6  0]
 [ 0  4  2 17  0]
 [ 0  3  2  0 20]]
F1-macro: 0.7527
Accuracy: 0.8434

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.7921    0.7921    0.7921       101
           1     0.6930    0.5603    0.6196       141
           2     0.5879    0.7080    0.6424       137
           3     0.5893    0.4125    0.4853        80
           4     0.7500    0.9027    0.8193       113

    accuracy                         0.6836       572
   macro avg     0.6824    0.6751    0.6717       572
weighted avg     0.6821    0.6836    0.6762       572

Confusion matrix:
 [[ 80   5  10   4   2]
 [  5  79  33  11  13]
 [  6  12  97   8  14]
 [  8  12  22  33   5]
 [  2   6   3   0 102]]
F1-macro: 0.6717
Accuracy: 0.6836

=== VAL ===
              precision    recall  f1-score   support

           0     1.0000    0.5000    0.6667         2
           1     0.8519    0.8961    0.8734        77
           2     0.8732    0.8732    0.8732        71
           3     0.7895    0.6522    0.7143        23
           4     0.7692    0.8000    0.7843        25

    accuracy                         0.8434       198
   macro avg     0.8568    0.7443    0.7824       198
weighted avg     0.8433    0.8434    0.8415       198

Confusion matrix:
 [[ 1  0  1  0  0]
 [ 0 69  3  0  5]
 [ 0  5 62  4  0]
 [ 0  4  3 15  1]
 [ 0  3  2  0 20]]
F1-macro: 0.7824
Accuracy: 0.8434

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.8333    0.6436    0.7263       101
           1     0.6087    0.5957    0.6022       141
           2     0.5385    0.7153    0.6144       137
           3     0.6512    0.3500    0.4553        80
           4     0.7786    0.9027    0.8361       113

    accuracy                         0.6591       572
   macro avg     0.6821    0.6415    0.6468       572
weighted avg     0.6710    0.6591    0.6527       572

Confusion matrix:
 [[ 65  13  18   4   1]
 [  3  84  39   4  11]
 [  4  16  98   7  12]
 [  4  19  24  28   5]
 [  2   6   3   0 102]]
F1-macro: 0.6468
Accuracy: 0.6591

=== VAL ===
              precision    recall  f1-score   support

           0     0.0667    0.5000    0.1176         2
           1     0.8806    0.7662    0.8194        77
           2     0.9216    0.6620    0.7705        71
           3     0.5588    0.8261    0.6667        23
           4     0.6452    0.8000    0.7143        25

    accuracy                         0.7374       198
   macro avg     0.6146    0.7109    0.6177       198
weighted avg     0.8200    0.7374    0.7638       198

Confusion matrix:
 [[ 1  0  1  0  0]
 [ 5 59  1  2 10]
 [ 7  4 47 13  0]
 [ 0  2  1 19  1]
 [ 2  2  1  0 20]]
F1-macro: 0.6177
Accuracy: 0.7374

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.5906    0.8713    0.7040       101
           1     0.7500    0.4468    0.5600       141
           2     0.6392    0.4526    0.5299       137
           3     0.4318    0.4750    0.4524        80
           4     0.6753    0.9204    0.7790       113

    accuracy                         0.6206       572
   macro avg     0.6174    0.6332    0.6051       572
weighted avg     0.6361    0.6206    0.6064       572

Confusion matrix:
 [[ 88   1   2   5   5]
 [ 28  63  18  14  18]
 [ 17   7  62  30  21]
 [ 12  11  13  38   6]
 [  4   2   2   1 104]]
F1-macro: 0.6051
Accuracy: 0.6206

##### SEED = 17 #####


=== VAL ===
              precision    recall  f1-score   support

           0     0.0000    0.0000    0.0000         2
           1     0.9104    0.7922    0.8472        77
           2     0.9574    0.6338    0.7627        71
           3     0.4510    1.0000    0.6216        23
           4     0.8462    0.8800    0.8627        25

    accuracy                         0.7626       198
   macro avg     0.6330    0.6612    0.6189       198
weighted avg     0.8566    0.7626    0.7841       198

Confusion matrix:
 [[ 0  1  0  1  0]
 [ 4 61  2  6  4]
 [ 2  5 45 19  0]
 [ 0  0  0 23  0]
 [ 1  0  0  2 22]]
F1-macro: 0.6189
Accuracy: 0.7626

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.6438    0.4653    0.5402       101
           1     0.7558    0.4610    0.5727       141
           2     0.7000    0.4088    0.5161       137
           3     0.3152    0.6500    0.4245        80
           4     0.6131    0.9115    0.7331       113

    accuracy                         0.5647       572
   macro avg     0.6056    0.5793    0.5573       572
weighted avg     0.6328    0.5647    0.5644       572

Confusion matrix:
 [[ 47   4   7  29  14]
 [ 11  65  10  34  21]
 [  8   7  56  46  20]
 [  5   7   6  52  10]
 [  2   3   1   4 103]]
F1-macro: 0.5573
Accuracy: 0.5647

=== VAL ===

/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1281: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1296: FutureWarning: Using the 'liblinear' solver for multiclass classification is deprecated. An error will be raised in 1.8. Either use another solver which supports the multinomial loss or wrap the estimator in a OneVsRestClassifier to keep applying a one-versus-rest scheme.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1305: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 32.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1281: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1296: FutureWarning: Using the 'liblinear' solver for multiclass classification is deprecated. An error will be raised in 1.8. Either use another solver which supports the multinomial loss or wrap the estimator in a OneVsRestClassifier to keep applying a one-versus-rest scheme.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1305: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 32.
  warnings.warn(

              precision    recall  f1-score   support

           0     0.0000    0.0000    0.0000         2
           1     0.9315    0.8831    0.9067        77
           2     0.9143    0.9014    0.9078        71
           3     0.7241    0.9130    0.8077        23
           4     0.9200    0.9200    0.9200        25

    accuracy                         0.8889       198
   macro avg     0.6980    0.7235    0.7084       198
weighted avg     0.8904    0.8889    0.8881       198

Confusion matrix:
 [[ 0  1  0  0  1]
 [ 1 68  5  2  1]
 [ 0  3 64  4  0]
 [ 0  1  1 21  0]
 [ 0  0  0  2 23]]
F1-macro: 0.7084
Accuracy: 0.8889

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.7000    0.4158    0.5217       101
           1     0.6783    0.5532    0.6094       141
           2     0.5641    0.6423    0.6007       137
           3     0.4819    0.5000    0.4908        80
           4     0.6456    0.9027    0.7528       113

    accuracy                         0.6119       572
   macro avg     0.6140    0.6028    0.5951       572
weighted avg     0.6208    0.6119    0.6036       572

Confusion matrix:
 [[ 42  11  24  12  12]
 [  7  78  24  12  20]
 [  6   7  88  17  19]
 [  3  14  18  40   5]
 [  2   5   2   2 102]]
F1-macro: 0.5951
Accuracy: 0.6119

=== VAL ===
              precision    recall  f1-score   support

           0     0.0000    0.0000    0.0000         2
           1     0.9200    0.8961    0.9079        77
           2     0.8904    0.9155    0.9028        71
           3     0.7857    0.9565    0.8627        23
           4     1.0000    0.8400    0.9130        25

    accuracy                         0.8939       198
   macro avg     0.7192    0.7216    0.7173       198
weighted avg     0.8946    0.8939    0.8923       198

Confusion matrix:
 [[ 0  1  1  0  0]
 [ 1 69  5  2  0]
 [ 0  4 65  2  0]
 [ 0  0  1 22  0]
 [ 0  1  1  2 21]]
F1-macro: 0.7173
Accuracy: 0.8939

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.7000    0.4158    0.5217       101
           1     0.6752    0.5603    0.6124       141
           2     0.5246    0.7007    0.6000       137
           3     0.5211    0.4625    0.4901        80
           4     0.7234    0.9027    0.8031       113

    accuracy                         0.6224       572
   macro avg     0.6289    0.6084    0.6055       572
weighted avg     0.6315    0.6224    0.6140       572

Confusion matrix:
 [[ 42   9  31   9  10]
 [  6  79  33  12  11]
 [  6   9  96  13  13]
 [  4  14  20  37   5]
 [  2   6   3   0 102]]
F1-macro: 0.6055
Accuracy: 0.6224

=== VAL ===
              precision    recall  f1-score   support

           0     0.0000    0.0000    0.0000         2
           1     0.8974    0.9091    0.9032        77
           2     0.8904    0.9155    0.9028        71
           3     0.8077    0.9130    0.8571        23
           4     1.0000    0.8000    0.8889        25

    accuracy                         0.8889       198
   macro avg     0.7191    0.7075    0.7104       198
weighted avg     0.8884    0.8889    0.8868       198

Confusion matrix:
 [[ 0  1  1  0  0]
 [ 1 70  4  2  0]
 [ 0  4 65  2  0]
 [ 0  1  1 21  0]
 [ 0  2  2  1 20]]
F1-macro: 0.7104
Accuracy: 0.8889

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.7400    0.3663    0.4901       101
           1     0.5822    0.6028    0.5923       141
           2     0.5238    0.7226    0.6074       137
           3     0.6078    0.3875    0.4733        80
           4     0.7500    0.9027    0.8193       113

    accuracy                         0.6189       572
   macro avg     0.6408    0.5964    0.5965       572
weighted avg     0.6328    0.6189    0.6061       572

Confusion matrix:
 [[ 37  17  30  10   7]
 [  5  85  37   3  11]
 [  4  16  99   7  11]
 [  2  22  20  31   5]
 [  2   6   3   0 102]]
F1-macro: 0.5965
Accuracy: 0.6189

=== VAL ===
              precision    recall  f1-score   support

           0     0.0714    0.5000    0.1250         2
           1     0.8871    0.7143    0.7914        77
           2     0.8913    0.5775    0.7009        71
           3     0.4490    0.9565    0.6111        23
           4     0.7778    0.8400    0.8077        25

    accuracy                         0.7071       198
   macro avg     0.6153    0.7177    0.6072       198
weighted avg     0.8157    0.7071    0.7333       198

Confusion matrix:
 [[ 1  1  0  0  0]
 [ 6 55  5  5  6]
 [ 5  5 41 20  0]
 [ 1  0  0 22  0]
 [ 1  1  0  2 21]]
F1-macro: 0.6072
Accuracy: 0.7071

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.4741    0.5446    0.5069       101
           1     0.6061    0.4255    0.5000       141
           2     0.6484    0.4307    0.5175       137
           3     0.3714    0.4875    0.4216        80
           4     0.6335    0.9027    0.7445       113

    accuracy                         0.5507       572
   macro avg     0.5467    0.5582    0.5381       572
weighted avg     0.5655    0.5507    0.5428       572

Confusion matrix:
 [[ 55  11   4  17  14]
 [ 25  60  18  21  17]
 [ 23   8  59  27  20]
 [  8  16   9  39   8]
 [  5   4   1   1 102]]
F1-macro: 0.5381
Accuracy: 0.5507

##### SEED = 19 #####


=== VAL ===
              precision    recall  f1-score   support

           0     0.0000    0.0000    0.0000         2
           1     0.9375    0.7792    0.8511        77
           2     0.8793    0.7183    0.7907        71
           3     0.5385    0.9130    0.6774        23
           4     0.6667    0.8800    0.7586        25

    accuracy                         0.7778       198
   macro avg     0.6044    0.6581    0.6156       198
weighted avg     0.8266    0.7778    0.7890       198

Confusion matrix:
 [[ 0  0  0  1  1]
 [ 2 60  7  4  4]
 [ 2  1 51 12  5]
 [ 0  1  0 21  1]
 [ 0  2  0  1 22]]
F1-macro: 0.6156
Accuracy: 0.7778

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.6667    0.8317    0.7401       101
           1     0.7831    0.4610    0.5804       141
           2     0.7444    0.4891    0.5903       137
           3     0.3740    0.5750    0.4532        80
           4     0.6733    0.8938    0.7681       113

    accuracy                         0.6346       572
   macro avg     0.6483    0.6501    0.6264       572
weighted avg     0.6744    0.6346    0.6302       572

Confusion matrix:
 [[ 84   2   2   8   5]
 [ 17  65  10  29  20]
 [ 13   6  67  36  15]
 [  9   7   9  46   9]
 [  3   3   2   4 101]]
F1-macro: 0.6264
Accuracy: 0.6346

=== VAL ===
              precision    recall  f1-score   support

           0     0.0000    0.0000    0.0000         2
           1     0.8767    0.8312    0.8533        77
           2     0.8429    0.8310    0.8369        71
           3     0.7200    0.7826    0.7500        23
           4     0.8077    0.8400    0.8235        25

    accuracy                         0.8182       198
   macro avg     0.6495    0.6570    0.6527       198
weighted avg     0.8288    0.8182    0.8230       198

Confusion matrix:
 [[ 0  1  0  0  1]
 [ 2 64  7  2  2]
 [ 2  4 59  5  1]
 [ 0  2  2 18  1]
 [ 0  2  2  0 21]]
F1-macro: 0.6527
Accuracy: 0.8182

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.7670    0.7822    0.7745       101
           1     0.7232    0.5745    0.6403       141
           2     0.6027    0.6423    0.6219       137
           3     0.5797    0.5000    0.5369        80
           4     0.7254    0.9115    0.8078       113

    accuracy                         0.6836       572
   macro avg     0.6796    0.6821    0.6763       572
weighted avg     0.6824    0.6836    0.6782       572

Confusion matrix:
 [[ 79   6   9   4   3]
 [  6  81  28  12  14]
 [  8  10  88  13  18]
 [  8  11  17  40   4]
 [  2   4   4   0 103]]
F1-macro: 0.6763
Accuracy: 0.6836

=== VAL ===
              precision    recall  f1-score   support

           0     0.0000    0.0000    0.0000         2
           1     0.8684    0.8571    0.8627        77
           2     0.8194    0.8310    0.8252        71
           3     0.6957    0.6957    0.6957        23
           4     0.9130    0.8400    0.8750        25

    accuracy                         0.8182       198
   macro avg     0.6593    0.6448    0.6517       198
weighted avg     0.8277    0.8182    0.8227       198

Confusion matrix:
 [[ 0  1  0  0  1]
 [ 2 66  7  2  0]
 [ 2  5 59  5  0]
 [ 0  2  4 16  1]
 [ 0  2  2  0 21]]
F1-macro: 0.6517
Accuracy: 0.8182

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.7596    0.7822    0.7707       101
           1     0.7411    0.5887    0.6561       141
           2     0.5780    0.7299    0.6452       137
           3     0.6458    0.3875    0.4844        80
           4     0.7481    0.8938    0.8145       113

    accuracy                         0.6888       572
   macro avg     0.6945    0.6764    0.6742       572
weighted avg     0.6934    0.6888    0.6810       572

Confusion matrix:
 [[ 79   5  11   3   3]
 [  5  83  32   8  13]
 [  9   9 100   6  13]
 [  9  11  24  31   5]
 [  2   4   6   0 101]]
F1-macro: 0.6742
Accuracy: 0.6888

=== VAL ===
              precision    recall  f1-score   support

           0     0.0000    0.0000    0.0000         2
           1     0.8272    0.8701    0.8481        77
           2     0.8514    0.8873    0.8690        71
           3     0.7368    0.6087    0.6667        23
           4     0.8696    0.8000    0.8333        25

    accuracy                         0.8283       198
   macro avg     0.6570    0.6332    0.6434       198
weighted avg     0.8223    0.8283    0.8241       198

Confusion matrix:
 [[ 0  1  0  0  1]
 [ 1 67  6  2  1]
 [ 0  5 63  3  0]
 [ 0  4  4 14  1]
 [ 0  4  1  0 20]]
F1-macro: 0.6434
Accuracy: 0.8283

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.8171    0.6634    0.7322       101
           1     0.6449    0.6312    0.6380       141
           2     0.5562    0.7226    0.6286       137
           3     0.6383    0.3750    0.4724        80
           4     0.7953    0.8938    0.8417       113

    accuracy                         0.6748       572
   macro avg     0.6904    0.6572    0.6626       572
weighted avg     0.6828    0.6748    0.6695       572

Confusion matrix:
 [[ 67  10  18   4   2]
 [  4  89  33   6   9]
 [  4  16  99   7  11]
 [  5  17  24  30   4]
 [  2   6   4   0 101]]
F1-macro: 0.6626
Accuracy: 0.6748

=== VAL ===
              precision    recall  f1-score   support

           0     0.0000    0.0000    0.0000         2
           1     0.9123    0.6753    0.7761        77
           2     0.8448    0.6901    0.7597        71
           3     0.4762    0.8696    0.6154        23
           4     0.7143    0.8000    0.7547        25

    accuracy                         0.7121       198
   macro avg     0.5895    0.6070    0.5812       198
weighted avg     0.8032    0.7121    0.7410       198

Confusion matrix:
 [[ 0  0  0  1  1]
 [ 5 52  6  9  5]
 [ 6  4 49 11  1]
 [ 1  0  1 20  1]
 [ 1  1  2  1 20]]
F1-macro: 0.5812
Accuracy: 0.7121

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.5621    0.8515    0.6772       101
           1     0.7209    0.4397    0.5463       141
           2     0.6632    0.4599    0.5431       137
           3     0.4368    0.4750    0.4551        80
           4     0.6755    0.9027    0.7727       113

    accuracy                         0.6136       572
   macro avg     0.6117    0.6257    0.5989       572
weighted avg     0.6303    0.6136    0.6006       572

Confusion matrix:
 [[ 86   2   2   7   4]
 [ 24  62  16  18  21]
 [ 25   9  63  22  18]
 [ 13  10  13  38   6]
 [  5   3   1   2 102]]
F1-macro: 0.5989
Accuracy: 0.6136

=====================================
Resumen Multi-Seed (95% CI)
=====================================
             model  val_f1_macro_mean  val_f1_macro_std  val_f1_macro_CI_low  val_f1_macro_CI_high  test_f1_macro_mean  test_f1_macro_std  test_f1_macro_CI_low  test_f1_macro_CI_high
           sgd_log           0.704571          0.045734             0.664483              0.744658            0.635265           0.034575              0.604959               0.665571
        linear_svm           0.691243          0.049450             0.647898              0.734588            0.626857           0.043943              0.588339               0.665375
passive_aggressive           0.689503          0.058110             0.638567              0.740439            0.614215           0.037882              0.581010               0.647420
        logreg_ovr           0.621616          0.023852             0.600708              0.642524            0.587858           0.036573              0.555800               0.619916
     complement_nb           0.584789          0.029115             0.559268              0.610309            0.570786           0.029560              0.544875               0.596697

/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1281: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1296: FutureWarning: Using the 'liblinear' solver for multiclass classification is deprecated. An error will be raised in 1.8. Either use another solver which supports the multinomial loss or wrap the estimator in a OneVsRestClassifier to keep applying a one-versus-rest scheme.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1305: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 32.
  warnings.warn(

In [28]:
df_summary

,model,val_f1_macro_mean,val_f1_macro_std,val_f1_macro_CI_low,val_f1_macro_CI_high,test_f1_macro_mean,test_f1_macro_std,test_f1_macro_CI_low,test_f1_macro_CI_high
4,sgd_log,0.704571,0.045734,0.664483,0.744658,0.635265,0.034575,0.604959,0.665571
1,linear_svm,0.691243,0.049450,0.647898,0.734588,0.626857,0.043943,0.588339,0.665375
3,passive_aggressive,0.689503,0.058110,0.638567,0.740439,0.614215,0.037882,0.581010,0.647420
2,logreg_ovr,0.621616,0.023852,0.600708,0.642524,0.587858,0.036573,0.555800,0.619916
0,complement_nb,0.584789,0.029115,0.559268,0.610309,0.570786,0.029560,0.544875,0.596697

In [25]:
df_summary

,model,val_f1_macro_mean,val_f1_macro_std,val_f1_macro_CI_low,val_f1_macro_CI_high,test_f1_macro_mean,test_f1_macro_std,test_f1_macro_CI_low,test_f1_macro_CI_high
3,passive_aggressive,0.986146,0.004920,0.981834,0.990459,0.573849,0.011785,0.563520,0.584179
1,linear_svm,0.982166,0.003895,0.978752,0.985580,0.625455,0.006698,0.619584,0.631326
4,sgd_log,0.975202,0.004870,0.970934,0.979471,0.627862,0.006536,0.622132,0.633591
2,logreg_ovr,0.964467,0.006119,0.959103,0.969830,0.638500,0.001303,0.637358,0.639642
0,complement_nb,0.931495,0.014556,0.918736,0.944254,0.626433,0.004067,0.622868,0.629998

## Remasking new test and test again

In [29]:
def load_lexicon_from_jsonl(path="lexicon/lexicon.jsonl"):
    """
    Lee lexicon/lexicon.jsonl y devuelve un dict Python con el lexicon.
    Asume que la primera línea contiene el lexicon (o un campo 'lexicon').
    """
    df_lex = load_jsonl(path)
    if len(df_lex) == 0:
        raise RuntimeError(f"No se encontró ninguna línea en {path}")

    row0 = df_lex.iloc[0]

    # Caso 1: columna explícita llamada 'lexicon'
    if "lexicon" in df_lex.columns and isinstance(row0["lexicon"], dict):
        return row0["lexicon"]

    # Caso 2: solo una columna y esa columna contiene el dict
    if len(df_lex.columns) == 1:
        col = df_lex.columns[0]
        if isinstance(row0[col], dict):
            return row0[col]

    # Fallback: convertir la fila entera a dict
    maybe_dict = row0.to_dict()
    if isinstance(maybe_dict, dict):
        return maybe_dict

    raise RuntimeError("Formato de lexicon.jsonl no reconocido.")

In [30]:
import re
import numpy as np
import pandas as pd

def build_lexicon_entries(lexicon, placeholder_keys=("TARGET", "SLUR")):
    """
    Flatten the lexicon into a list of entries:

        {
            "phrase": original phrase (str),
            "pattern": compiled regex,
            "placeholder": "[TARGET:GENDER_WOMEN]",
            "group": "GENDER_WOMEN",
            "kind": "TARGET" or "SLUR",
        }

    - Ignores *very* short phrases (len < 2) to avoid noise like "u".
    - For “normal word” phrases (letters/digits/spaces/'/-), we add word
      boundaries, so we match complete words, not substrings inside words.
    """
    entries = []

    for kind in placeholder_keys:  # "TARGET", "SLUR"
        if kind not in lexicon:
            continue

        by_axis = lexicon[kind]   # e.g. gender / ethnicity / ...
        for axis, by_group in by_axis.items():
            for group_code, phrase_dict in by_group.items():
                for phrase in phrase_dict.keys():
                    if not phrase:
                        continue

                    phrase_stripped = phrase.strip()
                    if len(phrase_stripped) < 2:
                        # skip ultra-short stuff: "u", etc.
                        continue

                    # "Normal word" (letters/digits/space/'/-) → use word boundaries
                    if re.fullmatch(r"[0-9A-Za-z' \-]+", phrase_stripped):
                        pattern = re.compile(
                            r"\b" + re.escape(phrase_stripped) + r"\b",
                            flags=re.IGNORECASE,
                        )
                    else:
                        # weird chars / emoji / punctuation → plain literal match
                        pattern = re.compile(re.escape(phrase_stripped), flags=re.IGNORECASE)

                    entries.append({
                        "phrase": phrase_stripped,
                        "pattern": pattern,
                        "placeholder": f"[{kind}:{group_code}]",
                        "group": group_code,
                        "kind": kind,
                    })

    # Longer phrases first (reduces conflicts: "black women" before "black")
    entries.sort(key=lambda e: len(e["phrase"]), reverse=True)
    return entries

In [31]:
import re

def mask_text_with_lexicon(text, entries):
    if not isinstance(text, str) or not text:
        return text, []

    n = len(text)
    occupied = [False] * n
    spans = []   # (start, end, placeholder, group)
    groups = set()
    seen_placeholders = set()

    for e in entries:
        pattern = e["pattern"]

        for m in pattern.finditer(text):
            start, end = m.span()
            if start == end:
                continue

            # ya cubierto por un span más largo
            if any(occupied[i] for i in range(start, end)):
                continue

            # NUEVO: solo una vez por placeholder
            if e["placeholder"] in seen_placeholders:
                continue

            spans.append((start, end, e["placeholder"], e["group"]))
            for i in range(start, end):
                occupied[i] = True
            groups.add(e["group"])
            seen_placeholders.add(e["placeholder"])

    if not spans:
        return text, []

    spans.sort(key=lambda x: x[0])

    out = []
    last = 0
    for start, end, placeholder, _group in spans:
        out.append(text[last:start])
        out.append(placeholder)
        last = end
    out.append(text[last:])

    masked_text = "".join(out)
    return masked_text, sorted(groups)

In [32]:
def remask_df_keep_minimal(df, lexicon_path="lexicon/lexicon.jsonl"):
    cols_needed = ["text", "text_masked", "predicted_hate_category"]
    missing = [c for c in cols_needed if c not in df.columns]
    if missing:
        raise KeyError(f"Faltan columnas en df: {missing}")

    df_out = df[cols_needed].copy()

    lexicon = load_lexicon_from_jsonl(lexicon_path)
    entries = build_lexicon_entries(lexicon)

    mask_missing = df_out["text_masked"].isna() | df_out["text_masked"].astype(str).str.strip().eq("")
    n_to_remask = mask_missing.sum()
    print(f"Remasking {n_to_remask} filas con text_masked vacío/NaN...")

    for idx in df_out[mask_missing].index:
        original_text = df_out.at[idx, "text"]
        masked_text, groups = mask_text_with_lexicon(original_text, entries)

        if isinstance(masked_text, str):
            df_out.at[idx, "text_masked"] = f'"""{masked_text}"""'
        else:
            df_out.at[idx, "text_masked"] = masked_text

    return df_out

In [33]:
# df_merged es tu dataframe grande con muchas columnas
df_min_remasked = remask_df_keep_minimal(
    df_test_aug,
    lexicon_path="lexicon/lexicon.jsonl"
)

print(df_min_remasked.head())
print(df_min_remasked.columns)  # solo text, text_masked, predicted_hate_category

Remasking 468 filas con text_masked vacío/NaN...
                                                text  \
0                                   Fck those niggas
1  @user . Linda Sarsour should already be in jai...
2  Women really should start carrying guns around...
3  @mike_pence @user Just shut your mouth and put...
4  Please let that bitch go. Every man done ran i...

                                         text_masked predicted_hate_category
0                  """Fck those [SLUR:RACE_BLACK]"""             hate_origin
1  """[MENTION] . Linda Sarsour should already be...             hate_gender
2  """[GENDER_WOMEN] really should start carrying...             hate_gender
3  """[MENTION] [MENTION] Just shut your mouth an...          hate_sexuality
4  """Please let that [SLUR:GENDER_WOMEN] go. Eve...             hate_gender
Index(['text', 'text_masked', 'predicted_hate_category'], dtype='object')

In [34]:
df_min_remasked

,text,text_masked,predicted_hate_category
0,Fck those niggas,"""""""Fck those [SLUR:RACE_BLACK]""""""",hate_origin
1,@user . Linda Sarsour should already be in jai...,"""""""[MENTION] . Linda Sarsour should already be...",hate_gender
2,Women really should start carrying guns around...,"""""""[GENDER_WOMEN] really should start carrying...",hate_gender
3,@mike_pence @user Just shut your mouth and put...,"""""""[MENTION] [MENTION] Just shut your mouth an...",hate_sexuality
4,Please let that bitch go. Every man done ran i...,"""""""Please let that [SLUR:GENDER_WOMEN] go. Eve...",hate_gender
...,...,...,...
567,@user @user @user @user @user @user Saw this t...,"""""""[SLUR:GENDER_MEN] [SLUR:GENDER_WOMEN] [SLUR...",hate_disability
568,okay but really why are Americans so fucking m...,"""""""okay but really why are [TARGET:NATIONAL_OR...",hate_disability
569,@user what\u2019s wrong with you you fucking r...,"""""""[SLUR:GENDER_MEN] what\u2019s wrong with yo...",hate_disability
570,@user @user @user @user Hell I'd say enticed t...,"""""""[SLUR:GENDER_MEN] [SLUR:GENDER_WOMEN] [SLUR...",hate_disability
571,Hate to give cunts like this the time of day b...,"""""""Hate to give [SLUR:GENDER_MEN] like this th...",hate_disability

In [57]:
INPUT_JSONL = "supertweeteval/merged_masked_unionv2.jsonl"

#INPUT_JSONL = "supertweeteval/broken_phone/balanced_with_broken_phone_supertweetevalv3.jsonl"

my_train_df = load_and_clean_tweethate(INPUT_JSONL, text_field="text_masked")

my_train_df = remove_values_from_column(my_train_df, "predicted_hate_category", ["hate_age"])

my_train_df = collapse_race_into_origin(my_train_df, col="predicted_hate_category")

In [58]:
df_all_runs, df_summary = experiment_from_df_multi_seed(
    df_trainval=my_train_df,
    df_test=df_min_remasked,
    X_field="text",
    seeds=[7,11,13,17,19]
)

=====================================
 Ejecutando Seeds: [7, 11, 13, 17, 19]
=====================================

##### SEED = 7 #####


=== VAL ===
              precision    recall  f1-score   support

           0     0.1000    0.5000    0.1667         2
           1     0.8966    0.6753    0.7704        77
           2     0.8750    0.6901    0.7717        71
           3     0.5238    0.9565    0.6769        23
           4     0.5938    0.7600    0.6667        25

    accuracy                         0.7222       198
   macro avg     0.5978    0.7164    0.6105       198
weighted avg     0.7992    0.7222    0.7408       198

Confusion matrix:
 [[ 1  0  0  1  0]
 [ 3 52  7  5 10]
 [ 4  4 49 11  3]
 [ 0  1  0 22  0]
 [ 2  1  0  3 19]]
F1-macro: 0.6105
Accuracy: 0.7222

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.6081    0.4455    0.5143       101
           1     0.7471    0.4610    0.5702       141
           2     0.6907    0.4891    0.5726       137
           3     0.3067    0.5750    0.4000        80
           4     0.6220    0.9027    0.7365       113

    accuracy                         0.5682       572
   macro avg     0.5949    0.5746    0.5587       572
weighted avg     0.6227    0.5682    0.5699       572

Confusion matrix:
 [[ 45   5   7  28  16]
 [ 11  65  11  36  18]
 [  8   7  67  36  19]
 [  7   7  11  46   9]
 [  3   3   1   4 102]]
F1-macro: 0.5587
Accuracy: 0.5682

=== VAL ===
              precision    recall  f1-score   support

           0     0.3333    0.5000    0.4000         2
           1     0.8788    0.7532    0.8112        77
           2     0.8472    0.8592    0.8531        71
           3     0.7037    0.8261    0.7600        23
           4     0.6667    0.8000    0.7273        25

    accuracy                         0.8030       198
   macro avg     0.6859    0.7477    0.7103       198
weighted avg     0.8148    0.8030    0.8055       198

Confusion matrix:
 [[ 1  0  1  0  0]
 [ 2 58  7  3  7]
 [ 0  3 61  5  2]
 [ 0  1  2 19  1]
 [ 0  4  1  0 20]]
F1-macro: 0.7103
Accuracy: 0.8030

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.7119    0.4158    0.5250       101
           1     0.6508    0.5816    0.6142       141
           2     0.5759    0.6642    0.6169       137
           3     0.5395    0.5125    0.5256        80
           4     0.6667    0.9027    0.7669       113

    accuracy                         0.6259       572
   macro avg     0.6289    0.6154    0.6097       572
weighted avg     0.6312    0.6259    0.6169       572

Confusion matrix:
 [[ 42  14  22  13  10]
 [  5  82  27   9  18]
 [  7  12  91  11  16]
 [  3  14  15  41   7]
 [  2   4   3   2 102]]
F1-macro: 0.6097
Accuracy: 0.6259

=== VAL ===
              precision    recall  f1-score   support

           0     0.5000    0.5000    0.5000         2
           1     0.8592    0.7922    0.8243        77
           2     0.8451    0.8451    0.8451        71
           3     0.7143    0.8696    0.7843        23
           4     0.7308    0.7600    0.7451        25

    accuracy                         0.8131       198
   macro avg     0.7299    0.7534    0.7398       198
weighted avg     0.8174    0.8131    0.8138       198

Confusion matrix:
 [[ 1  0  1  0  0]
 [ 1 61  8  2  5]
 [ 0  4 60  5  2]
 [ 0  2  1 20  0]
 [ 0  4  1  1 19]]
F1-macro: 0.7398
Accuracy: 0.8131

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.7119    0.4158    0.5250       101
           1     0.6560    0.5816    0.6165       141
           2     0.5363    0.7007    0.6076       137
           3     0.5672    0.4750    0.5170        80
           4     0.7254    0.9115    0.8078       113

    accuracy                         0.6311       572
   macro avg     0.6393    0.6169    0.6148       572
weighted avg     0.6385    0.6311    0.6221       572

Confusion matrix:
 [[ 42  13  28  11   7]
 [  4  82  33   9  13]
 [  7  12  96   9  13]
 [  4  14  18  38   6]
 [  2   4   4   0 103]]
F1-macro: 0.6148
Accuracy: 0.6311

=== VAL ===
              precision    recall  f1-score   support

           0     0.0000    0.0000    0.0000         2
           1     0.8750    0.8182    0.8456        77
           2     0.7927    0.9155    0.8497        71
           3     0.8095    0.7391    0.7727        23
           4     0.8261    0.7600    0.7917        25

    accuracy                         0.8283       198
   macro avg     0.6607    0.6466    0.6519       198
weighted avg     0.8229    0.8283    0.8233       198

Confusion matrix:
 [[ 0  1  1  0  0]
 [ 0 63 10  2  2]
 [ 0  3 65  2  1]
 [ 0  1  4 17  1]
 [ 0  4  2  0 19]]
F1-macro: 0.6519
Accuracy: 0.8283

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.7692    0.2970    0.4286       101
           1     0.5705    0.6312    0.5993       141
           2     0.5181    0.7299    0.6061       137
           3     0.6458    0.3875    0.4844        80
           4     0.7426    0.8938    0.8112       113

    accuracy                         0.6136       572
   macro avg     0.6493    0.5879    0.5859       572
weighted avg     0.6376    0.6136    0.5966       572

Confusion matrix:
 [[ 30  23  34   8   6]
 [  3  89  35   3  11]
 [  2  17 100   6  12]
 [  2  21  20  31   6]
 [  2   6   4   0 101]]
F1-macro: 0.5859
Accuracy: 0.6136

=== VAL ===
              precision    recall  f1-score   support

           0     0.0769    0.5000    0.1333         2
           1     0.8421    0.6234    0.7164        77
           2     0.8269    0.6056    0.6992        71
           3     0.5238    0.9565    0.6769        23
           4     0.5588    0.7600    0.6441        25

    accuracy                         0.6717       198
   macro avg     0.5657    0.6891    0.5740       198
weighted avg     0.7562    0.6717    0.6906       198

Confusion matrix:
 [[ 1  0  0  1  0]
 [ 5 48  7  6 11]
 [ 5  8 43 11  4]
 [ 0  0  1 22  0]
 [ 2  1  1  2 19]]
F1-macro: 0.5740
Accuracy: 0.6717

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.5361    0.5149    0.5253       101
           1     0.6593    0.4255    0.5172       141
           2     0.6346    0.4818    0.5477       137
           3     0.3621    0.5250    0.4286        80
           4     0.6280    0.9115    0.7437       113

    accuracy                         0.5647       572
   macro avg     0.5640    0.5717    0.5525       572
weighted avg     0.5839    0.5647    0.5583       572

Confusion matrix:
 [[ 52  11   8  18  12]
 [ 16  60  17  29  19]
 [ 17   7  66  26  21]
 [  7  11  11  42   9]
 [  5   2   2   1 103]]
F1-macro: 0.5525
Accuracy: 0.5647

##### SEED = 11 #####


=== VAL ===
              precision    recall  f1-score   support

           0     0.0000    0.0000    0.0000         2
           1     0.9464    0.6883    0.7970        77
           2     0.9153    0.7606    0.8308        71
           3     0.5500    0.9565    0.6984        23
           4     0.5676    0.8400    0.6774        25

    accuracy                         0.7576       198
   macro avg     0.5959    0.6491    0.6007       198
weighted avg     0.8318    0.7576    0.7745       198

Confusion matrix:
 [[ 0  1  1  0  0]
 [ 4 53  2  4 14]
 [ 1  2 54 12  2]
 [ 0  0  1 22  0]
 [ 1  0  1  2 21]]
F1-macro: 0.6007
Accuracy: 0.7576

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.4956    0.5545    0.5234       101
           1     0.7470    0.4397    0.5536       141
           2     0.7590    0.4599    0.5727       137
           3     0.3481    0.5875    0.4372        80
           4     0.6456    0.9027    0.7528       113

    accuracy                         0.5769       572
   macro avg     0.5991    0.5888    0.5679       572
weighted avg     0.6297    0.5769    0.5759       572

Confusion matrix:
 [[ 56   5   5  24  11]
 [ 20  62  10  28  21]
 [ 22   6  63  32  14]
 [ 11   7   5  47  10]
 [  4   3   0   4 102]]
F1-macro: 0.5679
Accuracy: 0.5769

=== VAL ===
              precision    recall  f1-score   support

           0     0.0000    0.0000    0.0000         2
           1     0.8889    0.8312    0.8591        77
           2     0.8788    0.8169    0.8467        71
           3     0.6667    0.8696    0.7547        23
           4     0.6667    0.7200    0.6923        25

    accuracy                         0.8081       198
   macro avg     0.6202    0.6475    0.6306       198
weighted avg     0.8224    0.8081    0.8128       198

Confusion matrix:
 [[ 0  1  1  0  0]
 [ 2 64  2  2  7]
 [ 0  4 58  7  2]
 [ 0  1  2 20  0]
 [ 1  2  3  1 18]]
F1-macro: 0.6306
Accuracy: 0.8081

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.5375    0.4257    0.4751       101
           1     0.5938    0.5390    0.5651       141
           2     0.5809    0.5766    0.5788       137
           3     0.5405    0.5000    0.5195        80
           4     0.6688    0.9115    0.7715       113

    accuracy                         0.5962       572
   macro avg     0.5843    0.5906    0.5820       572
weighted avg     0.5881    0.5962    0.5869       572

Confusion matrix:
 [[ 43  17  23   8  10]
 [ 15  76  22  11  17]
 [ 14  12  79  14  18]
 [  6  17  11  40   6]
 [  2   6   1   1 103]]
F1-macro: 0.5820
Accuracy: 0.5962

=== VAL ===
              precision    recall  f1-score   support

           0     0.0000    0.0000    0.0000         2
           1     0.9054    0.8701    0.8874        77
           2     0.8955    0.8451    0.8696        71
           3     0.7333    0.9565    0.8302        23
           4     0.7200    0.7200    0.7200        25

    accuracy                         0.8434       198
   macro avg     0.6509    0.6783    0.6614       198
weighted avg     0.8493    0.8434    0.8443       198

Confusion matrix:
 [[ 0  1  1  0  0]
 [ 1 67  2  1  6]
 [ 0  4 60  6  1]
 [ 0  0  1 22  0]
 [ 1  2  3  1 18]]
F1-macro: 0.6614
Accuracy: 0.8434

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.6000    0.4455    0.5114       101
           1     0.6429    0.5745    0.6067       141
           2     0.5556    0.6569    0.6020       137
           3     0.5821    0.4875    0.5306        80
           4     0.7183    0.9027    0.8000       113

    accuracy                         0.6241       572
   macro avg     0.6198    0.6134    0.6101       572
weighted avg     0.6208    0.6241    0.6163       572

Confusion matrix:
 [[ 45  12  27   9   8]
 [ 12  81  25   9  14]
 [ 12  12  90  10  13]
 [  4  16  16  39   5]
 [  2   5   4   0 102]]
F1-macro: 0.6101
Accuracy: 0.6241

/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1281: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1296: FutureWarning: Using the 'liblinear' solver for multiclass classification is deprecated. An error will be raised in 1.8. Either use another solver which supports the multinomial loss or wrap the estimator in a OneVsRestClassifier to keep applying a one-versus-rest scheme.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1305: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 32.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1281: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1296: FutureWarning: Using the 'liblinear' solver for multiclass classification is deprecated. An error will be raised in 1.8. Either use another solver which supports the multinomial loss or wrap the estimator in a OneVsRestClassifier to keep applying a one-versus-rest scheme.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1305: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 32.
  warnings.warn(

=== VAL ===
              precision    recall  f1-score   support

           0     0.0000    0.0000    0.0000         2
           1     0.8415    0.8961    0.8679        77
           2     0.8429    0.8310    0.8369        71
           3     0.7500    0.7826    0.7660        23
           4     0.9048    0.7600    0.8261        25

    accuracy                         0.8333       198
   macro avg     0.6678    0.6539    0.6594       198
weighted avg     0.8308    0.8333    0.8309       198

Confusion matrix:
 [[ 0  1  1  0  0]
 [ 1 69  4  1  2]
 [ 0  8 59  4  0]
 [ 0  2  3 18  0]
 [ 0  2  3  1 19]]
F1-macro: 0.6594
Accuracy: 0.8333

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.7857    0.3267    0.4615       101
           1     0.5667    0.6028    0.5842       141
           2     0.5185    0.7153    0.6012       137
           3     0.6122    0.3750    0.4651        80
           4     0.7042    0.8850    0.7843       113

    accuracy                         0.6049       572
   macro avg     0.6375    0.5810    0.5793       572
weighted avg     0.6274    0.6049    0.5895       572

Confusion matrix:
 [[ 33  21  33   6   8]
 [  3  85  35   7  11]
 [  3  14  98   6  16]
 [  1  22  20  30   7]
 [  2   8   3   0 100]]
F1-macro: 0.5793
Accuracy: 0.6049

=== VAL ===
              precision    recall  f1-score   support

           0     0.0000    0.0000    0.0000         2
           1     0.8491    0.5844    0.6923        77
           2     0.9038    0.6620    0.7642        71
           3     0.5000    0.9565    0.6567        23
           4     0.4878    0.8000    0.6061        25

    accuracy                         0.6768       198
   macro avg     0.5481    0.6006    0.5439       198
weighted avg     0.7740    0.6768    0.6961       198

Confusion matrix:
 [[ 0  1  1  0  0]
 [ 6 45  3  5 18]
 [ 1  6 47 14  3]
 [ 0  0  1 22  0]
 [ 1  1  0  3 20]]
F1-macro: 0.5439
Accuracy: 0.6768

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.4914    0.5644    0.5253       101
           1     0.6300    0.4468    0.5228       141
           2     0.6900    0.5036    0.5823       137
           3     0.4111    0.4625    0.4353        80
           4     0.6145    0.9027    0.7312       113

    accuracy                         0.5734       572
   macro avg     0.5674    0.5760    0.5594       572
weighted avg     0.5862    0.5734    0.5664       572

Confusion matrix:
 [[ 57  10   5  15  14]
 [ 28  63  16  13  21]
 [ 18   7  69  23  20]
 [  8  17   9  37   9]
 [  5   3   1   2 102]]
F1-macro: 0.5594
Accuracy: 0.5734

##### SEED = 13 #####


=== VAL ===
              precision    recall  f1-score   support

           0     0.1429    0.5000    0.2222         2
           1     0.9231    0.7792    0.8451        77
           2     0.9623    0.7183    0.8226        71
           3     0.5500    0.9565    0.6984        23
           4     0.6364    0.8400    0.7241        25

    accuracy                         0.7828       198
   macro avg     0.6429    0.7588    0.6625       198
weighted avg     0.8497    0.7828    0.7984       198

Confusion matrix:
 [[ 1  0  1  0  0]
 [ 2 60  0  3 12]
 [ 3  4 51 13  0]
 [ 0  0  1 22  0]
 [ 1  1  0  2 21]]
F1-macro: 0.6625
Accuracy: 0.7828

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.6992    0.8515    0.7679       101
           1     0.7975    0.4468    0.5727       141
           2     0.7033    0.4672    0.5614       137
           3     0.3721    0.6000    0.4593        80
           4     0.6867    0.9115    0.7833       113

    accuracy                         0.6364       572
   macro avg     0.6517    0.6554    0.6289       572
weighted avg     0.6762    0.6364    0.6302       572

Confusion matrix:
 [[ 86   0   2   8   5]
 [ 17  63  12  31  18]
 [ 10   6  64  41  16]
 [  8   7   9  48   8]
 [  2   3   4   1 103]]
F1-macro: 0.6289
Accuracy: 0.6364

=== VAL ===
              precision    recall  f1-score   support

           0     0.5000    0.5000    0.5000         2
           1     0.8800    0.8571    0.8684        77
           2     0.9077    0.8310    0.8676        71
           3     0.6923    0.7826    0.7347        23
           4     0.7333    0.8800    0.8000        25

    accuracy                         0.8384       198
   macro avg     0.7427    0.7701    0.7542       198
weighted avg     0.8458    0.8384    0.8402       198

Confusion matrix:
 [[ 1  0  1  0  0]
 [ 0 66  2  1  8]
 [ 1  4 59  7  0]
 [ 0  4  1 18  0]
 [ 0  1  2  0 22]]
F1-macro: 0.7542
Accuracy: 0.8384

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.7822    0.7822    0.7822       101
           1     0.6957    0.5674    0.6250       141
           2     0.6207    0.6569    0.6383       137
           3     0.5588    0.4750    0.5135        80
           4     0.7133    0.9027    0.7969       113

    accuracy                         0.6801       572
   macro avg     0.6741    0.6768    0.6712       572
weighted avg     0.6773    0.6801    0.6743       572

Confusion matrix:
 [[ 79   5   8   5   4]
 [  7  80  27  13  14]
 [  6  11  90  12  18]
 [  7  13  17  38   5]
 [  2   6   3   0 102]]
F1-macro: 0.6712
Accuracy: 0.6801

=== VAL ===
              precision    recall  f1-score   support

           0     0.5000    0.5000    0.5000         2
           1     0.8625    0.8961    0.8790        77
           2     0.9091    0.8451    0.8759        71
           3     0.7391    0.7391    0.7391        23
           4     0.7407    0.8000    0.7692        25

    accuracy                         0.8434       198
   macro avg     0.7503    0.7561    0.7527       198
weighted avg     0.8458    0.8434    0.8439       198

Confusion matrix:
 [[ 1  0  1  0  0]
 [ 0 69  1  0  7]
 [ 1  4 60  6  0]
 [ 0  4  2 17  0]
 [ 0  3  2  0 20]]
F1-macro: 0.7527
Accuracy: 0.8434

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.7921    0.7921    0.7921       101
           1     0.6930    0.5603    0.6196       141
           2     0.5879    0.7080    0.6424       137
           3     0.5893    0.4125    0.4853        80
           4     0.7500    0.9027    0.8193       113

    accuracy                         0.6836       572
   macro avg     0.6824    0.6751    0.6717       572
weighted avg     0.6821    0.6836    0.6762       572

Confusion matrix:
 [[ 80   5  10   4   2]
 [  5  79  33  11  13]
 [  6  12  97   8  14]
 [  8  12  22  33   5]
 [  2   6   3   0 102]]
F1-macro: 0.6717
Accuracy: 0.6836

=== VAL ===
              precision    recall  f1-score   support

           0     1.0000    0.5000    0.6667         2
           1     0.8519    0.8961    0.8734        77
           2     0.8732    0.8732    0.8732        71
           3     0.7895    0.6522    0.7143        23
           4     0.7692    0.8000    0.7843        25

    accuracy                         0.8434       198
   macro avg     0.8568    0.7443    0.7824       198
weighted avg     0.8433    0.8434    0.8415       198

Confusion matrix:
 [[ 1  0  1  0  0]
 [ 0 69  3  0  5]
 [ 0  5 62  4  0]
 [ 0  4  3 15  1]
 [ 0  3  2  0 20]]
F1-macro: 0.7824
Accuracy: 0.8434

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.8333    0.6436    0.7263       101
           1     0.6087    0.5957    0.6022       141
           2     0.5385    0.7153    0.6144       137
           3     0.6512    0.3500    0.4553        80
           4     0.7786    0.9027    0.8361       113

    accuracy                         0.6591       572
   macro avg     0.6821    0.6415    0.6468       572
weighted avg     0.6710    0.6591    0.6527       572

Confusion matrix:
 [[ 65  13  18   4   1]
 [  3  84  39   4  11]
 [  4  16  98   7  12]
 [  4  19  24  28   5]
 [  2   6   3   0 102]]
F1-macro: 0.6468
Accuracy: 0.6591

=== VAL ===
              precision    recall  f1-score   support

           0     0.0667    0.5000    0.1176         2
           1     0.8806    0.7662    0.8194        77
           2     0.9216    0.6620    0.7705        71
           3     0.5588    0.8261    0.6667        23
           4     0.6452    0.8000    0.7143        25

    accuracy                         0.7374       198
   macro avg     0.6146    0.7109    0.6177       198
weighted avg     0.8200    0.7374    0.7638       198

Confusion matrix:
 [[ 1  0  1  0  0]
 [ 5 59  1  2 10]
 [ 7  4 47 13  0]
 [ 0  2  1 19  1]
 [ 2  2  1  0 20]]
F1-macro: 0.6177
Accuracy: 0.7374

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.5906    0.8713    0.7040       101
           1     0.7500    0.4468    0.5600       141
           2     0.6392    0.4526    0.5299       137
           3     0.4318    0.4750    0.4524        80
           4     0.6753    0.9204    0.7790       113

    accuracy                         0.6206       572
   macro avg     0.6174    0.6332    0.6051       572
weighted avg     0.6361    0.6206    0.6064       572

Confusion matrix:
 [[ 88   1   2   5   5]
 [ 28  63  18  14  18]
 [ 17   7  62  30  21]
 [ 12  11  13  38   6]
 [  4   2   2   1 104]]
F1-macro: 0.6051
Accuracy: 0.6206

##### SEED = 17 #####


=== VAL ===
              precision    recall  f1-score   support

           0     0.0000    0.0000    0.0000         2
           1     0.9104    0.7922    0.8472        77
           2     0.9574    0.6338    0.7627        71
           3     0.4510    1.0000    0.6216        23
           4     0.8462    0.8800    0.8627        25

    accuracy                         0.7626       198
   macro avg     0.6330    0.6612    0.6189       198
weighted avg     0.8566    0.7626    0.7841       198

Confusion matrix:
 [[ 0  1  0  1  0]
 [ 4 61  2  6  4]
 [ 2  5 45 19  0]
 [ 0  0  0 23  0]
 [ 1  0  0  2 22]]
F1-macro: 0.6189
Accuracy: 0.7626

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.6438    0.4653    0.5402       101
           1     0.7558    0.4610    0.5727       141
           2     0.7000    0.4088    0.5161       137
           3     0.3152    0.6500    0.4245        80
           4     0.6131    0.9115    0.7331       113

    accuracy                         0.5647       572
   macro avg     0.6056    0.5793    0.5573       572
weighted avg     0.6328    0.5647    0.5644       572

Confusion matrix:
 [[ 47   4   7  29  14]
 [ 11  65  10  34  21]
 [  8   7  56  46  20]
 [  5   7   6  52  10]
 [  2   3   1   4 103]]
F1-macro: 0.5573
Accuracy: 0.5647

=== VAL ===
              precision    recall  f1-score   support

           0     0.0000    0.0000    0.0000         2
           1     0.9315    0.8831    0.9067        77
           2     0.9143    0.9014    0.9078        71
           3     0.7241    0.9130    0.8077        23
           4     0.9200    0.9200    0.9200        25

    accuracy                         0.8889       198
   macro avg     0.6980    0.7235    0.7084       198
weighted avg     0.8904    0.8889    0.8881       198

Confusion matrix:
 [[ 0  1  0  0  1]
 [ 1 68  5  2  1]
 [ 0  3 64  4  0]
 [ 0  1  1 21  0]
 [ 0  0  0  2 23]]
F1-macro: 0.7084
Accuracy: 0.8889

=== TEST (fijo) ===

/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1281: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1296: FutureWarning: Using the 'liblinear' solver for multiclass classification is deprecated. An error will be raised in 1.8. Either use another solver which supports the multinomial loss or wrap the estimator in a OneVsRestClassifier to keep applying a one-versus-rest scheme.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1305: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 32.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1281: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1296: FutureWarning: Using the 'liblinear' solver for multiclass classification is deprecated. An error will be raised in 1.8. Either use another solver which supports the multinomial loss or wrap the estimator in a OneVsRestClassifier to keep applying a one-versus-rest scheme.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1305: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 32.
  warnings.warn(

              precision    recall  f1-score   support

           0     0.7000    0.4158    0.5217       101
           1     0.6783    0.5532    0.6094       141
           2     0.5641    0.6423    0.6007       137
           3     0.4819    0.5000    0.4908        80
           4     0.6456    0.9027    0.7528       113

    accuracy                         0.6119       572
   macro avg     0.6140    0.6028    0.5951       572
weighted avg     0.6208    0.6119    0.6036       572

Confusion matrix:
 [[ 42  11  24  12  12]
 [  7  78  24  12  20]
 [  6   7  88  17  19]
 [  3  14  18  40   5]
 [  2   5   2   2 102]]
F1-macro: 0.5951
Accuracy: 0.6119

=== VAL ===
              precision    recall  f1-score   support

           0     0.0000    0.0000    0.0000         2
           1     0.9200    0.8961    0.9079        77
           2     0.8904    0.9155    0.9028        71
           3     0.7857    0.9565    0.8627        23
           4     1.0000    0.8400    0.9130        25

    accuracy                         0.8939       198
   macro avg     0.7192    0.7216    0.7173       198
weighted avg     0.8946    0.8939    0.8923       198

Confusion matrix:
 [[ 0  1  1  0  0]
 [ 1 69  5  2  0]
 [ 0  4 65  2  0]
 [ 0  0  1 22  0]
 [ 0  1  1  2 21]]
F1-macro: 0.7173
Accuracy: 0.8939

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.7000    0.4158    0.5217       101
           1     0.6752    0.5603    0.6124       141
           2     0.5246    0.7007    0.6000       137
           3     0.5211    0.4625    0.4901        80
           4     0.7234    0.9027    0.8031       113

    accuracy                         0.6224       572
   macro avg     0.6289    0.6084    0.6055       572
weighted avg     0.6315    0.6224    0.6140       572

Confusion matrix:
 [[ 42   9  31   9  10]
 [  6  79  33  12  11]
 [  6   9  96  13  13]
 [  4  14  20  37   5]
 [  2   6   3   0 102]]
F1-macro: 0.6055
Accuracy: 0.6224

=== VAL ===
              precision    recall  f1-score   support

           0     0.0000    0.0000    0.0000         2
           1     0.8974    0.9091    0.9032        77
           2     0.8904    0.9155    0.9028        71
           3     0.8077    0.9130    0.8571        23
           4     1.0000    0.8000    0.8889        25

    accuracy                         0.8889       198
   macro avg     0.7191    0.7075    0.7104       198
weighted avg     0.8884    0.8889    0.8868       198

Confusion matrix:
 [[ 0  1  1  0  0]
 [ 1 70  4  2  0]
 [ 0  4 65  2  0]
 [ 0  1  1 21  0]
 [ 0  2  2  1 20]]
F1-macro: 0.7104
Accuracy: 0.8889

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.7400    0.3663    0.4901       101
           1     0.5822    0.6028    0.5923       141
           2     0.5238    0.7226    0.6074       137
           3     0.6078    0.3875    0.4733        80
           4     0.7500    0.9027    0.8193       113

    accuracy                         0.6189       572
   macro avg     0.6408    0.5964    0.5965       572
weighted avg     0.6328    0.6189    0.6061       572

Confusion matrix:
 [[ 37  17  30  10   7]
 [  5  85  37   3  11]
 [  4  16  99   7  11]
 [  2  22  20  31   5]
 [  2   6   3   0 102]]
F1-macro: 0.5965
Accuracy: 0.6189

=== VAL ===
              precision    recall  f1-score   support

           0     0.0714    0.5000    0.1250         2
           1     0.8871    0.7143    0.7914        77
           2     0.8913    0.5775    0.7009        71
           3     0.4490    0.9565    0.6111        23
           4     0.7778    0.8400    0.8077        25

    accuracy                         0.7071       198
   macro avg     0.6153    0.7177    0.6072       198
weighted avg     0.8157    0.7071    0.7333       198

Confusion matrix:
 [[ 1  1  0  0  0]
 [ 6 55  5  5  6]
 [ 5  5 41 20  0]
 [ 1  0  0 22  0]
 [ 1  1  0  2 21]]
F1-macro: 0.6072
Accuracy: 0.7071

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.4741    0.5446    0.5069       101
           1     0.6061    0.4255    0.5000       141
           2     0.6484    0.4307    0.5175       137
           3     0.3714    0.4875    0.4216        80
           4     0.6335    0.9027    0.7445       113

    accuracy                         0.5507       572
   macro avg     0.5467    0.5582    0.5381       572
weighted avg     0.5655    0.5507    0.5428       572

Confusion matrix:
 [[ 55  11   4  17  14]
 [ 25  60  18  21  17]
 [ 23   8  59  27  20]
 [  8  16   9  39   8]
 [  5   4   1   1 102]]
F1-macro: 0.5381
Accuracy: 0.5507

##### SEED = 19 #####


=== VAL ===
              precision    recall  f1-score   support

           0     0.0000    0.0000    0.0000         2
           1     0.9375    0.7792    0.8511        77
           2     0.8793    0.7183    0.7907        71
           3     0.5385    0.9130    0.6774        23
           4     0.6667    0.8800    0.7586        25

    accuracy                         0.7778       198
   macro avg     0.6044    0.6581    0.6156       198
weighted avg     0.8266    0.7778    0.7890       198

Confusion matrix:
 [[ 0  0  0  1  1]
 [ 2 60  7  4  4]
 [ 2  1 51 12  5]
 [ 0  1  0 21  1]
 [ 0  2  0  1 22]]
F1-macro: 0.6156
Accuracy: 0.7778

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.6667    0.8317    0.7401       101
           1     0.7831    0.4610    0.5804       141
           2     0.7444    0.4891    0.5903       137
           3     0.3740    0.5750    0.4532        80
           4     0.6733    0.8938    0.7681       113

    accuracy                         0.6346       572
   macro avg     0.6483    0.6501    0.6264       572
weighted avg     0.6744    0.6346    0.6302       572

Confusion matrix:
 [[ 84   2   2   8   5]
 [ 17  65  10  29  20]
 [ 13   6  67  36  15]
 [  9   7   9  46   9]
 [  3   3   2   4 101]]
F1-macro: 0.6264
Accuracy: 0.6346

=== VAL ===
              precision    recall  f1-score   support

           0     0.0000    0.0000    0.0000         2
           1     0.8767    0.8312    0.8533        77
           2     0.8429    0.8310    0.8369        71
           3     0.7200    0.7826    0.7500        23
           4     0.8077    0.8400    0.8235        25

    accuracy                         0.8182       198
   macro avg     0.6495    0.6570    0.6527       198
weighted avg     0.8288    0.8182    0.8230       198

Confusion matrix:
 [[ 0  1  0  0  1]
 [ 2 64  7  2  2]
 [ 2  4 59  5  1]
 [ 0  2  2 18  1]
 [ 0  2  2  0 21]]
F1-macro: 0.6527
Accuracy: 0.8182

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.7670    0.7822    0.7745       101
           1     0.7232    0.5745    0.6403       141
           2     0.6027    0.6423    0.6219       137
           3     0.5797    0.5000    0.5369        80
           4     0.7254    0.9115    0.8078       113

    accuracy                         0.6836       572
   macro avg     0.6796    0.6821    0.6763       572
weighted avg     0.6824    0.6836    0.6782       572

Confusion matrix:
 [[ 79   6   9   4   3]
 [  6  81  28  12  14]
 [  8  10  88  13  18]
 [  8  11  17  40   4]
 [  2   4   4   0 103]]
F1-macro: 0.6763
Accuracy: 0.6836

=== VAL ===
              precision    recall  f1-score   support

           0     0.0000    0.0000    0.0000         2
           1     0.8684    0.8571    0.8627        77
           2     0.8194    0.8310    0.8252        71
           3     0.6957    0.6957    0.6957        23
           4     0.9130    0.8400    0.8750        25

    accuracy                         0.8182       198
   macro avg     0.6593    0.6448    0.6517       198
weighted avg     0.8277    0.8182    0.8227       198

Confusion matrix:
 [[ 0  1  0  0  1]
 [ 2 66  7  2  0]
 [ 2  5 59  5  0]
 [ 0  2  4 16  1]
 [ 0  2  2  0 21]]
F1-macro: 0.6517
Accuracy: 0.8182

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.7596    0.7822    0.7707       101
           1     0.7411    0.5887    0.6561       141
           2     0.5780    0.7299    0.6452       137
           3     0.6458    0.3875    0.4844        80
           4     0.7481    0.8938    0.8145       113

    accuracy                         0.6888       572
   macro avg     0.6945    0.6764    0.6742       572
weighted avg     0.6934    0.6888    0.6810       572

Confusion matrix:
 [[ 79   5  11   3   3]
 [  5  83  32   8  13]
 [  9   9 100   6  13]
 [  9  11  24  31   5]
 [  2   4   6   0 101]]
F1-macro: 0.6742
Accuracy: 0.6888

=== VAL ===
              precision    recall  f1-score   support

           0     0.0000    0.0000    0.0000         2
           1     0.8272    0.8701    0.8481        77
           2     0.8514    0.8873    0.8690        71
           3     0.7368    0.6087    0.6667        23
           4     0.8696    0.8000    0.8333        25

    accuracy                         0.8283       198
   macro avg     0.6570    0.6332    0.6434       198
weighted avg     0.8223    0.8283    0.8241       198

Confusion matrix:
 [[ 0  1  0  0  1]
 [ 1 67  6  2  1]
 [ 0  5 63  3  0]
 [ 0  4  4 14  1]
 [ 0  4  1  0 20]]
F1-macro: 0.6434
Accuracy: 0.8283

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.8171    0.6634    0.7322       101
           1     0.6449    0.6312    0.6380       141
           2     0.5562    0.7226    0.6286       137
           3     0.6383    0.3750    0.4724        80
           4     0.7953    0.8938    0.8417       113

    accuracy                         0.6748       572
   macro avg     0.6904    0.6572    0.6626       572
weighted avg     0.6828    0.6748    0.6695       572

Confusion matrix:
 [[ 67  10  18   4   2]
 [  4  89  33   6   9]
 [  4  16  99   7  11]
 [  5  17  24  30   4]
 [  2   6   4   0 101]]
F1-macro: 0.6626
Accuracy: 0.6748

=== VAL ===
              precision    recall  f1-score   support

           0     0.0000    0.0000    0.0000         2
           1     0.9123    0.6753    0.7761        77
           2     0.8448    0.6901    0.7597        71
           3     0.4762    0.8696    0.6154        23
           4     0.7143    0.8000    0.7547        25

    accuracy                         0.7121       198
   macro avg     0.5895    0.6070    0.5812       198
weighted avg     0.8032    0.7121    0.7410       198

Confusion matrix:
 [[ 0  0  0  1  1]
 [ 5 52  6  9  5]
 [ 6  4 49 11  1]
 [ 1  0  1 20  1]
 [ 1  1  2  1 20]]
F1-macro: 0.5812
Accuracy: 0.7121

=== TEST (fijo) ===
              precision    recall  f1-score   support

           0     0.5621    0.8515    0.6772       101
           1     0.7209    0.4397    0.5463       141
           2     0.6632    0.4599    0.5431       137
           3     0.4368    0.4750    0.4551        80
           4     0.6755    0.9027    0.7727       113

    accuracy                         0.6136       572
   macro avg     0.6117    0.6257    0.5989       572
weighted avg     0.6303    0.6136    0.6006       572

Confusion matrix:
 [[ 86   2   2   7   4]
 [ 24  62  16  18  21]
 [ 25   9  63  22  18]
 [ 13  10  13  38   6]
 [  5   3   1   2 102]]
F1-macro: 0.5989
Accuracy: 0.6136

=====================================
Resumen Multi-Seed (95% CI)
=====================================
             model  val_f1_macro_mean  val_f1_macro_std  val_f1_macro_CI_low  val_f1_macro_CI_high  test_f1_macro_mean  test_f1_macro_std  test_f1_macro_CI_low  test_f1_macro_CI_high
           sgd_log           0.704571          0.045734             0.664483              0.744658            0.635265           0.034575              0.604959               0.665571
        linear_svm           0.691243          0.049450             0.647898              0.734588            0.626857           0.043943              0.588339               0.665375
passive_aggressive           0.689503          0.058110             0.638567              0.740439            0.614215           0.037882              0.581010               0.647420
        logreg_ovr           0.621616          0.023852             0.600708              0.642524            0.587858           0.036573              0.555800               0.619916
     complement_nb           0.584789          0.029115             0.559268              0.610309            0.570786           0.029560              0.544875               0.596697

/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1281: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1296: FutureWarning: Using the 'liblinear' solver for multiclass classification is deprecated. An error will be raised in 1.8. Either use another solver which supports the multinomial loss or wrap the estimator in a OneVsRestClassifier to keep applying a one-versus-rest scheme.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1305: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 32.
  warnings.warn(

In [59]:
df_summary

,model,val_f1_macro_mean,val_f1_macro_std,val_f1_macro_CI_low,val_f1_macro_CI_high,test_f1_macro_mean,test_f1_macro_std,test_f1_macro_CI_low,test_f1_macro_CI_high
4,sgd_log,0.704571,0.045734,0.664483,0.744658,0.635265,0.034575,0.604959,0.665571
1,linear_svm,0.691243,0.049450,0.647898,0.734588,0.626857,0.043943,0.588339,0.665375
3,passive_aggressive,0.689503,0.058110,0.638567,0.740439,0.614215,0.037882,0.581010,0.647420
2,logreg_ovr,0.621616,0.023852,0.600708,0.642524,0.587858,0.036573,0.555800,0.619916
0,complement_nb,0.584789,0.029115,0.559268,0.610309,0.570786,0.029560,0.544875,0.596697

In [56]:
df_summary

,model,val_f1_macro_mean,val_f1_macro_std,val_f1_macro_CI_low,val_f1_macro_CI_high,test_f1_macro_mean,test_f1_macro_std,test_f1_macro_CI_low,test_f1_macro_CI_high
3,passive_aggressive,0.986146,0.004920,0.981834,0.990459,0.573849,0.011785,0.563520,0.584179
1,linear_svm,0.982166,0.003895,0.978752,0.985580,0.625455,0.006698,0.619584,0.631326
4,sgd_log,0.975202,0.004870,0.970934,0.979471,0.627862,0.006536,0.622132,0.633591
2,logreg_ovr,0.964467,0.006119,0.959103,0.969830,0.638500,0.001303,0.637358,0.639642
0,complement_nb,0.931495,0.014556,0.918736,0.944254,0.626433,0.004067,0.622868,0.629998

# Dual view

In [41]:
from scipy.sparse import hstack

def _single_seed_experiment_dualview(
    df_trainval,
    df_test,
    raw_field,
    masked_field,
    seed,
    val_size,
    ngram_range,
    min_df,
    max_df,
    max_features
):
    """
    Single-seed experiment using BOTH raw and masked text as features.

    df_trainval / df_test must contain:
        - raw_field        (e.g. 'text')
        - masked_field     (e.g. 'text_masked')
        - predicted_hate_category
    """
    random.seed(seed)
    np.random.seed(seed)

    # --------- Filter valid text in both views ----------
    def valid_str(x):
        return isinstance(x, str) and x.strip() != ""

    df_trainval = df_trainval[
        df_trainval[raw_field].apply(valid_str)
        & df_trainval[masked_field].apply(valid_str)
    ].copy()

    df_test = df_test[
        df_test[raw_field].apply(valid_str)
        & df_test[masked_field].apply(valid_str)
    ].copy()

    # --------- Normalize and filter 'nan' labels ----------
    for df in (df_trainval, df_test):
        df["phc"] = df["predicted_hate_category"].astype(str).str.strip()

    df_trainval = df_trainval[df_trainval["phc"].str.lower() != "nan"].copy()
    df_test     = df_test[df_test["phc"].str.lower() != "nan"].copy()

    if len(df_trainval) == 0 or len(df_test) == 0:
        raise RuntimeError("Train/Val o Test vacío tras filtrar 'nan'.")

    # --------- Label mapping (union train+test) ----------
    all_labels = sorted(set(df_trainval["phc"].str.lower()) |
                        set(df_test["phc"].str.lower()))
    label2id = {c: i for i, c in enumerate(all_labels)}
    id2label = {i: c for c, i in label2id.items()}

    for df in (df_trainval, df_test):
        df["label"] = df["phc"].str.lower().map(label2id).astype(int)
        df["clean_raw"]    = df[raw_field].apply(clean_text)
        df["clean_masked"] = df[masked_field].apply(clean_text)

    # --------- Train/Val split (dual-view) ----------
    X_raw = df_trainval["clean_raw"].values
    X_msk = df_trainval["clean_masked"].values
    y_all = df_trainval["label"].values

    X_raw_train, X_raw_val, X_msk_train, X_msk_val, y_train, y_val = train_test_split(
        X_raw,
        X_msk,
        y_all,
        test_size=val_size,
        random_state=seed,
        stratify=y_all,
    )

    X_raw_test = df_test["clean_raw"].values
    X_msk_test = df_test["clean_masked"].values
    y_test     = df_test["label"].values

    # --------- TF-IDF for RAW and MASKED separately ----------
    vec_raw = TfidfVectorizer(
        lowercase=True,
        ngram_range=ngram_range,
        min_df=min_df,
        max_df=max_df,
        strip_accents="unicode",
        sublinear_tf=True,
        stop_words="english",
        max_features=max_features,
    )
    vec_msk = TfidfVectorizer(
        lowercase=True,
        ngram_range=ngram_range,
        min_df=min_df,
        max_df=max_df,
        strip_accents="unicode",
        sublinear_tf=True,
        stop_words="english",
        max_features=max_features,
    )

    Xtr_raw = vec_raw.fit_transform(X_raw_train)
    Xva_raw = vec_raw.transform(X_raw_val)
    Xte_raw = vec_raw.transform(X_raw_test)

    Xtr_msk = vec_msk.fit_transform(X_msk_train)
    Xva_msk = vec_msk.transform(X_msk_val)
    Xte_msk = vec_msk.transform(X_msk_test)

    # Concatenate [raw | masked]
    Xtr = hstack([Xtr_raw, Xtr_msk], format="csr")
    Xva = hstack([Xva_raw, Xva_msk], format="csr")
    Xte = hstack([Xte_raw, Xte_msk], format="csr")

    # --------- Class weights ----------
    uniq = np.unique(y_train)
    class_weights = compute_class_weight(class_weight="balanced", classes=uniq, y=y_train)
    cw_map = {int(c): float(w) for c, w in zip(uniq, class_weights)}
    sw_train = np.vectorize(cw_map.get)(y_train)

    # --------- Models ----------
    models = {
        "logreg_ovr": LogisticRegression(
            max_iter=8000, n_jobs=-1, class_weight=cw_map, C=2.0,
            solver="liblinear", multi_class="ovr", random_state=seed),
        "linear_svm": LinearSVC(class_weight=cw_map, random_state=seed),
        "sgd_log": SGDClassifier(loss="log_loss", alpha=1e-4, max_iter=2000,
                                 tol=1e-3, random_state=seed),
        "passive_aggressive": PassiveAggressiveClassifier(C=0.5, max_iter=2000,
                                                          random_state=seed),
        "complement_nb": ComplementNB(alpha=0.5),
    }

    seed_results = []

    for name, clf in models.items():
        print("\n" + "="*100)
        print(f"Entrenando (dual-view): {name}  — seed={seed}")

        # Entrenamiento
        try:
            clf.fit(Xtr, y_train, sample_weight=sw_train)
        except TypeError:
            clf.fit(Xtr, y_train)

        # Evaluación
        val_metrics  = eval_split(clf, Xva, y_val, "VAL (dual-view)")
        test_metrics = eval_split(clf, Xte, y_test, "TEST (dual-view, fijo)")

        seed_results.append({
            "model": name,
            "seed": seed,
            "val_f1_macro":  val_metrics["f1_macro"],
            "val_accuracy":  val_metrics["accuracy"],
            "test_f1_macro": test_metrics["f1_macro"],
            "test_accuracy": test_metrics["accuracy"],
        })

    return pd.DataFrame(seed_results)

In [ ]:
def experiment_dualview_from_df_multi_seed(
        df_trainval,
        df_test,
        raw_field="text",
        masked_field="text_masked",
        seeds=[1,2,3,4,5],
        val_size=0.10,
        ngram_range=(1,3),
        min_df=3,
        max_df=0.90,
        max_features=None):

    all_runs = []

    print("=====================================")
    print(" Ejecutando Seeds (dual-view):", seeds)
    print(" raw_field   :", raw_field)
    print(" masked_field:", masked_field)
    print("=====================================")

    for sd in seeds:
        print(f"\n##### SEED = {sd} #####\n")
        df_seed = _single_seed_experiment_dualview(
            df_trainval.copy(),
            df_test.copy(),
            raw_field=raw_field,
            masked_field=masked_field,
            seed=sd,
            val_size=val_size,
            ngram_range=ngram_range,
            min_df=min_df,
            max_df=max_df,
            max_features=max_features
        )
        all_runs.append(df_seed)

    df_all = pd.concat(all_runs, ignore_index=True)

    # ============================
    #  Aggregate by model (95% CI)
    # ============================
    rows = []
    for model, sub in df_all.groupby("model"):
        mean_val, std_val, lo_val, hi_val = ci95(sub["val_f1_macro"])
        mean_te, std_te, lo_te, hi_te = ci95(sub["test_f1_macro"])
I
        rows.append({
            "model": model,
            "val_f1_macro_mean":    mean_val,
            "val_f1_macro_std":     std_val,
            "val_f1_macro_CI_low":  lo_val,
            "val_f1_macro_CI_high": hi_val,

            "test_f1_macro_mean":    mean_te,
            "test_f1_macro_std":     std_te,
            "test_f1_macro_CI_low":  lo_te,
            "test_f1_macro_CI_high": hi_te,
        })

    df_summary = pd.DataFrame(rows).sort_values(
        by="val_f1_macro_mean", ascending=False
    )

    print("\n=====================================")
    print("Resumen Multi-Seed (dual-view, 95% CI)")
    print("=====================================")
    print(df_summary.to_string(index=False))

    return df_all, df_summary

In [47]:
INPUT_JSONL = "supertweeteval/merged_masked_unionv2.jsonl"
TEST_JSONL = "supertweeteval/test_split_only_originals.jsonl"

#INPUT_JSONL = "supertweeteval/broken_phone/balanced_with_broken_phone_supertweetevalv3.jsonl"

my_train_df = load_and_clean_tweethate(INPUT_JSONL, text_field="text_masked")
my_train_df = remove_values_from_column(my_train_df, "predicted_hate_category", ["hate_age"])
my_train_df = collapse_race_into_origin(my_train_df, col="predicted_hate_category")

my_test_df = load_and_clean_tweethate(TEST_JSONL, text_field="text_masked")
my_test_df = remove_values_from_column(my_test_df, "predicted_hate_category", ["hate_age"])
my_test_df = collapse_race_into_origin(my_test_df, col="predicted_hate_category")

df_all_dual, df_summary_dual = experiment_dualview_from_df_multi_seed(
    df_trainval=my_train_df,
    df_test=my_test_df,
    raw_field="text",          # o el campo que uses para raw
    masked_field="text_masked",
    seeds=[7, 11, 13, 17, 19],
)

df_summary_dual

=====================================
 Ejecutando Seeds (dual-view): [7, 11, 13, 17, 19]
 raw_field   : text
 masked_field: text_masked
=====================================

##### SEED = 7 #####


====================================================================================================
Entrenando (dual-view): logreg_ovr  — seed=7

=== VAL (dual-view) ===
              precision    recall  f1-score   support

           0     0.3333    1.0000    0.5000         2
           1     0.9403    0.8182    0.8750        77
           2     0.9104    0.8592    0.8841        71
           3     0.7500    0.9130    0.8235        23
           4     0.8000    0.9600    0.8727        25

    accuracy                         0.8636       198
   macro avg     0.7468    0.9101    0.7911       198
weighted avg     0.8836    0.8636    0.8682       198

Confusion matrix:
 [[ 2  0  0  0  0]
 [ 2 63  6  2  4]
 [ 2  2 61  5  1]
 [ 0  1  0 21  1]
 [ 0  1  0  0 24]]
F1-macro: 0.7911
Accuracy: 0.8636

=== TEST (dual-view, fijo) ===
              precision    recall  f1-score   support

           0     0.3333    1.0000    0.5000         1
           1     0.8750    0.8537    0.8642        41
           2     0.9032    0.7568    0.8235        37
           3     0.6250    0.8333    0.7143        12
           4     0.8571    0.9231    0.8889        13

    accuracy                         0.8269       104
   macro avg     0.7187    0.8734    0.7582       104
weighted avg     0.8488    0.8269    0.8320       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 35  2  2  2]
 [ 2  3 28  4  0]
 [ 0  1  1 10  0]
 [ 0  1  0  0 12]]
F1-macro: 0.7582
Accuracy: 0.8269

====================================================================================================
Entrenando (dual-view): linear_svm  — seed=7

=== VAL (dual-view) ===
              precision    recall  f1-score   support

           0     0.5000    0.5000    0.5000         2
           1     0.9444    0.8831    0.9128        77
           2     0.9167    0.9296    0.9231        71
           3     0.8400    0.9130    0.8750        23
           4     0.8889    0.9600    0.9231        25

    accuracy                         0.9091       198
   macro avg     0.8180    0.8371    0.8268       198
weighted avg     0.9108    0.9091    0.9092       198

Confusion matrix:
 [[ 1  0  1  0  0]
 [ 1 68  5  2  1]
 [ 0  2 66  2  1]
 [ 0  1  0 21  1]
 [ 0  1  0  0 24]]
F1-macro: 0.8268
Accuracy: 0.9091

=== TEST (dual-view, fijo) ===
              precision    recall  f1-score   support

           0     0.5000    1.0000    0.6667         1
           1     0.9048    0.9268    0.9157        41
           2     0.9118    0.8378    0.8732        37
           3     0.6667    0.6667    0.6667        12
           4     0.8571    0.9231    0.8889        13

    accuracy                         0.8654       104
   macro avg     0.7681    0.8709    0.8022       104
weighted avg     0.8699    0.8654    0.8661       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 38  1  1  1]
 [ 1  2 31  3  0]
 [ 0  1  2  8  1]
 [ 0  1  0  0 12]]
F1-macro: 0.8022
Accuracy: 0.8654

====================================================================================================
Entrenando (dual-view): sgd_log  — seed=7

=== VAL (dual-view) ===
              precision    recall  f1-score   support

           0     0.2500    0.5000    0.3333         2
           1     0.9306    0.8701    0.8993        77
           2     0.9041    0.9296    0.9167        71
           3     0.8333    0.8696    0.8511        23
           4     0.9200    0.9200    0.9200        25

    accuracy                         0.8939       198
   macro avg     0.7676    0.8179    0.7841       198
weighted avg     0.9016    0.8939    0.8968       198

Confusion matrix:
 [[ 1  0  1  0  0]
 [ 2 67  6  1  1]
 [ 0  2 66  3  0]
 [ 0  2  0 20  1]
 [ 1  1  0  0 23]]
F1-macro: 0.7841
Accuracy: 0.8939

=== TEST (dual-view, fijo) ===
              precision    recall  f1-score   support

           0     0.5000    1.0000    0.6667         1
           1     0.9048    0.9268    0.9157        41
           2     0.8611    0.8378    0.8493        37
           3     0.7000    0.5833    0.6364        12
           4     0.8571    0.9231    0.8889        13

    accuracy                         0.8558       104
   macro avg     0.7646    0.8542    0.7914       104
weighted avg     0.8558    0.8558    0.8541       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 38  2  0  1]
 [ 1  2 31  3  0]
 [ 0  1  3  7  1]
 [ 0  1  0  0 12]]
F1-macro: 0.7914
Accuracy: 0.8558

====================================================================================================
Entrenando (dual-view): passive_aggressive  — seed=7

=== VAL (dual-view) ===
              precision    recall  f1-score   support

           0     0.0000    0.0000    0.0000         2
           1     0.9041    0.8571    0.8800        77
           2     0.8784    0.9155    0.8966        71
           3     0.8400    0.9130    0.8750        23
           4     0.9600    0.9600    0.9600        25

    accuracy                         0.8889       198
   macro avg     0.7165    0.7291    0.7223       198
weighted avg     0.8854    0.8889    0.8866       198

Confusion matrix:
 [[ 0  1  1  0  0]
 [ 1 66  8  2  0]
 [ 0  4 65  2  0]
 [ 0  1  0 21  1]
 [ 0  1  0  0 24]]
F1-macro: 0.7223
Accuracy: 0.8889

=== TEST (dual-view, fijo) ===
              precision    recall  f1-score   support

           0     0.5000    1.0000    0.6667         1
           1     0.8444    0.9268    0.8837        41
           2     0.8529    0.7838    0.8169        37
           3     0.6667    0.5000    0.5714        12
           4     0.8571    0.9231    0.8889        13

    accuracy                         0.8269       104
   macro avg     0.7442    0.8267    0.7655       104
weighted avg     0.8252    0.8269    0.8225       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 38  2  0  1]
 [ 1  4 29  3  0]
 [ 0  2  3  6  1]
 [ 0  1  0  0 12]]
F1-macro: 0.7655
Accuracy: 0.8269

====================================================================================================
Entrenando (dual-view): complement_nb  — seed=7

=== VAL (dual-view) ===
              precision    recall  f1-score   support

           0     0.1818    1.0000    0.3077         2
           1     0.9492    0.7273    0.8235        77
           2     0.8983    0.7465    0.8154        71
           3     0.6571    1.0000    0.7931        23
           4     0.7059    0.9600    0.8136        25

    accuracy                         0.7980       198
   macro avg     0.6785    0.8868    0.7107       198
weighted avg     0.8585    0.7980    0.8106       198

Confusion matrix:
 [[ 2  0  0  0  0]
 [ 5 56  6  2  8]
 [ 4  2 53 10  2]
 [ 0  0  0 23  0]
 [ 0  1  0  0 24]]
F1-macro: 0.7107
Accuracy: 0.7980

/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1281: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1296: FutureWarning: Using the 'liblinear' solver for multiclass classification is deprecated. An error will be raised in 1.8. Either use another solver which supports the multinomial loss or wrap the estimator in a OneVsRestClassifier to keep applying a one-versus-rest scheme.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1305: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 32.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1281: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1296: FutureWarning: Using the 'liblinear' solver for multiclass classification is deprecated. An error will be raised in 1.8. Either use another solver which supports the multinomial loss or wrap the estimator in a OneVsRestClassifier to keep applying a one-versus-rest scheme.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1305: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 32.
  warnings.warn(

=== TEST (dual-view, fijo) ===
              precision    recall  f1-score   support

           0     0.3333    1.0000    0.5000         1
           1     0.9211    0.8537    0.8861        41
           2     0.9643    0.7297    0.8308        37
           3     0.5000    0.7500    0.6000        12
           4     0.7647    1.0000    0.8667        13

    accuracy                         0.8173       104
   macro avg     0.6967    0.8667    0.7367       104
weighted avg     0.8627    0.8173    0.8273       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 35  1  3  2]
 [ 2  2 27  6  0]
 [ 0  1  0  9  2]
 [ 0  0  0  0 13]]
F1-macro: 0.7367
Accuracy: 0.8173

##### SEED = 11 #####


====================================================================================================
Entrenando (dual-view): logreg_ovr  — seed=11

=== VAL (dual-view) ===
              precision    recall  f1-score   support

           0     0.2500    0.5000    0.3333         2
           1     0.9706    0.8571    0.9103        77
           2     0.9841    0.8732    0.9254        71
           3     0.7188    1.0000    0.8364        23
           4     0.7742    0.9600    0.8571        25

    accuracy                         0.8889       198
   macro avg     0.7395    0.8381    0.7725       198
weighted avg     0.9141    0.8889    0.8946       198

Confusion matrix:
 [[ 1  0  0  1  0]
 [ 2 66  1  2  6]
 [ 1  2 62  5  1]
 [ 0  0  0 23  0]
 [ 0  0  0  1 24]]
F1-macro: 0.7725
Accuracy: 0.8889

=== TEST (dual-view, fijo) ===
              precision    recall  f1-score   support

           0     0.2500    1.0000    0.4000         1
           1     0.9000    0.8780    0.8889        41
           2     0.9032    0.7568    0.8235        37
           3     0.5714    0.6667    0.6154        12
           4     0.8000    0.9231    0.8571        13

    accuracy                         0.8173       104
   macro avg     0.6849    0.8449    0.7170       104
weighted avg     0.8445    0.8173    0.8254       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 36  2  1  2]
 [ 2  2 28  5  0]
 [ 1  1  1  8  1]
 [ 0  1  0  0 12]]
F1-macro: 0.7170
Accuracy: 0.8173

====================================================================================================
Entrenando (dual-view): linear_svm  — seed=11

=== VAL (dual-view) ===
              precision    recall  f1-score   support

           0     0.5000    0.5000    0.5000         2
           1     0.9444    0.8831    0.9128        77
           2     0.9167    0.9296    0.9231        71
           3     0.8261    0.8261    0.8261        23
           4     0.8276    0.9600    0.8889        25

    accuracy                         0.8990       198
   macro avg     0.8030    0.8198    0.8102       198
weighted avg     0.9015    0.8990    0.8992       198

Confusion matrix:
 [[ 1  0  1  0  0]
 [ 1 68  2  1  5]
 [ 0  3 66  2  0]
 [ 0  1  3 19  0]
 [ 0  0  0  1 24]]
F1-macro: 0.8102
Accuracy: 0.8990

=== TEST (dual-view, fijo) ===
              precision    recall  f1-score   support

           0     0.3333    1.0000    0.5000         1
           1     0.8780    0.8780    0.8780        41
           2     0.8889    0.8649    0.8767        37
           3     0.8000    0.6667    0.7273        12
           4     0.8571    0.9231    0.8889        13

    accuracy                         0.8558       104
   macro avg     0.7515    0.8665    0.7742       104
weighted avg     0.8650    0.8558    0.8579       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 36  3  1  1]
 [ 1  3 32  1  0]
 [ 1  1  1  8  1]
 [ 0  1  0  0 12]]
F1-macro: 0.7742
Accuracy: 0.8558

====================================================================================================
Entrenando (dual-view): sgd_log  — seed=11

=== VAL (dual-view) ===
              precision    recall  f1-score   support

           0     0.5000    0.5000    0.5000         2
           1     0.9315    0.8831    0.9067        77
           2     0.9167    0.9296    0.9231        71
           3     0.8636    0.8261    0.8444        23
           4     0.8276    0.9600    0.8889        25

    accuracy                         0.8990       198
   macro avg     0.8079    0.8198    0.8126       198
weighted avg     0.9008    0.8990    0.8990       198

Confusion matrix:
 [[ 1  0  1  0  0]
 [ 1 68  2  1  5]
 [ 0  4 66  1  0]
 [ 0  1  3 19  0]
 [ 0  0  0  1 24]]
F1-macro: 0.8126
Accuracy: 0.8990

=== TEST (dual-view, fijo) ===
              precision    recall  f1-score   support

           0     0.3333    1.0000    0.5000         1
           1     0.8810    0.9024    0.8916        41
           2     0.8857    0.8378    0.8611        37
           3     0.7000    0.5833    0.6364        12
           4     0.8571    0.9231    0.8889        13

    accuracy                         0.8462       104
   macro avg     0.7314    0.8493    0.7556       104
weighted avg     0.8535    0.8462    0.8472       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 37  2  1  1]
 [ 1  3 31  2  0]
 [ 1  1  2  7  1]
 [ 0  1  0  0 12]]
F1-macro: 0.7556
Accuracy: 0.8462

====================================================================================================
Entrenando (dual-view): passive_aggressive  — seed=11

=== VAL (dual-view) ===
              precision    recall  f1-score   support

           0     0.5000    0.5000    0.5000         2
           1     0.9200    0.8961    0.9079        77
           2     0.8933    0.9437    0.9178        71
           3     0.9444    0.7391    0.8293        23
           4     0.8571    0.9600    0.9057        25

    accuracy                         0.8990       198
   macro avg     0.8230    0.8078    0.8121       198
weighted avg     0.9011    0.8990    0.8979       198

Confusion matrix:
 [[ 1  0  1  0  0]
 [ 1 69  3  0  4]
 [ 0  4 67  0  0]
 [ 0  2  4 17  0]
 [ 0  0  0  1 24]]
F1-macro: 0.8121
Accuracy: 0.8990

=== TEST (dual-view, fijo) ===
              precision    recall  f1-score   support

           0     0.5000    1.0000    0.6667         1
           1     0.8605    0.9024    0.8810        41
           2     0.8889    0.8649    0.8767        37
           3     0.7778    0.5833    0.6667        12
           4     0.8571    0.9231    0.8889        13

    accuracy                         0.8558       104
   macro avg     0.7769    0.8547    0.7960       104
weighted avg     0.8572    0.8558    0.8537       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 37  3  0  1]
 [ 0  3 32  2  0]
 [ 1  2  1  7  1]
 [ 0  1  0  0 12]]
F1-macro: 0.7960
Accuracy: 0.8558

====================================================================================================
Entrenando (dual-view): complement_nb  — seed=11

=== VAL (dual-view) ===
              precision    recall  f1-score   support

           0     0.1250    0.5000    0.2000         2
           1     0.9273    0.6623    0.7727        77
           2     0.9206    0.8169    0.8657        71
           3     0.6765    1.0000    0.8070        23
           4     0.6316    0.9600    0.7619        25

    accuracy                         0.7929       198
   macro avg     0.6562    0.7878    0.6815       198
weighted avg     0.8503    0.7929    0.8029       198

Confusion matrix:
 [[ 1  1  0  0  0]
 [ 5 51  5  4 12]
 [ 2  3 58  6  2]
 [ 0  0  0 23  0]
 [ 0  0  0  1 24]]
F1-macro: 0.6815
Accuracy: 0.7929

=== TEST (dual-view, fijo) ===
              precision    recall  f1-score   support

           0     0.2500    1.0000    0.4000         1
           1     0.9444    0.8293    0.8831        41
           2     0.8929    0.6757    0.7692        37
           3     0.5556    0.8333    0.6667        12
           4     0.7222    1.0000    0.8387        13

    accuracy                         0.7981       104
   macro avg     0.6730    0.8677    0.7115       104
weighted avg     0.8468    0.7981    0.8074       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 34  3  2  2]
 [ 2  2 25  6  2]
 [ 1  0  0 10  1]
 [ 0  0  0  0 13]]
F1-macro: 0.7115
Accuracy: 0.7981

##### SEED = 13 #####


====================================================================================================
Entrenando (dual-view): logreg_ovr  — seed=13

=== VAL (dual-view) ===
              precision    recall  f1-score   support

           0     0.2500    0.5000    0.3333         2
           1     0.8961    0.8961    0.8961        77
           2     0.9524    0.8451    0.8955        71
           3     0.7308    0.8261    0.7755        23
           4     0.7500    0.8400    0.7925        25

    accuracy                         0.8586       198
   macro avg     0.7159    0.7815    0.7386       198
weighted avg     0.8721    0.8586    0.8631       198

Confusion matrix:
 [[ 1  0  1  0  0]
 [ 1 69  1  0  6]
 [ 2  2 60  7  0]
 [ 0  3  0 19  1]
 [ 0  3  1  0 21]]
F1-macro: 0.7386
Accuracy: 0.8586

=== TEST (dual-view, fijo) ===
              precision    recall  f1-score   support

           0     0.2500    1.0000    0.4000         1
           1     0.9024    0.9024    0.9024        41
           2     0.8750    0.7568    0.8116        37
           3     0.5833    0.5833    0.5833        12
           4     0.8000    0.9231    0.8571        13

    accuracy                         0.8173       104
   macro avg     0.6822    0.8331    0.7109       104
weighted avg     0.8368    0.8173    0.8228       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 37  2  0  2]
 [ 2  2 28  5  0]
 [ 1  1  2  7  1]
 [ 0  1  0  0 12]]
F1-macro: 0.7109
Accuracy: 0.8173

====================================================================================================
Entrenando (dual-view): linear_svm  — seed=13

=== VAL (dual-view) ===
              precision    recall  f1-score   support

           0     0.5000    0.5000    0.5000         2
           1     0.8987    0.9221    0.9103        77
           2     0.9552    0.9014    0.9275        71
           3     0.8261    0.8261    0.8261        23
           4     0.7778    0.8400    0.8077        25

    accuracy                         0.8889       198
   macro avg     0.7916    0.7979    0.7943       198
weighted avg     0.8913    0.8889    0.8896       198

Confusion matrix:
 [[ 1  0  1  0  0]
 [ 0 71  1  0  5]
 [ 1  2 64  4  0]
 [ 0  3  0 19  1]
 [ 0  3  1  0 21]]
F1-macro: 0.7943
Accuracy: 0.8889

=== TEST (dual-view, fijo) ===
              precision    recall  f1-score   support

           0     0.3333    1.0000    0.5000         1
           1     0.8837    0.9268    0.9048        41
           2     0.8889    0.8649    0.8767        37
           3     0.8750    0.5833    0.7000        12
           4     0.8571    0.9231    0.8889        13

    accuracy                         0.8654       104
   macro avg     0.7676    0.8596    0.7741       104
weighted avg     0.8759    0.8654    0.8653       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 38  2  0  1]
 [ 1  3 32  1  0]
 [ 1  1  2  7  1]
 [ 0  1  0  0 12]]
F1-macro: 0.7741
Accuracy: 0.8654

====================================================================================================
Entrenando (dual-view): sgd_log  — seed=13

=== VAL (dual-view) ===
              precision    recall  f1-score   support

           0     0.5000    0.5000    0.5000         2
           1     0.8974    0.9091    0.9032        77
           2     0.9412    0.9014    0.9209        71
           3     0.8261    0.8261    0.8261        23
           4     0.7778    0.8400    0.8077        25

    accuracy                         0.8838       198
   macro avg     0.7885    0.7953    0.7916       198
weighted avg     0.8857    0.8838    0.8845       198

Confusion matrix:
 [[ 1  0  1  0  0]
 [ 0 70  2  0  5]
 [ 1  2 64  4  0]
 [ 0  3  0 19  1]
 [ 0  3  1  0 21]]
F1-macro: 0.7916
Accuracy: 0.8838

=== TEST (dual-view, fijo) ===
              precision    recall  f1-score   support

           0     0.3333    1.0000    0.5000         1
           1     0.8864    0.9512    0.9176        41
           2     0.8889    0.8649    0.8767        37
           3     0.8750    0.5833    0.7000        12
           4     0.9231    0.9231    0.9231        13

    accuracy                         0.8750       104
   macro avg     0.7813    0.8645    0.7835       104
weighted avg     0.8852    0.8750    0.8746       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 39  2  0  0]
 [ 1  3 32  1  0]
 [ 1  1  2  7  1]
 [ 0  1  0  0 12]]
F1-macro: 0.7835
Accuracy: 0.8750

====================================================================================================
Entrenando (dual-view): passive_aggressive  — seed=13

=== VAL (dual-view) ===
              precision    recall  f1-score   support

           0     1.0000    0.5000    0.6667         2
           1     0.8974    0.9091    0.9032        77
           2     0.9054    0.9437    0.9241        71
           3     0.9444    0.7391    0.8293        23
           4     0.7778    0.8400    0.8077        25

    accuracy                         0.8889       198
   macro avg     0.9050    0.7864    0.8262       198
weighted avg     0.8917    0.8889    0.8877       198

Confusion matrix:
 [[ 1  0  1  0  0]
 [ 0 70  2  0  5]
 [ 0  3 67  1  0]
 [ 0  2  3 17  1]
 [ 0  3  1  0 21]]
F1-macro: 0.8262
Accuracy: 0.8889

=== TEST (dual-view, fijo) ===
              precision    recall  f1-score   support

           0     0.3333    1.0000    0.5000         1
           1     0.8864    0.9512    0.9176        41
           2     0.8649    0.8649    0.8649        37
           3     0.8571    0.5000    0.6316        12
           4     0.9231    0.9231    0.9231        13

    accuracy                         0.8654       104
   macro avg     0.7730    0.8478    0.7674       104
weighted avg     0.8746    0.8654    0.8625       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 39  2  0  0]
 [ 1  3 32  1  0]
 [ 1  1  3  6  1]
 [ 0  1  0  0 12]]
F1-macro: 0.7674
Accuracy: 0.8654

====================================================================================================
Entrenando (dual-view): complement_nb  — seed=13

=== VAL (dual-view) ===
              precision    recall  f1-score   support

           0     0.1111    0.5000    0.1818         2
           1     0.9254    0.8052    0.8611        77
           2     0.9310    0.7606    0.8372        71
           3     0.6250    0.8696    0.7273        23
           4     0.6562    0.8400    0.7368        25

    accuracy                         0.7980       198
   macro avg     0.6498    0.7551    0.6689       198
weighted avg     0.8503    0.7980    0.8144       198

Confusion matrix:
 [[ 1  0  1  0  0]
 [ 4 62  1  2  8]
 [ 4  2 54 10  1]
 [ 0  0  1 20  2]
 [ 0  3  1  0 21]]
F1-macro: 0.6689
Accuracy: 0.7980

=== TEST (dual-view, fijo) ===
              precision    recall  f1-score   support

           0     0.2000    1.0000    0.3333         1
           1     0.9444    0.8293    0.8831        41
           2     0.8966    0.7027    0.7879        37
           3     0.5882    0.8333    0.6897        12
           4     0.7647    1.0000    0.8667        13

    accuracy                         0.8077       104
   macro avg     0.6788    0.8731    0.7121       104
weighted avg     0.8567    0.8077    0.8196       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 1 34  3  2  1]
 [ 2  2 26  5  2]
 [ 1  0  0 10  1]
 [ 0  0  0  0 13]]
F1-macro: 0.7121
Accuracy: 0.8077

##### SEED = 17 #####


====================================================================================================
Entrenando (dual-view): logreg_ovr  — seed=17

=== VAL (dual-view) ===
              precision    recall  f1-score   support

           0     0.5000    1.0000    0.6667         2
           1     0.9459    0.9091    0.9272        77
           2     0.9688    0.8732    0.9185        71
           3     0.7333    0.9565    0.8302        23
           4     0.8462    0.8800    0.8627        25

    accuracy                         0.8990       198
   macro avg     0.7988    0.9238    0.8411       198
weighted avg     0.9123    0.8990    0.9020       198

Confusion matrix:
 [[ 2  0  0  0  0]
 [ 1 70  2  1  3]
 [ 1  2 62  6  0]
 [ 0  0  0 22  1]
 [ 0  2  0  1 22]]
F1-macro: 0.8411
Accuracy: 0.8990

=== TEST (dual-view, fijo) ===
              precision    recall  f1-score   support

           0     0.3333    1.0000    0.5000         1
           1     0.9000    0.8780    0.8889        41
           2     0.8710    0.7297    0.7941        37
           3     0.5333    0.6667    0.5926        12
           4     0.8000    0.9231    0.8571        13

    accuracy                         0.8077       104
   macro avg     0.6875    0.8395    0.7265       104
weighted avg     0.8294    0.8077    0.8133       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 36  2  1  2]
 [ 2  2 27  6  0]
 [ 0  1  2  8  1]
 [ 0  1  0  0 12]]
F1-macro: 0.7265
Accuracy: 0.8077

====================================================================================================
Entrenando (dual-view): linear_svm  — seed=17

=== VAL (dual-view) ===
              precision    recall  f1-score   support

           0     0.5000    0.5000    0.5000         2
           1     0.9481    0.9481    0.9481        77
           2     0.9559    0.9155    0.9353        71
           3     0.7931    1.0000    0.8846        23
           4     1.0000    0.8800    0.9362        25

    accuracy                         0.9293       198
   macro avg     0.8394    0.8487    0.8408       198
weighted avg     0.9349    0.9293    0.9301       198

Confusion matrix:
 [[ 1  0  1  0  0]
 [ 1 73  2  1  0]
 [ 0  2 65  4  0]
 [ 0  0  0 23  0]
 [ 0  2  0  1 22]]
F1-macro: 0.8408
Accuracy: 0.9293

=== TEST (dual-view, fijo) ===
              precision    recall  f1-score   support

           0     0.5000    1.0000    0.6667         1
           1     0.9000    0.8780    0.8889        41
           2     0.8421    0.8649    0.8533        37
           3     0.7000    0.5833    0.6364        12
           4     0.8571    0.9231    0.8889        13

    accuracy                         0.8462       104
   macro avg     0.7598    0.8499    0.7868       104
weighted avg     0.8471    0.8462    0.8450       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 36  3  1  1]
 [ 1  2 32  2  0]
 [ 0  1  3  7  1]
 [ 0  1  0  0 12]]
F1-macro: 0.7868
Accuracy: 0.8462

====================================================================================================
Entrenando (dual-view): sgd_log  — seed=17

=== VAL (dual-view) ===
              precision    recall  f1-score   support

           0     0.6667    1.0000    0.8000         2
           1     0.9481    0.9481    0.9481        77
           2     0.9701    0.9155    0.9420        71
           3     0.7857    0.9565    0.8627        23
           4     0.9565    0.8800    0.9167        25

    accuracy                         0.9293       198
   macro avg     0.8654    0.9400    0.8939       198
weighted avg     0.9353    0.9293    0.9305       198

Confusion matrix:
 [[ 2  0  0  0  0]
 [ 1 73  2  1  0]
 [ 0  2 65  4  0]
 [ 0  0  0 22  1]
 [ 0  2  0  1 22]]
F1-macro: 0.8939
Accuracy: 0.9293

=== TEST (dual-view, fijo) ===
              precision    recall  f1-score   support

           0     0.5000    1.0000    0.6667         1
           1     0.9048    0.9268    0.9157        41
           2     0.8611    0.8378    0.8493        37
           3     0.7000    0.5833    0.6364        12
           4     0.8571    0.9231    0.8889        13

    accuracy                         0.8558       104
   macro avg     0.7646    0.8542    0.7914       104
weighted avg     0.8558    0.8558    0.8541       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 38  2  0  1]
 [ 1  2 31  3  0]
 [ 0  1  3  7  1]
 [ 0  1  0  0 12]]
F1-macro: 0.7914
Accuracy: 0.8558

====================================================================================================

/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1281: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1296: FutureWarning: Using the 'liblinear' solver for multiclass classification is deprecated. An error will be raised in 1.8. Either use another solver which supports the multinomial loss or wrap the estimator in a OneVsRestClassifier to keep applying a one-versus-rest scheme.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1305: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 32.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1281: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1296: FutureWarning: Using the 'liblinear' solver for multiclass classification is deprecated. An error will be raised in 1.8. Either use another solver which supports the multinomial loss or wrap the estimator in a OneVsRestClassifier to keep applying a one-versus-rest scheme.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1305: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 32.
  warnings.warn(

=== VAL (dual-view) ===
              precision    recall  f1-score   support

           0     0.5000    0.5000    0.5000         2
           1     0.9231    0.9351    0.9290        77
           2     0.9275    0.9014    0.9143        71
           3     0.8214    1.0000    0.9020        23
           4     1.0000    0.8400    0.9130        25

    accuracy                         0.9141       198
   macro avg     0.8344    0.8353    0.8317       198
weighted avg     0.9183    0.9141    0.9142       198

Confusion matrix:
 [[ 1  0  1  0  0]
 [ 1 72  3  1  0]
 [ 0  4 64  3  0]
 [ 0  0  0 23  0]
 [ 0  2  1  1 21]]
F1-macro: 0.8317
Accuracy: 0.9141

=== TEST (dual-view, fijo) ===
              precision    recall  f1-score   support

           0     0.5000    1.0000    0.6667         1
           1     0.8810    0.9024    0.8916        41
           2     0.8750    0.9459    0.9091        37
           3     0.8571    0.5000    0.6316        12
           4     0.8462    0.8462    0.8462        13

    accuracy                         0.8654       104
   macro avg     0.7918    0.8389    0.7890       104
weighted avg     0.8681    0.8654    0.8600       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 37  2  1  1]
 [ 1  1 35  0  0]
 [ 0  2  3  6  1]
 [ 0  2  0  0 11]]
F1-macro: 0.7890
Accuracy: 0.8654

====================================================================================================
Entrenando (dual-view): complement_nb  — seed=17

=== VAL (dual-view) ===
              precision    recall  f1-score   support

           0     0.2857    1.0000    0.4444         2
           1     0.9254    0.8052    0.8611        77
           2     0.9434    0.7042    0.8065        71
           3     0.5238    0.9565    0.6769        23
           4     0.7586    0.8800    0.8148        25

    accuracy                         0.7980       198
   macro avg     0.6874    0.8692    0.7207       198
weighted avg     0.8577    0.7980    0.8101       198

Confusion matrix:
 [[ 2  0  0  0  0]
 [ 3 62  2  4  6]
 [ 2  4 50 14  1]
 [ 0  0  1 22  0]
 [ 0  1  0  2 22]]
F1-macro: 0.7207
Accuracy: 0.7980

=== TEST (dual-view, fijo) ===
              precision    recall  f1-score   support

           0     0.2500    1.0000    0.4000         1
           1     0.9429    0.8049    0.8684        41
           2     0.8929    0.6757    0.7692        37
           3     0.5238    0.9167    0.6667        12
           4     0.8125    1.0000    0.8966        13

    accuracy                         0.7981       104
   macro avg     0.6844    0.8794    0.7202       104
weighted avg     0.8538    0.7981    0.8089       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 1 33  3  3  1]
 [ 2  2 25  7  1]
 [ 0  0  0 11  1]
 [ 0  0  0  0 13]]
F1-macro: 0.7202
Accuracy: 0.7981

##### SEED = 19 #####


====================================================================================================
Entrenando (dual-view): logreg_ovr  — seed=19

=== VAL (dual-view) ===
              precision    recall  f1-score   support

           0     0.3333    1.0000    0.5000         2
           1     0.9296    0.8571    0.8919        77
           2     0.8971    0.8592    0.8777        71
           3     0.7500    0.9130    0.8235        23
           4     0.8800    0.8800    0.8800        25

    accuracy                         0.8687       198
   macro avg     0.7580    0.9019    0.7946       198
weighted avg     0.8848    0.8687    0.8734       198

Confusion matrix:
 [[ 2  0  0  0  0]
 [ 2 66  7  1  1]
 [ 2  1 61  6  1]
 [ 0  1  0 21  1]
 [ 0  3  0  0 22]]
F1-macro: 0.7946
Accuracy: 0.8687

=== TEST (dual-view, fijo) ===
              precision    recall  f1-score   support

           0     0.2500    1.0000    0.4000         1
           1     0.9024    0.9024    0.9024        41
           2     0.9062    0.7838    0.8406        37
           3     0.6154    0.6667    0.6400        12
           4     0.8571    0.9231    0.8889        13

    accuracy                         0.8365       104
   macro avg     0.7062    0.8552    0.7344       104
weighted avg     0.8587    0.8365    0.8436       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 37  2  1  1]
 [ 2  2 29  4  0]
 [ 1  1  1  8  1]
 [ 0  1  0  0 12]]
F1-macro: 0.7344
Accuracy: 0.8365

====================================================================================================
Entrenando (dual-view): linear_svm  — seed=19

=== VAL (dual-view) ===
              precision    recall  f1-score   support

           0     0.2500    0.5000    0.3333         2
           1     0.9167    0.8571    0.8859        77
           2     0.8514    0.8873    0.8690        71
           3     0.8333    0.8696    0.8511        23
           4     0.8750    0.8400    0.8571        25

    accuracy                         0.8636       198
   macro avg     0.7453    0.7908    0.7593       198
weighted avg     0.8716    0.8636    0.8666       198

Confusion matrix:
 [[ 1  0  1  0  0]
 [ 2 66  7  0  2]
 [ 1  2 63  4  1]
 [ 0  1  2 20  0]
 [ 0  3  1  0 21]]
F1-macro: 0.7593
Accuracy: 0.8636

=== TEST (dual-view, fijo) ===
              precision    recall  f1-score   support

           0     0.3333    1.0000    0.5000         1
           1     0.8780    0.8780    0.8780        41
           2     0.8889    0.8649    0.8767        37
           3     0.8000    0.6667    0.7273        12
           4     0.8571    0.9231    0.8889        13

    accuracy                         0.8558       104
   macro avg     0.7515    0.8665    0.7742       104
weighted avg     0.8650    0.8558    0.8579       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 36  3  1  1]
 [ 1  3 32  1  0]
 [ 1  1  1  8  1]
 [ 0  1  0  0 12]]
F1-macro: 0.7742
Accuracy: 0.8558

====================================================================================================
Entrenando (dual-view): sgd_log  — seed=19

=== VAL (dual-view) ===
              precision    recall  f1-score   support

           0     0.2500    0.5000    0.3333         2
           1     0.9189    0.8831    0.9007        77
           2     0.8649    0.9014    0.8828        71
           3     0.8696    0.8696    0.8696        23
           4     0.9565    0.8800    0.9167        25

    accuracy                         0.8838       198
   macro avg     0.7720    0.8068    0.7806       198
weighted avg     0.8918    0.8838    0.8869       198

Confusion matrix:
 [[ 1  0  1  0  0]
 [ 2 68  7  0  0]
 [ 1  2 64  3  1]
 [ 0  1  2 20  0]
 [ 0  3  0  0 22]]
F1-macro: 0.7806
Accuracy: 0.8838

=== TEST (dual-view, fijo) ===
              precision    recall  f1-score   support

           0     0.3333    1.0000    0.5000         1
           1     0.8810    0.9024    0.8916        41
           2     0.8889    0.8649    0.8767        37
           3     0.7778    0.5833    0.6667        12
           4     0.8571    0.9231    0.8889        13

    accuracy                         0.8558       104
   macro avg     0.7476    0.8547    0.7648       104
weighted avg     0.8636    0.8558    0.8562       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 37  2  1  1]
 [ 1  3 32  1  0]
 [ 1  1  2  7  1]
 [ 0  1  0  0 12]]
F1-macro: 0.7648
Accuracy: 0.8558

====================================================================================================
Entrenando (dual-view): passive_aggressive  — seed=19

=== VAL (dual-view) ===
              precision    recall  f1-score   support

           0     0.5000    0.5000    0.5000         2
           1     0.9178    0.8701    0.8933        77
           2     0.8571    0.9296    0.8919        71
           3     0.8261    0.8261    0.8261        23
           4     0.9130    0.8400    0.8750        25

    accuracy                         0.8788       198
   macro avg     0.8028    0.7932    0.7973       198
weighted avg     0.8806    0.8788    0.8787       198

Confusion matrix:
 [[ 1  0  0  1  0]
 [ 1 67  7  1  1]
 [ 0  2 66  2  1]
 [ 0  1  3 19  0]
 [ 0  3  1  0 21]]
F1-macro: 0.7973
Accuracy: 0.8788

=== TEST (dual-view, fijo) ===
              precision    recall  f1-score   support

           0     0.5000    1.0000    0.6667         1
           1     0.8372    0.8780    0.8571        41
           2     0.8947    0.9189    0.9067        37
           3     0.8750    0.5833    0.7000        12
           4     0.8462    0.8462    0.8462        13

    accuracy                         0.8558       104
   macro avg     0.7906    0.8453    0.7953       104
weighted avg     0.8599    0.8558    0.8534       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 0 36  3  1  1]
 [ 0  3 34  0  0]
 [ 1  2  1  7  1]
 [ 0  2  0  0 11]]
F1-macro: 0.7953
Accuracy: 0.8558

====================================================================================================
Entrenando (dual-view): complement_nb  — seed=19

=== VAL (dual-view) ===
              precision    recall  f1-score   support

           0     0.1818    1.0000    0.3077         2
           1     0.9219    0.7662    0.8369        77
           2     0.8689    0.7465    0.8030        71
           3     0.6389    1.0000    0.7797        23
           4     0.8077    0.8400    0.8235        25

    accuracy                         0.7980       198
   macro avg     0.6838    0.8705    0.7102       198
weighted avg     0.8481    0.7980    0.8111       198

Confusion matrix:
 [[ 2  0  0  0  0]
 [ 4 59  8  2  4]
 [ 5  3 53  9  1]
 [ 0  0  0 23  0]
 [ 0  2  0  2 21]]
F1-macro: 0.7102
Accuracy: 0.7980

=== TEST (dual-view, fijo) ===
              precision    recall  f1-score   support

           0     0.2500    1.0000    0.4000         1
           1     0.9118    0.7561    0.8267        41
           2     0.8621    0.6757    0.7576        37
           3     0.4737    0.7500    0.5806        12
           4     0.7222    1.0000    0.8387        13

    accuracy                         0.7596       104
   macro avg     0.6439    0.8364    0.6807       104
weighted avg     0.8135    0.7596    0.7711       104

Confusion matrix:
 [[ 1  0  0  0  0]
 [ 1 31  4  3  2]
 [ 1  3 25  7  1]
 [ 1  0  0  9  2]
 [ 0  0  0  0 13]]
F1-macro: 0.6807
Accuracy: 0.7596

=====================================
Resumen Multi-Seed (dual-view, 95% CI)
=====================================
             model  val_f1_macro_mean  val_f1_macro_std  val_f1_macro_CI_low  val_f1_macro_CI_high  test_f1_macro_mean  test_f1_macro_std  test_f1_macro_CI_low  test_f1_macro_CI_high
           sgd_log           0.812553          0.047141             0.771232              0.853874            0.777320           0.016304              0.763028               0.791611
        linear_svm           0.806271          0.031544             0.778621              0.833921            0.782299           0.012419              0.771413               0.793185
passive_aggressive           0.797912          0.044321             0.759063              0.836761            0.782654           0.015031              0.769479               0.795829
        logreg_ovr           0.787567          0.037245             0.754920              0.820214            0.729400           0.018422              0.713253               0.745548
     complement_nb           0.698375          0.022067             0.679032              0.717718            0.712254           0.020343              0.694422               0.730086

/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1281: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1296: FutureWarning: Using the 'liblinear' solver for multiclass classification is deprecated. An error will be raised in 1.8. Either use another solver which supports the multinomial loss or wrap the estimator in a OneVsRestClassifier to keep applying a one-versus-rest scheme.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1305: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 32.
  warnings.warn(

,model,val_f1_macro_mean,val_f1_macro_std,val_f1_macro_CI_low,val_f1_macro_CI_high,test_f1_macro_mean,test_f1_macro_std,test_f1_macro_CI_low,test_f1_macro_CI_high
4,sgd_log,0.812553,0.047141,0.771232,0.853874,0.777320,0.016304,0.763028,0.791611
1,linear_svm,0.806271,0.031544,0.778621,0.833921,0.782299,0.012419,0.771413,0.793185
3,passive_aggressive,0.797912,0.044321,0.759063,0.836761,0.782654,0.015031,0.769479,0.795829
2,logreg_ovr,0.787567,0.037245,0.754920,0.820214,0.729400,0.018422,0.713253,0.745548
0,complement_nb,0.698375,0.022067,0.679032,0.717718,0.712254,0.020343,0.694422,0.730086

In [48]:
df_summary_dual

,model,val_f1_macro_mean,val_f1_macro_std,val_f1_macro_CI_low,val_f1_macro_CI_high,test_f1_macro_mean,test_f1_macro_std,test_f1_macro_CI_low,test_f1_macro_CI_high
4,sgd_log,0.812553,0.047141,0.771232,0.853874,0.777320,0.016304,0.763028,0.791611
1,linear_svm,0.806271,0.031544,0.778621,0.833921,0.782299,0.012419,0.771413,0.793185
3,passive_aggressive,0.797912,0.044321,0.759063,0.836761,0.782654,0.015031,0.769479,0.795829
2,logreg_ovr,0.787567,0.037245,0.754920,0.820214,0.729400,0.018422,0.713253,0.745548
0,complement_nb,0.698375,0.022067,0.679032,0.717718,0.712254,0.020343,0.694422,0.730086

In [46]:
df_summary_dual

,model,val_f1_macro_mean,val_f1_macro_std,val_f1_macro_CI_low,val_f1_macro_CI_high,test_f1_macro_mean,test_f1_macro_std,test_f1_macro_CI_low,test_f1_macro_CI_high
1,linear_svm,0.986012,0.005964,0.980784,0.991240,0.876819,0.036833,0.844533,0.909104
3,passive_aggressive,0.985681,0.008635,0.978112,0.993249,0.882591,0.013909,0.870399,0.894782
4,sgd_log,0.980131,0.008463,0.972712,0.987549,0.827095,0.002755,0.824680,0.829510
2,logreg_ovr,0.973096,0.009082,0.965135,0.981056,0.812155,0.004307,0.808379,0.815930
0,complement_nb,0.948422,0.008715,0.940782,0.956061,0.794841,0.015081,0.781622,0.808060

In [49]:
df_min_remasked

,text,text_masked,predicted_hate_category
0,Fck those niggas,"""""""Fck those [SLUR:RACE_BLACK]""""""",hate_origin
1,@user . Linda Sarsour should already be in jai...,"""""""[MENTION] . Linda Sarsour should already be...",hate_gender
2,Women really should start carrying guns around...,"""""""[GENDER_WOMEN] really should start carrying...",hate_gender
3,@mike_pence @user Just shut your mouth and put...,"""""""[MENTION] [MENTION] Just shut your mouth an...",hate_sexuality
4,Please let that bitch go. Every man done ran i...,"""""""Please let that [SLUR:GENDER_WOMEN] go. Eve...",hate_gender
...,...,...,...
567,@user @user @user @user @user @user Saw this t...,"""""""[SLUR:GENDER_MEN] [SLUR:GENDER_WOMEN] [SLUR...",hate_disability
568,okay but really why are Americans so fucking m...,"""""""okay but really why are [TARGET:NATIONAL_OR...",hate_disability
569,@user what\u2019s wrong with you you fucking r...,"""""""[SLUR:GENDER_MEN] what\u2019s wrong with yo...",hate_disability
570,@user @user @user @user Hell I'd say enticed t...,"""""""[SLUR:GENDER_MEN] [SLUR:GENDER_WOMEN] [SLUR...",hate_disability
571,Hate to give cunts like this the time of day b...,"""""""Hate to give [SLUR:GENDER_MEN] like this th...",hate_disability

In [63]:
#INPUT_JSONL = "supertweeteval/merged_masked_unionv2.jsonl"
TEST_JSONL = "supertweeteval/test_split_only_originals.jsonl"

INPUT_JSONL = "supertweeteval/broken_phone/balanced_with_broken_phone_supertweetevalv3.jsonl"

my_train_df = load_and_clean_tweethate(INPUT_JSONL, text_field="text_masked")
my_train_df = remove_values_from_column(my_train_df, "predicted_hate_category", ["hate_age"])
my_train_df = collapse_race_into_origin(my_train_df, col="predicted_hate_category")

my_test_df = load_and_clean_tweethate(TEST_JSONL, text_field="text_masked")
my_test_df = remove_values_from_column(my_test_df, "predicted_hate_category", ["hate_age"])
my_test_df = collapse_race_into_origin(my_test_df, col="predicted_hate_category")

df_all_dual, df_summary_dual = experiment_dualview_from_df_multi_seed(
    df_trainval=my_train_df,
    df_test=df_min_remasked,
    raw_field="text",          # o el campo que uses para raw
    masked_field="text_masked",
    seeds=[7, 11, 13, 17, 19],
)

df_summary_dual

=====================================
 Ejecutando Seeds (dual-view): [7, 11, 13, 17, 19]
 raw_field   : text
 masked_field: text_masked
=====================================

##### SEED = 7 #####


====================================================================================================
Entrenando (dual-view): logreg_ovr  — seed=7

=== VAL (dual-view) ===
              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000        71
           1     0.9359    0.9733    0.9542        75
           2     1.0000    0.9730    0.9863       148
           3     1.0000    1.0000    1.0000        74
           4     0.9737    0.9867    0.9801        75

    accuracy                         0.9842       443
   macro avg     0.9819    0.9866    0.9841       443
weighted avg     0.9847    0.9842    0.9843       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  0  73   0   0   2]
 [  0   4 144   0   0]
 [  0   0   0  74   0]
 [  0   1   0   0  74]]
F1-macro: 0.9841
Accuracy: 0.9842

=== TEST (dual-view, fijo) ===
              precision    recall  f1-score   support

           0     0.8667    0.3861    0.5342       101
           1     0.4892    0.8014    0.6075       141
           2     0.7143    0.5109    0.5957       137
           3     0.6222    0.3500    0.4480        80
           4     0.6732    0.9115    0.7744       113

    accuracy                         0.6171       572
   macro avg     0.6731    0.5920    0.5920       572
weighted avg     0.6647    0.6171    0.6024       572

Confusion matrix:
 [[ 39  39   6   5  12]
 [  1 113   8   4  15]
 [  2  42  70   8  15]
 [  3  29  12  28   8]
 [  0   8   2   0 103]]
F1-macro: 0.5920
Accuracy: 0.6171

====================================================================================================
Entrenando (dual-view): linear_svm  — seed=7

=== VAL (dual-view) ===
              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000        71
           1     0.9737    0.9867    0.9801        75
           2     0.9932    0.9865    0.9898       148
           3     1.0000    1.0000    1.0000        74
           4     1.0000    1.0000    1.0000        75

    accuracy                         0.9932       443
   macro avg     0.9934    0.9946    0.9940       443
weighted avg     0.9933    0.9932    0.9932       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  0  74   1   0   0]
 [  0   2 146   0   0]
 [  0   0   0  74   0]
 [  0   0   0   0  75]]
F1-macro: 0.9940
Accuracy: 0.9932

=== TEST (dual-view, fijo) ===
              precision    recall  f1-score   support

           0     0.9189    0.3366    0.4928       101
           1     0.5158    0.8085    0.6298       141
           2     0.7000    0.6131    0.6537       137
           3     0.7143    0.3750    0.4918        80
           4     0.6776    0.9115    0.7774       113

    accuracy                         0.6381       572
   macro avg     0.7053    0.6090    0.6091       572
weighted avg     0.6908    0.6381    0.6212       572

Confusion matrix:
 [[ 34  37  13   4  13]
 [  1 114   8   4  14]
 [  1  34  84   4  14]
 [  1  28  13  30   8]
 [  0   8   2   0 103]]
F1-macro: 0.6091
Accuracy: 0.6381

====================================================================================================
Entrenando (dual-view): sgd_log  — seed=7

=== VAL (dual-view) ===
              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000        71
           1     0.9733    0.9733    0.9733        75
           2     0.9932    0.9865    0.9898       148
           3     1.0000    1.0000    1.0000        74
           4     0.9868    1.0000    0.9934        75

    accuracy                         0.9910       443
   macro avg     0.9907    0.9920    0.9913       443
weighted avg     0.9910    0.9910    0.9910       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  0  73   1   0   1]
 [  0   2 146   0   0]
 [  0   0   0  74   0]
 [  0   0   0   0  75]]
F1-macro: 0.9913
Accuracy: 0.9910

=== TEST (dual-view, fijo) ===
              precision    recall  f1-score   support

           0     0.8537    0.3465    0.4930       101
           1     0.5113    0.8014    0.6243       141
           2     0.6949    0.5985    0.6431       137
           3     0.6923    0.3375    0.4538        80
           4     0.6732    0.9115    0.7744       113

    accuracy                         0.6294       572
   macro avg     0.6851    0.5991    0.5977       572
weighted avg     0.6730    0.6294    0.6114       572

Confusion matrix:
 [[ 35  37  13   3  13]
 [  1 113   8   4  15]
 [  2  34  82   5  14]
 [  3  29  13  27   8]
 [  0   8   2   0 103]]
F1-macro: 0.5977
Accuracy: 0.6294

====================================================================================================
Entrenando (dual-view): passive_aggressive  — seed=7

=== VAL (dual-view) ===
              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000        71
           1     0.9867    0.9867    0.9867        75
           2     0.9932    0.9932    0.9932       148
           3     1.0000    1.0000    1.0000        74
           4     1.0000    1.0000    1.0000        75

    accuracy                         0.9955       443
   macro avg     0.9960    0.9960    0.9960       443
weighted avg     0.9955    0.9955    0.9955       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  0  74   1   0   0]
 [  0   1 147   0   0]
 [  0   0   0  74   0]
 [  0   0   0   0  75]]
F1-macro: 0.9960
Accuracy: 0.9955

=== TEST (dual-view, fijo) ===
              precision    recall  f1-score   support

           0     0.8929    0.2475    0.3876       101
           1     0.4978    0.7943    0.6120       141
           2     0.6746    0.6204    0.6464       137
           3     0.7143    0.3750    0.4918        80
           4     0.6623    0.8850    0.7576       113

    accuracy                         0.6154       572
   macro avg     0.6884    0.5844    0.5791       572
weighted avg     0.6727    0.6154    0.5926       572

Confusion matrix:
 [[ 25  43  16   4  13]
 [  1 112   9   4  15]
 [  1  32  85   4  15]
 [  1  26  15  30   8]
 [  0  12   1   0 100]]
F1-macro: 0.5791
Accuracy: 0.6154

====================================================================================================
Entrenando (dual-view): complement_nb  — seed=7

=== VAL (dual-view) ===
              precision    recall  f1-score   support

           0     0.9861    1.0000    0.9930        71
           1     0.8161    0.9467    0.8765        75
           2     1.0000    0.9054    0.9504       148
           3     0.9867    1.0000    0.9933        74
           4     0.9467    0.9467    0.9467        75

    accuracy                         0.9503       443
   macro avg     0.9471    0.9597    0.9520       443
weighted avg     0.9554    0.9503    0.9512       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  0  71   0   0   4]
 [  0  13 134   1   0]
 [  0   0   0  74   0]
 [  1   3   0   0  71]]
F1-macro: 0.9520
Accuracy: 0.9503

=== TEST (dual-view, fijo) ===
              precision    recall  f1-score   support

           0     0.7973    0.5842    0.6743       101
           1     0.5598    0.7305    0.6338       141
           2     0.7568    0.6131    0.6774       137
           3     0.7143    0.4375    0.5426        80
           4     0.6753    0.9204    0.7790       113

    accuracy                         0.6731       572
   macro avg     0.7007    0.6571    0.6614       572
weighted avg     0.6933    0.6731    0.6673       572

Confusion matrix:
 [[ 59  25   7   4   6]
 [  3 103   8   6  21]
 [  4  29  84   4  16]
 [  5  22  11  35   7]
 [  3   5   1   0 104]]
F1-macro: 0.6614
Accuracy: 0.6731

##### SEED = 11 #####

/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1281: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1296: FutureWarning: Using the 'liblinear' solver for multiclass classification is deprecated. An error will be raised in 1.8. Either use another solver which supports the multinomial loss or wrap the estimator in a OneVsRestClassifier to keep applying a one-versus-rest scheme.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1305: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 32.
  warnings.warn(

====================================================================================================
Entrenando (dual-view): logreg_ovr  — seed=11

=== VAL (dual-view) ===
              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000        71
           1     0.8452    0.9467    0.8931        75
           2     0.9858    0.9392    0.9619       148
           3     0.9863    0.9730    0.9796        74
           4     0.9730    0.9600    0.9664        75

    accuracy                         0.9594       443
   macro avg     0.9581    0.9638    0.9602       443
weighted avg     0.9622    0.9594    0.9601       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  0  71   2   0   2]
 [  0   8 139   1   0]
 [  0   2   0  72   0]
 [  0   3   0   0  72]]
F1-macro: 0.9602
Accuracy: 0.9594

=== TEST (dual-view, fijo) ===
              precision    recall  f1-score   support

           0     0.8636    0.3762    0.5241       101
           1     0.4851    0.8085    0.6064       141
           2     0.7391    0.4964    0.5939       137
           3     0.6304    0.3625    0.4603        80
           4     0.6774    0.9292    0.7836       113

    accuracy                         0.6189       572
   macro avg     0.6791    0.5946    0.5937       572
weighted avg     0.6711    0.6189    0.6034       572

Confusion matrix:
 [[ 38  40   6   5  12]
 [  1 114   8   4  14]
 [  2  44  68   8  15]
 [  3  31   8  29   9]
 [  0   6   2   0 105]]
F1-macro: 0.5937
Accuracy: 0.6189

====================================================================================================
Entrenando (dual-view): linear_svm  — seed=11

=== VAL (dual-view) ===
              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000        71
           1     0.9231    0.9600    0.9412        75
           2     0.9862    0.9662    0.9761       148
           3     1.0000    1.0000    1.0000        74
           4     0.9867    0.9867    0.9867        75

    accuracy                         0.9797       443
   macro avg     0.9792    0.9826    0.9808       443
weighted avg     0.9801    0.9797    0.9798       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  0  72   2   0   1]
 [  0   5 143   0   0]
 [  0   0   0  74   0]
 [  0   1   0   0  74]]
F1-macro: 0.9808
Accuracy: 0.9797

=== TEST (dual-view, fijo) ===
              precision    recall  f1-score   support

           0     0.9706    0.3267    0.4889       101
           1     0.5114    0.7943    0.6222       141
           2     0.6885    0.6131    0.6486       137
           3     0.6829    0.3500    0.4628        80
           4     0.6731    0.9292    0.7807       113

    accuracy                         0.6329       572
   macro avg     0.7053    0.6027    0.6006       572
weighted avg     0.6908    0.6329    0.6140       572

Confusion matrix:
 [[ 33  38  13   4  13]
 [  0 112  10   4  15]
 [  0  33  84   5  15]
 [  1  30  13  28   8]
 [  0   6   2   0 105]]
F1-macro: 0.6006
Accuracy: 0.6329

====================================================================================================
Entrenando (dual-view): sgd_log  — seed=11

=== VAL (dual-view) ===
              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000        71
           1     0.8987    0.9467    0.9221        75
           2     0.9861    0.9595    0.9726       148
           3     0.9865    0.9865    0.9865        74
           4     0.9733    0.9733    0.9733        75

    accuracy                         0.9707       443
   macro avg     0.9689    0.9732    0.9709       443
weighted avg     0.9714    0.9707    0.9709       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  0  71   2   0   2]
 [  0   5 142   1   0]
 [  0   1   0  73   0]
 [  0   2   0   0  73]]
F1-macro: 0.9709
Accuracy: 0.9707

=== TEST (dual-view, fijo) ===
              precision    recall  f1-score   support

           0     0.8605    0.3663    0.5139       101
           1     0.5207    0.8014    0.6313       141
           2     0.6949    0.5985    0.6431       137
           3     0.7000    0.3500    0.4667        80
           4     0.6818    0.9292    0.7865       113

    accuracy                         0.6381       572
   macro avg     0.6916    0.6091    0.6083       572
weighted avg     0.6793    0.6381    0.6210       572

Confusion matrix:
 [[ 37  35  13   3  13]
 [  1 113   9   4  14]
 [  2  34  82   5  14]
 [  3  29  12  28   8]
 [  0   6   2   0 105]]
F1-macro: 0.6083
Accuracy: 0.6381

====================================================================================================
Entrenando (dual-view): passive_aggressive  — seed=11

=== VAL (dual-view) ===
              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000        71
           1     0.9333    0.9333    0.9333        75
           2     0.9796    0.9730    0.9763       148
           3     1.0000    1.0000    1.0000        74
           4     0.9737    0.9867    0.9801        75

    accuracy                         0.9774       443
   macro avg     0.9773    0.9786    0.9779       443
weighted avg     0.9774    0.9774    0.9774       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  0  70   3   0   2]
 [  0   4 144   0   0]
 [  0   0   0  74   0]
 [  0   1   0   0  74]]
F1-macro: 0.9779
Accuracy: 0.9774

=== TEST (dual-view, fijo) ===
              precision    recall  f1-score   support

           0     0.9677    0.2970    0.4545       101
           1     0.5347    0.7660    0.6297       141
           2     0.6429    0.6569    0.6498       137
           3     0.6977    0.3750    0.4878        80
           4     0.6731    0.9292    0.7807       113

    accuracy                         0.6346       572
   macro avg     0.7032    0.6048    0.6005       572
weighted avg     0.6872    0.6346    0.6136       572

Confusion matrix:
 [[ 30  36  19   3  13]
 [  0 108  13   5  15]
 [  0  28  90   5  14]
 [  1  25  15  30   9]
 [  0   5   3   0 105]]
F1-macro: 0.6005
Accuracy: 0.6346

====================================================================================================
Entrenando (dual-view): complement_nb  — seed=11

=== VAL (dual-view) ===
              precision    recall  f1-score   support

           0     0.9861    1.0000    0.9930        71
           1     0.7701    0.8933    0.8272        75
           2     0.9773    0.8716    0.9214       148
           3     0.9610    1.0000    0.9801        74
           4     0.9467    0.9467    0.9467        75

    accuracy                         0.9300       443
   macro avg     0.9282    0.9423    0.9337       443
weighted avg     0.9357    0.9300    0.9310       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  0  67   3   1   4]
 [  1  16 129   2   0]
 [  0   0   0  74   0]
 [  0   4   0   0  71]]
F1-macro: 0.9337
Accuracy: 0.9300

=== TEST (dual-view, fijo) ===
              precision    recall  f1-score   support

           0     0.7848    0.6139    0.6889       101
           1     0.5543    0.7234    0.6277       141
           2     0.7714    0.5912    0.6694       137
           3     0.6000    0.4500    0.5143        80
           4     0.6944    0.8850    0.7782       113

    accuracy                         0.6661       572
   macro avg     0.6810    0.6527    0.6557       572
weighted avg     0.6811    0.6661    0.6624       572

Confusion matrix:
 [[ 62  24   5   4   6]
 [  4 102   7  11  17]
 [  4  29  81   8  15]
 [  6  21  11  36   6]
 [  3   8   1   1 100]]
F1-macro: 0.6557
Accuracy: 0.6661

##### SEED = 13 #####

/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1281: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1296: FutureWarning: Using the 'liblinear' solver for multiclass classification is deprecated. An error will be raised in 1.8. Either use another solver which supports the multinomial loss or wrap the estimator in a OneVsRestClassifier to keep applying a one-versus-rest scheme.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1305: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 32.
  warnings.warn(

====================================================================================================
Entrenando (dual-view): logreg_ovr  — seed=13

=== VAL (dual-view) ===
              precision    recall  f1-score   support

           0     0.9861    1.0000    0.9930        71
           1     0.9114    0.9600    0.9351        75
           2     0.9861    0.9595    0.9726       148
           3     1.0000    1.0000    1.0000        74
           4     1.0000    0.9867    0.9933        75

    accuracy                         0.9774       443
   macro avg     0.9767    0.9812    0.9788       443
weighted avg     0.9781    0.9774    0.9776       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  1  72   2   0   0]
 [  0   6 142   0   0]
 [  0   0   0  74   0]
 [  0   1   0   0  74]]
F1-macro: 0.9788
Accuracy: 0.9774

=== TEST (dual-view, fijo) ===
              precision    recall  f1-score   support

           0     0.8696    0.3960    0.5442       101
           1     0.4936    0.8156    0.6150       141
           2     0.7263    0.5036    0.5948       137
           3     0.6170    0.3625    0.4567        80
           4     0.6821    0.9115    0.7803       113

    accuracy                         0.6224       572
   macro avg     0.6777    0.5979    0.5982       572
weighted avg     0.6702    0.6224    0.6082       572

Confusion matrix:
 [[ 40  38   6   5  12]
 [  1 115   8   4  13]
 [  2  42  69   9  15]
 [  3  30  10  29   8]
 [  0   8   2   0 103]]
F1-macro: 0.5982
Accuracy: 0.6224

====================================================================================================
Entrenando (dual-view): linear_svm  — seed=13

=== VAL (dual-view) ===
              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000        71
           1     0.9730    0.9600    0.9664        75
           2     0.9799    0.9865    0.9832       148
           3     1.0000    1.0000    1.0000        74
           4     1.0000    1.0000    1.0000        75

    accuracy                         0.9887       443
   macro avg     0.9906    0.9893    0.9899       443
weighted avg     0.9887    0.9887    0.9887       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  0  72   3   0   0]
 [  0   2 146   0   0]
 [  0   0   0  74   0]
 [  0   0   0   0  75]]
F1-macro: 0.9899
Accuracy: 0.9887

=== TEST (dual-view, fijo) ===
              precision    recall  f1-score   support

           0     0.9487    0.3663    0.5286       101
           1     0.5258    0.7943    0.6328       141
           2     0.6825    0.6277    0.6540       137
           3     0.7179    0.3500    0.4706        80
           4     0.6710    0.9204    0.7761       113

    accuracy                         0.6416       572
   macro avg     0.7092    0.6118    0.6124       572
weighted avg     0.6936    0.6416    0.6251       572

Confusion matrix:
 [[ 37  36  13   3  12]
 [  1 112   9   4  15]
 [  0  31  86   4  16]
 [  1  27  16  28   8]
 [  0   7   2   0 104]]
F1-macro: 0.6124
Accuracy: 0.6416

====================================================================================================
Entrenando (dual-view): sgd_log  — seed=13

=== VAL (dual-view) ===
              precision    recall  f1-score   support

           0     0.9861    1.0000    0.9930        71
           1     0.9600    0.9600    0.9600        75
           2     0.9865    0.9865    0.9865       148
           3     1.0000    1.0000    1.0000        74
           4     1.0000    0.9867    0.9933        75

    accuracy                         0.9865       443
   macro avg     0.9865    0.9866    0.9866       443
weighted avg     0.9865    0.9865    0.9865       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  1  72   2   0   0]
 [  0   2 146   0   0]
 [  0   0   0  74   0]
 [  0   1   0   0  74]]
F1-macro: 0.9866
Accuracy: 0.9865

=== TEST (dual-view, fijo) ===
              precision    recall  f1-score   support

           0     0.8605    0.3663    0.5139       101
           1     0.5253    0.8085    0.6369       141
           2     0.6748    0.6058    0.6385       137
           3     0.7105    0.3375    0.4576        80
           4     0.6821    0.9115    0.7803       113

    accuracy                         0.6364       572
   macro avg     0.6907    0.6059    0.6054       572
weighted avg     0.6772    0.6364    0.6188       572

Confusion matrix:
 [[ 37  34  14   3  13]
 [  1 114   9   4  13]
 [  2  34  83   4  14]
 [  3  27  15  27   8]
 [  0   8   2   0 103]]
F1-macro: 0.6054
Accuracy: 0.6364

====================================================================================================
Entrenando (dual-view): passive_aggressive  — seed=13

=== VAL (dual-view) ===
              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000        71
           1     0.9865    0.9733    0.9799        75
           2     0.9866    0.9932    0.9899       148
           3     1.0000    1.0000    1.0000        74
           4     1.0000    1.0000    1.0000        75

    accuracy                         0.9932       443
   macro avg     0.9946    0.9933    0.9940       443
weighted avg     0.9932    0.9932    0.9932       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  0  73   2   0   0]
 [  0   1 147   0   0]
 [  0   0   0  74   0]
 [  0   0   0   0  75]]
F1-macro: 0.9940
Accuracy: 0.9932

=== TEST (dual-view, fijo) ===
              precision    recall  f1-score   support

           0     0.9143    0.3168    0.4706       101
           1     0.5288    0.7801    0.6304       141
           2     0.6496    0.6496    0.6496       137
           3     0.7368    0.3500    0.4746        80
           4     0.6753    0.9204    0.7790       113

    accuracy                         0.6346       572
   macro avg     0.7010    0.6034    0.6008       572
weighted avg     0.6839    0.6346    0.6143       572

Confusion matrix:
 [[ 32  37  16   3  13]
 [  1 110  11   4  15]
 [  1  30  89   3  14]
 [  1  24  19  28   8]
 [  0   7   2   0 104]]
F1-macro: 0.6008
Accuracy: 0.6346

====================================================================================================
Entrenando (dual-view): complement_nb  — seed=13

=== VAL (dual-view) ===
              precision    recall  f1-score   support

           0     0.9861    1.0000    0.9930        71
           1     0.7889    0.9467    0.8606        75
           2     0.9774    0.8784    0.9253       148
           3     0.9867    1.0000    0.9933        74
           4     1.0000    0.9733    0.9865        75

    accuracy                         0.9458       443
   macro avg     0.9478    0.9597    0.9517       443
weighted avg     0.9523    0.9458    0.9469       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  1  71   3   0   0]
 [  0  17 130   1   0]
 [  0   0   0  74   0]
 [  0   2   0   0  73]]
F1-macro: 0.9517
Accuracy: 0.9458

=== TEST (dual-view, fijo) ===
              precision    recall  f1-score   support

           0     0.8026    0.6040    0.6893       101
           1     0.5455    0.6809    0.6057       141
           2     0.7685    0.6058    0.6776       137
           3     0.6000    0.4500    0.5143        80
           4     0.6645    0.8938    0.7623       113

    accuracy                         0.6591       572
   macro avg     0.6762    0.6469    0.6498       572
weighted avg     0.6754    0.6591    0.6558       572

Confusion matrix:
 [[ 61  24   5   4   7]
 [  3  96   9  12  21]
 [  4  27  83   7  16]
 [  6  20  11  36   7]
 [  2   9   0   1 101]]
F1-macro: 0.6498
Accuracy: 0.6591

##### SEED = 17 #####

/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1281: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1296: FutureWarning: Using the 'liblinear' solver for multiclass classification is deprecated. An error will be raised in 1.8. Either use another solver which supports the multinomial loss or wrap the estimator in a OneVsRestClassifier to keep applying a one-versus-rest scheme.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1305: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 32.
  warnings.warn(

====================================================================================================
Entrenando (dual-view): logreg_ovr  — seed=17

=== VAL (dual-view) ===
              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000        71
           1     0.8987    0.9467    0.9221        75
           2     0.9859    0.9459    0.9655       148
           3     0.9867    1.0000    0.9933        74
           4     0.9737    0.9867    0.9801        75

    accuracy                         0.9707       443
   macro avg     0.9690    0.9759    0.9722       443
weighted avg     0.9715    0.9707    0.9708       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  0  71   2   1   1]
 [  0   7 140   0   1]
 [  0   0   0  74   0]
 [  0   1   0   0  74]]
F1-macro: 0.9722
Accuracy: 0.9707

=== TEST (dual-view, fijo) ===
              precision    recall  f1-score   support

           0     0.8636    0.3762    0.5241       101
           1     0.4893    0.8085    0.6096       141
           2     0.6837    0.4891    0.5702       137
           3     0.6364    0.3500    0.4516        80
           4     0.6797    0.9204    0.7820       113

    accuracy                         0.6136       572
   macro avg     0.6705    0.5888    0.5875       572
weighted avg     0.6601    0.6136    0.5970       572

Confusion matrix:
 [[ 38  38   8   4  13]
 [  1 114   8   4  14]
 [  2  45  67   8  15]
 [  3  29  13  28   7]
 [  0   7   2   0 104]]
F1-macro: 0.5875
Accuracy: 0.6136

====================================================================================================
Entrenando (dual-view): linear_svm  — seed=17

=== VAL (dual-view) ===
              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000        71
           1     0.9474    0.9600    0.9536        75
           2     0.9863    0.9730    0.9796       148
           3     0.9867    1.0000    0.9933        74
           4     1.0000    1.0000    1.0000        75

    accuracy                         0.9842       443
   macro avg     0.9841    0.9866    0.9853       443
weighted avg     0.9843    0.9842    0.9842       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  0  72   2   1   0]
 [  0   4 144   0   0]
 [  0   0   0  74   0]
 [  0   0   0   0  75]]
F1-macro: 0.9853
Accuracy: 0.9842

=== TEST (dual-view, fijo) ===
              precision    recall  f1-score   support

           0     0.8947    0.3366    0.4892       101
           1     0.5136    0.8014    0.6260       141
           2     0.6750    0.5912    0.6304       137
           3     0.6585    0.3375    0.4463        80
           4     0.6797    0.9204    0.7820       113

    accuracy                         0.6276       572
   macro avg     0.6843    0.5974    0.5948       572
weighted avg     0.6727    0.6276    0.6086       572

Confusion matrix:
 [[ 34  38  14   3  12]
 [  1 113   8   4  15]
 [  1  34  81   7  14]
 [  2  28  15  27   8]
 [  0   7   2   0 104]]
F1-macro: 0.5948
Accuracy: 0.6276

====================================================================================================
Entrenando (dual-view): sgd_log  — seed=17

=== VAL (dual-view) ===
              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000        71
           1     0.9467    0.9467    0.9467        75
           2     0.9730    0.9730    0.9730       148
           3     0.9863    0.9730    0.9796        74
           4     0.9737    0.9867    0.9801        75

    accuracy                         0.9752       443
   macro avg     0.9759    0.9759    0.9759       443
weighted avg     0.9752    0.9752    0.9752       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  0  71   2   1   1]
 [  0   3 144   0   1]
 [  0   0   2  72   0]
 [  0   1   0   0  74]]
F1-macro: 0.9759
Accuracy: 0.9752

=== TEST (dual-view, fijo) ===
              precision    recall  f1-score   support

           0     0.8537    0.3465    0.4930       101
           1     0.5229    0.8085    0.6351       141
           2     0.6721    0.5985    0.6332       137
           3     0.6842    0.3250    0.4407        80
           4     0.6863    0.9292    0.7895       113

    accuracy                         0.6329       572
   macro avg     0.6838    0.6016    0.5983       572
weighted avg     0.6719    0.6329    0.6129       572

Confusion matrix:
 [[ 35  36  14   3  13]
 [  1 114   8   4  14]
 [  2  34  82   5  14]
 [  3  28  16  26   7]
 [  0   6   2   0 105]]
F1-macro: 0.5983
Accuracy: 0.6329

====================================================================================================
Entrenando (dual-view): passive_aggressive  — seed=17

=== VAL (dual-view) ===
              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000        71
           1     0.9459    0.9333    0.9396        75
           2     0.9664    0.9730    0.9697       148
           3     1.0000    1.0000    1.0000        74
           4     1.0000    1.0000    1.0000        75

    accuracy                         0.9797       443
   macro avg     0.9825    0.9813    0.9819       443
weighted avg     0.9796    0.9797    0.9797       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  0  70   5   0   0]
 [  0   4 144   0   0]
 [  0   0   0  74   0]
 [  0   0   0   0  75]]
F1-macro: 0.9819
Accuracy: 0.9797

=== TEST (dual-view, fijo) ===
              precision    recall  f1-score   support

           0     0.9091    0.2970    0.4478       101
           1     0.5343    0.7730    0.6319       141
           2     0.6500    0.6642    0.6570       137
           3     0.6667    0.3250    0.4370        80
           4     0.6667    0.9204    0.7732       113

    accuracy                         0.6294       572
   macro avg     0.6853    0.5959    0.5894       572
weighted avg     0.6729    0.6294    0.6061       572

Confusion matrix:
 [[ 30  36  18   3  14]
 [  1 109  10   4  17]
 [  1  26  91   6  13]
 [  1  26  19  26   8]
 [  0   7   2   0 104]]
F1-macro: 0.5894
Accuracy: 0.6294

====================================================================================================
Entrenando (dual-view): complement_nb  — seed=17

=== VAL (dual-view) ===
              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000        71
           1     0.8481    0.8933    0.8701        75
           2     0.9786    0.9257    0.9514       148
           3     0.9367    1.0000    0.9673        74
           4     0.9595    0.9467    0.9530        75

    accuracy                         0.9481       443
   macro avg     0.9446    0.9531    0.9484       443
weighted avg     0.9497    0.9481    0.9484       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  0  67   3   3   2]
 [  0  10 137   0   1]
 [  0   0   0  74   0]
 [  0   2   0   2  71]]
F1-macro: 0.9484
Accuracy: 0.9481

=== TEST (dual-view, fijo) ===
              precision    recall  f1-score   support

           0     0.7763    0.5842    0.6667       101
           1     0.5511    0.6879    0.6120       141
           2     0.7524    0.5766    0.6529       137
           3     0.6066    0.4625    0.5248        80
           4     0.6688    0.9115    0.7715       113

    accuracy                         0.6556       572
   macro avg     0.6710    0.6445    0.6456       572
weighted avg     0.6701    0.6556    0.6508       572

Confusion matrix:
 [[ 59  25   6   4   7]
 [  4  97   9  13  18]
 [  4  28  79   7  19]
 [  6  19  11  37   7]
 [  3   7   0   0 103]]
F1-macro: 0.6456
Accuracy: 0.6556

##### SEED = 19 #####

/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1281: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1296: FutureWarning: Using the 'liblinear' solver for multiclass classification is deprecated. An error will be raised in 1.8. Either use another solver which supports the multinomial loss or wrap the estimator in a OneVsRestClassifier to keep applying a one-versus-rest scheme.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1305: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 32.
  warnings.warn(

====================================================================================================
Entrenando (dual-view): logreg_ovr  — seed=19

=== VAL (dual-view) ===
              precision    recall  f1-score   support

           0     0.9861    1.0000    0.9930        71
           1     0.9577    0.9067    0.9315        75
           2     0.9658    0.9527    0.9592       148
           3     0.9610    1.0000    0.9801        74
           4     0.9740    1.0000    0.9868        75

    accuracy                         0.9684       443
   macro avg     0.9689    0.9719    0.9701       443
weighted avg     0.9683    0.9684    0.9681       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  1  68   5   0   1]
 [  0   3 141   3   1]
 [  0   0   0  74   0]
 [  0   0   0   0  75]]
F1-macro: 0.9701
Accuracy: 0.9684

=== TEST (dual-view, fijo) ===
              precision    recall  f1-score   support

           0     0.8723    0.4059    0.5541       101
           1     0.5067    0.8014    0.6209       141
           2     0.7100    0.5182    0.5992       137
           3     0.6383    0.3750    0.4724        80
           4     0.6774    0.9292    0.7836       113

    accuracy                         0.6294       572
   macro avg     0.6810    0.6060    0.6060       572
weighted avg     0.6721    0.6294    0.6153       572

Confusion matrix:
 [[ 41  35   8   5  12]
 [  1 113   8   4  15]
 [  2  41  71   8  15]
 [  3  28  11  30   8]
 [  0   6   2   0 105]]
F1-macro: 0.6060
Accuracy: 0.6294

====================================================================================================
Entrenando (dual-view): linear_svm  — seed=19

=== VAL (dual-view) ===
              precision    recall  f1-score   support

           0     0.9861    1.0000    0.9930        71
           1     1.0000    0.8933    0.9437        75
           2     0.9608    0.9932    0.9767       148
           3     1.0000    1.0000    1.0000        74
           4     0.9740    1.0000    0.9868        75

    accuracy                         0.9797       443
   macro avg     0.9842    0.9773    0.9801       443
weighted avg     0.9803    0.9797    0.9793       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  1  67   6   0   1]
 [  0   0 147   0   1]
 [  0   0   0  74   0]
 [  0   0   0   0  75]]
F1-macro: 0.9801
Accuracy: 0.9797

=== TEST (dual-view, fijo) ===
              precision    recall  f1-score   support

           0     0.9487    0.3663    0.5286       101
           1     0.5407    0.8014    0.6457       141
           2     0.6615    0.6277    0.6442       137
           3     0.7250    0.3625    0.4833        80
           4     0.6818    0.9292    0.7865       113

    accuracy                         0.6469       572
   macro avg     0.7115    0.6174    0.6177       572
weighted avg     0.6953    0.6469    0.6298       572

Confusion matrix:
 [[ 37  32  16   3  13]
 [  0 113  10   4  14]
 [  1  32  86   4  14]
 [  1  26  16  29   8]
 [  0   6   2   0 105]]
F1-macro: 0.6177
Accuracy: 0.6469

====================================================================================================
Entrenando (dual-view): sgd_log  — seed=19

=== VAL (dual-view) ===
              precision    recall  f1-score   support

           0     0.9861    1.0000    0.9930        71
           1     1.0000    0.8933    0.9437        75
           2     0.9603    0.9797    0.9699       148
           3     0.9737    1.0000    0.9867        74
           4     0.9740    1.0000    0.9868        75

    accuracy                         0.9752       443
   macro avg     0.9788    0.9746    0.9760       443
weighted avg     0.9757    0.9752    0.9748       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  1  67   6   0   1]
 [  0   0 145   2   1]
 [  0   0   0  74   0]
 [  0   0   0   0  75]]
F1-macro: 0.9760
Accuracy: 0.9752

=== TEST (dual-view, fijo) ===
              precision    recall  f1-score   support

           0     0.8636    0.3762    0.5241       101
           1     0.5359    0.7943    0.6400       141
           2     0.6800    0.6204    0.6489       137
           3     0.7000    0.3500    0.4667        80
           4     0.6818    0.9292    0.7865       113

    accuracy                         0.6434       572
   macro avg     0.6923    0.6140    0.6132       572
weighted avg     0.6801    0.6434    0.6264       572

Confusion matrix:
 [[ 38  33  14   4  12]
 [  1 112   9   4  15]
 [  2  32  85   4  14]
 [  3  26  15  28   8]
 [  0   6   2   0 105]]
F1-macro: 0.6132
Accuracy: 0.6434

====================================================================================================
Entrenando (dual-view): passive_aggressive  — seed=19

=== VAL (dual-view) ===
              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000        71
           1     1.0000    0.8800    0.9362        75
           2     0.9484    0.9932    0.9703       148
           3     1.0000    1.0000    1.0000        74
           4     0.9740    1.0000    0.9868        75

    accuracy                         0.9774       443
   macro avg     0.9845    0.9746    0.9787       443
weighted avg     0.9784    0.9774    0.9770       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  0  66   8   0   1]
 [  0   0 147   0   1]
 [  0   0   0  74   0]
 [  0   0   0   0  75]]
F1-macro: 0.9787
Accuracy: 0.9774

=== TEST (dual-view, fijo) ===
              precision    recall  f1-score   support

           0     0.9310    0.2673    0.4154       101
           1     0.5521    0.7518    0.6366       141
           2     0.5949    0.6861    0.6373       137
           3     0.6579    0.3125    0.4237        80
           4     0.6774    0.9292    0.7836       113

    accuracy                         0.6241       572
   macro avg     0.6827    0.5894    0.5793       572
weighted avg     0.6688    0.6241    0.5970       572

Confusion matrix:
 [[ 27  32  25   5  12]
 [  0 106  15   4  16]
 [  1  26  94   4  12]
 [  1  23  21  25  10]
 [  0   5   3   0 105]]
F1-macro: 0.5793
Accuracy: 0.6241

====================================================================================================
Entrenando (dual-view): complement_nb  — seed=19

=== VAL (dual-view) ===
              precision    recall  f1-score   support

           0     0.9861    1.0000    0.9930        71
           1     0.9054    0.8933    0.8993        75
           2     0.9724    0.9527    0.9625       148
           3     0.9605    0.9865    0.9733        74
           4     0.9474    0.9600    0.9536        75

    accuracy                         0.9571       443
   macro avg     0.9544    0.9585    0.9564       443
weighted avg     0.9570    0.9571    0.9570       443

Confusion matrix:
 [[ 71   0   0   0   0]
 [  1  67   3   0   4]
 [  0   4 141   3   0]
 [  0   1   0  73   0]
 [  0   2   1   0  72]]
F1-macro: 0.9564
Accuracy: 0.9571

=== TEST (dual-view, fijo) ===
              precision    recall  f1-score   support

           0     0.7949    0.6139    0.6927       101
           1     0.5714    0.7092    0.6329       141
           2     0.7547    0.5839    0.6584       137
           3     0.6167    0.4625    0.5286        80
           4     0.6863    0.9292    0.7895       113

    accuracy                         0.6713       572
   macro avg     0.6848    0.6597    0.6604       572
weighted avg     0.6838    0.6713    0.6659       572

Confusion matrix:
 [[ 62  23   6   4   6]
 [  3 100   8  11  19]
 [  4  28  80   8  17]
 [  6  21  10  37   6]
 [  3   3   2   0 105]]
F1-macro: 0.6604
Accuracy: 0.6713

=====================================
Resumen Multi-Seed (dual-view, 95% CI)
=====================================
             model  val_f1_macro_mean  val_f1_macro_std  val_f1_macro_CI_low  val_f1_macro_CI_high  test_f1_macro_mean  test_f1_macro_std  test_f1_macro_CI_low  test_f1_macro_CI_high
        linear_svm           0.986012          0.005964             0.980784              0.991240            0.606916           0.009183              0.598866               0.614965
passive_aggressive           0.985681          0.008635             0.978112              0.993249            0.589827           0.010742              0.580411               0.599243
           sgd_log           0.980131          0.008463             0.972712              0.987549            0.604594           0.006636              0.598778               0.610411
        logreg_ovr           0.973096          0.009082             0.965135              0.981056            0.595477           0.007028              0.589317               0.601638
     complement_nb           0.948422          0.008715             0.940782              0.956061            0.654592           0.006824              0.648610               0.660573

/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1281: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1296: FutureWarning: Using the 'liblinear' solver for multiclass classification is deprecated. An error will be raised in 1.8. Either use another solver which supports the multinomial loss or wrap the estimator in a OneVsRestClassifier to keep applying a one-versus-rest scheme.
  warnings.warn(
/home/mrodrive/miniconda3/envs/hs-env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1305: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 32.
  warnings.warn(

,model,val_f1_macro_mean,val_f1_macro_std,val_f1_macro_CI_low,val_f1_macro_CI_high,test_f1_macro_mean,test_f1_macro_std,test_f1_macro_CI_low,test_f1_macro_CI_high
1,linear_svm,0.986012,0.005964,0.980784,0.991240,0.606916,0.009183,0.598866,0.614965
3,passive_aggressive,0.985681,0.008635,0.978112,0.993249,0.589827,0.010742,0.580411,0.599243
4,sgd_log,0.980131,0.008463,0.972712,0.987549,0.604594,0.006636,0.598778,0.610411
2,logreg_ovr,0.973096,0.009082,0.965135,0.981056,0.595477,0.007028,0.589317,0.601638
0,complement_nb,0.948422,0.008715,0.940782,0.956061,0.654592,0.006824,0.648610,0.660573

In [62]:
df_summary_dual

,model,val_f1_macro_mean,val_f1_macro_std,val_f1_macro_CI_low,val_f1_macro_CI_high,test_f1_macro_mean,test_f1_macro_std,test_f1_macro_CI_low,test_f1_macro_CI_high
4,sgd_log,0.812553,0.047141,0.771232,0.853874,0.640961,0.013899,0.628777,0.653144
1,linear_svm,0.806271,0.031544,0.778621,0.833921,0.636804,0.010158,0.627900,0.645707
3,passive_aggressive,0.797912,0.044321,0.759063,0.836761,0.618875,0.025060,0.596909,0.640841
2,logreg_ovr,0.787567,0.037245,0.754920,0.820214,0.638123,0.012751,0.626947,0.649300
0,complement_nb,0.698375,0.022067,0.679032,0.717718,0.635388,0.010188,0.626458,0.644318

In [64]:
df_summary_dual

,model,val_f1_macro_mean,val_f1_macro_std,val_f1_macro_CI_low,val_f1_macro_CI_high,test_f1_macro_mean,test_f1_macro_std,test_f1_macro_CI_low,test_f1_macro_CI_high
1,linear_svm,0.986012,0.005964,0.980784,0.991240,0.606916,0.009183,0.598866,0.614965
3,passive_aggressive,0.985681,0.008635,0.978112,0.993249,0.589827,0.010742,0.580411,0.599243
4,sgd_log,0.980131,0.008463,0.972712,0.987549,0.604594,0.006636,0.598778,0.610411
2,logreg_ovr,0.973096,0.009082,0.965135,0.981056,0.595477,0.007028,0.589317,0.601638
0,complement_nb,0.948422,0.008715,0.940782,0.956061,0.654592,0.006824,0.648610,0.660573

In [ ]:
df_summary

,model,val_f1_macro_mean,val_f1_macro_std,val_f1_macro_CI_low,val_f1_macro_CI_high,test_f1_macro_mean,test_f1_macro_std,test_f1_macro_CI_low,test_f1_macro_CI_high
4,sgd_log,0.704571,0.045734,0.664483,0.744658,0.635265,0.034575,0.604959,0.665571
1,linear_svm,0.691243,0.049450,0.647898,0.734588,0.626857,0.043943,0.588339,0.665375
3,passive_aggressive,0.689503,0.058110,0.638567,0.740439,0.614215,0.037882,0.581010,0.647420
2,logreg_ovr,0.621616,0.023852,0.600708,0.642524,0.587858,0.036573,0.555800,0.619916
0,complement_nb,0.584789,0.029115,0.559268,0.610309,0.570786,0.029560,0.544875,0.596697

In [ ]:
df_summary

,model,val_f1_macro_mean,val_f1_macro_std,val_f1_macro_CI_low,val_f1_macro_CI_high,test_f1_macro_mean,test_f1_macro_std,test_f1_macro_CI_low,test_f1_macro_CI_high
3,passive_aggressive,0.986146,0.004920,0.981834,0.990459,0.573849,0.011785,0.563520,0.584179
1,linear_svm,0.982166,0.003895,0.978752,0.985580,0.625455,0.006698,0.619584,0.631326
4,sgd_log,0.975202,0.004870,0.970934,0.979471,0.627862,0.006536,0.622132,0.633591
2,logreg_ovr,0.964467,0.006119,0.959103,0.969830,0.638500,0.001303,0.637358,0.639642
0,complement_nb,0.931495,0.014556,0.918736,0.944254,0.626433,0.004067,0.622868,0.629998